[package]
name = "visitgen"
version = "0.1.0"
authors = ["Patrick Meredith <pmeredit@protonmail.com>"]
edition = "2018"

[dependencies]
syn = { version = "1", features = ["visit", "full"] }
lazy_static = "1"
