linters-settings:
  govet:
    check-shadowing: true
linters:
  enable:
    - deadcode
    - errcheck
    - gofmt
    - goimports
    - golint
    - govet
    - ineffassign
    - megacheck
    - misspell
    - structcheck
    - unconvert
    - unparam
    - varcheck
  fast: false
issues:
    exclude-use-default: false
    exclude:
        # errcheck: Almost all programs ignore errors on these functions and in most cases it's ok
        - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked
output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
run:
  build-tags:
    - "gssapi,integration"
  concurrency: 4
  deadline: 3m
  issues-exit-code: 1
  max-same-issues: 1
  skip-files:
    - "parser/sql.go"
    - "parser/sql.y"
    - "parser/yaccpar"
