[workspace]

members = [
    "benchmark/pipeline_generator",
    "e2e-tests",
    "mongosql-datastructures",
    "mongosql-c",
    "mongosql",
    "usererrordisplay-impl",
    "visitgen",
    "visitgen-test",
]
