required = ["github.com/go-sql-driver/mysql"]

#
# dependencies from github.com/10gen
#

[[constraint]]
  name = "github.com/10gen/candiedyaml"
  branch = "master"

[[constraint]]
  name = "github.com/10gen/mongo-go-driver"
  source = "github.com/jstewart-mongo/mongo-go-driver"
  revision = "1d4cd22d0f723bd468ba081ccff07aa16c68f7de"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  source = "github.com/10gen/mysql"
  branch = "master"

[[constraint]]
  name = "github.com/10gen/openssl"
  branch = "master"

#
# dependencies from github.com/mongodb
#

[[constraint]]
  name = "github.com/mongodb/mongo-tools"
  branch = "master"

#
# third-party dependencies
#

[[constraint]]
  name = "github.com/jessevdk/go-flags"
  branch = "master"

[[constraint]]
  name = "github.com/kardianos/service"
  branch = "master"

[[constraint]]
  name = "github.com/kr/pretty"
  branch = "master"

[[constraint]]
  name = "github.com/shopspring/decimal"
  revision = "d6f52241f332c63811249bd79a522406bea1a7c9"

[[constraint]]
  name = "github.com/smartystreets/goconvey"
  version = "1.6.2"

[[constraint]]
  name = "golang.org/x/crypto"
  branch = "master"

[[constraint]]
  name = "golang.org/x/text"
  branch = "master"

[[constraint]]
  name = "github.com/stretchr/testify"
  branch = "master"

[[constraint]]
  name = "github.com/xdg/stringprep"
  branch = "master"
