uri: mongodb://localhost:27017
username: user
password: hunter2
nsInclude:
  - mydb.foo
  - mydb.bar
nsExclude:
  - mydb.baz
quiet: false
logpath: C:\Users\user\Documents\schema-builder\logs\schema-builder.log
verbosity: DEBUG
schemaAction: overwrite
