package evaluator

import (
	"github.com/10gen/sqlproxy/collation"
)

// SubquerySourceStage handles taking sourced rows and projecting them into an alias.
type SubquerySourceStage struct {
	// aliasName is the alias for all the columns from the subquery.
	aliasName string
	// dbName is the database from which this table was derived. It is empty if this
	// subquery is a result of a multi-database join.
	dbName string
	// selectID is the selectID for the resulting columns.
	selectID int
	// source is the operator that provides the data to the subquery.
	source PlanStage
	// Indicates whether it is a true subquery or if it was generated by a CTE.
	fromCTE bool
}

// NewSubquerySourceStage creates a new SubquerySourceStage.
func NewSubquerySourceStage(source PlanStage, selectID int, dbName,
	aliasName string, fromCTE bool) *SubquerySourceStage {
	return &SubquerySourceStage{
		source:    source,
		selectID:  selectID,
		aliasName: aliasName,
		dbName:    dbName,
		fromCTE:   fromCTE,
	}
}

// Open returns an iterator that returns results from executing this plan stage
// with the given ExecutionContext.
func (s *SubquerySourceStage) Open(ctx *ExecutionCtx) (Iter, error) {
	sourceIter, err := s.source.Open(ctx)
	if err != nil {
		return nil, err
	}

	var projectedColumns ProjectedColumns

	for _, column := range s.source.Columns() {
		projectedColumn := column.projectAs(column.Name)
		projectedColumn.SelectID = s.selectID
		projectedColumn.Table = s.aliasName
		projectedColumns = append(projectedColumns, projectedColumn)
	}

	return &ProjectIter{
		ctx:              ctx,
		memoryMonitor:    ctx.MemoryMonitor(),
		source:           sourceIter,
		projectedColumns: projectedColumns,
	}, nil
}

// Columns returns the ordered set of columns that are contained in results from this plan.
func (s *SubquerySourceStage) Columns() []*Column {
	var columns []*Column
	for _, column := range s.source.Columns() {
		c := column.clone()
		c.SelectID = s.selectID
		c.Table = s.aliasName
		columns = append(columns, c)
	}

	return columns
}

// Collation returns the collation to use for comparisons.
func (s *SubquerySourceStage) Collation() *collation.Collation {
	return s.source.Collation()
}

func (s *SubquerySourceStage) clone() PlanStage {
	return NewSubquerySourceStage(s.source.clone(), s.selectID, s.dbName, s.aliasName, s.fromCTE)
}
