package evaluator

import (
	"context"

	"github.com/10gen/sqlproxy/collation"
	"github.com/10gen/sqlproxy/evaluator/results"
)

// SubquerySourceStage handles taking sourced rows and projecting them into an alias.
type SubquerySourceStage struct {
	// aliasName is the alias for all the columns from the subquery.
	aliasName string
	// dbName is the database from which this table was derived. It is empty if this
	// subquery is a result of a multi-database join.
	dbName string
	// selectID is the selectID for the resulting columns.
	selectID int
	// source is the operator that provides the data to the subquery.
	source PlanStage
	// Indicates whether it is a true subquery or if it was generated by a CTE.
	fromCTE bool
}

// Children returns a slice of all the Node children of the Node.
func (s SubquerySourceStage) Children() []Node {
	return []Node{s.source}
}

// ReplaceChild replaces the i'th child of the receiver Node with the Node n.
func (s *SubquerySourceStage) ReplaceChild(i int, n Node) {
	switch i {
	case 0:
		s.source = panicIfNotPlanStage("SubquerySourceStage", n)
	default:
		panicWithInvalidIndex("SubquerySourceStage", i, 0)
	}
}

// NewSubquerySourceStage creates a new SubquerySourceStage.
func NewSubquerySourceStage(source PlanStage, selectID int, dbName,
	aliasName string, fromCTE bool) *SubquerySourceStage {
	return &SubquerySourceStage{
		source:    source,
		selectID:  selectID,
		aliasName: aliasName,
		dbName:    dbName,
		fromCTE:   fromCTE,
	}
}

// Open returns an iterator that returns results from executing this plan stage
// with the given ExecutionContext.
func (s *SubquerySourceStage) Open(ctx context.Context, cfg *ExecutionConfig, st *ExecutionState) (results.RowIter, error) {
	sourceIter, err := s.source.Open(ctx, cfg, st)
	if err != nil {
		return nil, err
	}

	var projectedColumns ProjectedColumns

	for _, column := range s.source.Columns() {
		projectedColumn := newProjectedColumnFromColumn(column)
		projectedColumn.SelectID = s.selectID
		projectedColumn.Table = s.aliasName
		projectedColumns = append(projectedColumns, projectedColumn)
	}

	return &ProjectIter{
		cfg:              cfg,
		st:               st,
		memoryMonitor:    cfg.memoryMonitor,
		source:           sourceIter,
		projectedColumns: projectedColumns,
	}, nil
}

// Columns returns the ordered set of columns that are contained in results from this plan.
func (s *SubquerySourceStage) Columns() []*results.Column {
	var columns []*results.Column
	for _, column := range s.source.Columns() {
		c := column.Clone()
		c.SelectID = s.selectID
		c.Table = s.aliasName
		columns = append(columns, c)
	}

	return columns
}

// Collation returns the collation to use for comparisons.
func (s *SubquerySourceStage) Collation() *collation.Collation {
	return s.source.Collation()
}

func (s *SubquerySourceStage) clone() PlanStage {
	return NewSubquerySourceStage(s.source.clone(), s.selectID, s.dbName, s.aliasName, s.fromCTE)
}
