uri: mongodb://localhost:27017
username: user
password: hunter2
ns-include:
  - mydb.foo
  - mydb.bar
ns-exclude:
  - mydb.baz
quiet: false
logpath: C:\Users\user\Documents\mongodb-schema-manager\logs\
verbosity: DEBUG
action: overwrite
