[package]
name = "schema-derivation"
version = "0.0.0"
edition = "2021"

[dependencies]
agg-ast = { path = "../ast" }
bson = { version = "2", features = ["chrono-0_4"] }
mongosql = { path = "../../mongosql" }
serde_json = "1"
thiserror = "1"

[features]
