// Code generated by 'go generate'. DO NOT EDIT.

package variable

import (
	"fmt"
	"math"

	"github.com/10gen/sqlproxy/collation"
	"github.com/10gen/sqlproxy/internal/config"
	"github.com/10gen/sqlproxy/internal/mysqlerrors"
	"github.com/10gen/sqlproxy/schema"
)

// These variables hold system variable names.
const (
	Autocommit                    Name = "autocommit"
	CharacterSetClient            Name = "character_set_client"
	CharacterSetConnection        Name = "character_set_connection"
	CharacterSetDatabase          Name = "character_set_database"
	CharacterSetResults           Name = "character_set_results"
	CollationConnection           Name = "collation_connection"
	CollationDatabase             Name = "collation_database"
	CollationServer               Name = "collation_server"
	GroupConcatMaxLen             Name = "group_concat_max_len"
	InteractiveTimeoutSecs        Name = "interactive_timeout"
	MaxAllowedPacket              Name = "max_allowed_packet"
	MaxConnections                Name = "max_connections"
	MaxTimeMS                     Name = "max_execution_time"
	Socket                        Name = "socket"
	SQLAutoIsNull                 Name = "sql_auto_is_null"
	SQLSelectLimit                Name = "sql_select_limit"
	Version                       Name = "version"
	VersionComment                Name = "version_comment"
	WaitTimeoutSecs               Name = "wait_timeout"
	AnonymizeMetrics              Name = "anonymize_metrics"
	EnableTableAlterations        Name = "enable_table_alterations"
	FullPushdownExecMode          Name = "full_pushdown_exec_mode"
	LogLevel                      Name = "log_level"
	MaxNestedTableDepth           Name = "max_nested_table_depth"
	MaxNumColumnsPerTable         Name = "max_num_columns_per_table"
	MetricsBackend                Name = "metrics_backend"
	MongoDBMaxServerSize          Name = "mongodb_max_server_size"
	MongoDBMaxConnectionSize      Name = "mongodb_max_connection_size"
	MongoDBMaxStageSize           Name = "mongodb_max_stage_size"
	MongoDBMaxVarcharLength       Name = "mongodb_max_varchar_length"
	MongoDBGitVersion             Name = "mongodb_git_version"
	MongoDBTopology               Name = "mongodb_topology"
	MongoDBVersion                Name = "mongodb_version"
	MongoDBVersionCompatibility   Name = "mongodb_version_compatibility"
	MongosqldVersion              Name = "mongosqld_version"
	OptimizeCrossJoins            Name = "optimize_cross_joins"
	OptimizeEvaluations           Name = "optimize_evaluations"
	OptimizeFiltering             Name = "optimize_filtering"
	OptimizeInnerJoins            Name = "optimize_inner_joins"
	OptimizeSelfJoins             Name = "optimize_self_joins"
	OptimizeViewSampling          Name = "optimize_view_sampling"
	PolymorphicTypeConversionMode Name = "polymorphic_type_conversion_mode"
	Pushdown                      Name = "pushdown"
	RewriteDistinctAsGroup        Name = "rewrite_distinct_as_group"
	SampleRefreshIntervalSecs     Name = "sample_refresh_interval_secs"
	SampleSize                    Name = "sample_size"
	SchemaMappingMode             Name = "schema_mapping_mode"
	TypeConversionMode            Name = "type_conversion_mode"
)

// These are constants representing variants of enum-style variables.
const (
	// MetricsBackend variants
	NoMetricsBackend     = "off"
	LogMetricsBackend    = "log"
	StitchMetricsBackend = "stitch"

	// PolymorphicTypeConversionMode variants
	SafePolymorphicTypeConversionMode = "safe"
	FastPolymorphicTypeConversionMode = "fast"
	OffPolymorphicTypeConversionMode  = "off"

	// SchemaMappingMode variants
	MajoritySchemaMappingMode = "majority"
	LatticeSchemaMappingMode  = "lattice"

	// TypeConversionMode variants
	MongoSQLTypeConversionMode = "mongosql"
	MySQLTypeConversionMode    = "mysql"
)

// These are constants representing variables' default values.
var (
	defaultAutocommit                    bool   = true
	defaultCharacterSetClient            string = string(collation.DefaultCharset.Name)
	defaultCharacterSetConnection        string = string(collation.DefaultCharset.Name)
	defaultCharacterSetDatabase          string = string(collation.DefaultCharset.Name)
	defaultCharacterSetResults           string = string(collation.DefaultCharset.Name)
	defaultCollationConnection           string = string(collation.Default.Name)
	defaultCollationDatabase             string = string(collation.Default.Name)
	defaultCollationServer               string = string(collation.Default.Name)
	defaultGroupConcatMaxLen             int64  = 1024
	defaultInteractiveTimeoutSecs        int64  = 28800
	defaultMaxAllowedPacket              int64  = 1073741824
	defaultMaxConnections                int64  = 0
	defaultMaxTimeMS                     int64  = 0
	defaultSocket                        string = ""
	defaultSQLAutoIsNull                 bool   = false
	defaultSQLSelectLimit                uint64 = math.MaxUint64
	defaultVersion                       string = "5.7.12"
	defaultVersionComment                string = fmt.Sprintf("mongosqld " + config.VersionStr)
	defaultWaitTimeoutSecs               int64  = 28800
	defaultAnonymizeMetrics              bool   = true
	defaultEnableTableAlterations        bool   = false
	defaultFullPushdownExecMode          bool   = false
	defaultLogLevel                      int64  = 0
	defaultMaxNestedTableDepth           int64  = 50
	defaultMaxNumColumnsPerTable         int64  = 2000
	defaultMetricsBackend                string = NoMetricsBackend
	defaultMongoDBMaxServerSize          uint64 = 0
	defaultMongoDBMaxConnectionSize      uint64 = 0
	defaultMongoDBMaxStageSize           uint64 = 0
	defaultMongoDBMaxVarcharLength       uint16 = math.MaxUint16
	defaultMongoDBGitVersion             string = ""
	defaultMongoDBTopology               string = ""
	defaultMongoDBVersion                string = ""
	defaultMongoDBVersionCompatibility   string = ""
	defaultMongosqldVersion              string = config.VersionStr
	defaultOptimizeCrossJoins            bool   = true
	defaultOptimizeEvaluations           bool   = true
	defaultOptimizeFiltering             bool   = true
	defaultOptimizeInnerJoins            bool   = true
	defaultOptimizeSelfJoins             bool   = true
	defaultOptimizeViewSampling          bool   = true
	defaultPolymorphicTypeConversionMode string = OffPolymorphicTypeConversionMode
	defaultPushdown                      bool   = true
	defaultRewriteDistinctAsGroup        bool   = false
	defaultSampleRefreshIntervalSecs     int64  = 0
	defaultSampleSize                    int64  = 1000
	defaultSchemaMappingMode             string = LatticeSchemaMappingMode
	defaultTypeConversionMode            string = MongoSQLTypeConversionMode
)

type systemVariableContainer struct {
	autocommit                    bool
	characterSetClient            string
	characterSetConnection        string
	characterSetDatabase          string
	characterSetResults           string
	collationConnection           string
	collationDatabase             string
	collationServer               string
	groupConcatMaxLen             int64
	interactiveTimeoutSecs        int64
	maxAllowedPacket              int64
	maxConnections                int64
	maxTimeMS                     int64
	socket                        string
	sqlAutoIsNull                 bool
	sqlSelectLimit                uint64
	version                       string
	versionComment                string
	waitTimeoutSecs               int64
	anonymizeMetrics              bool
	enableTableAlterations        bool
	fullPushdownExecMode          bool
	logLevel                      int64
	maxNestedTableDepth           int64
	maxNumColumnsPerTable         int64
	metricsBackend                string
	mongoDBMaxServerSize          uint64
	mongoDBMaxConnectionSize      uint64
	mongoDBMaxStageSize           uint64
	mongoDBMaxVarcharLength       uint16
	mongoDBGitVersion             string
	mongoDBTopology               string
	mongoDBVersion                string
	mongoDBVersionCompatibility   string
	mongosqldVersion              string
	optimizeCrossJoins            bool
	optimizeEvaluations           bool
	optimizeFiltering             bool
	optimizeInnerJoins            bool
	optimizeSelfJoins             bool
	optimizeViewSampling          bool
	polymorphicTypeConversionMode string
	pushdown                      bool
	rewriteDistinctAsGroup        bool
	sampleRefreshIntervalSecs     int64
	sampleSize                    int64
	schemaMappingMode             string
	typeConversionMode            string
}

func (svc *systemVariableContainer) setDefaults() {
	svc.autocommit = defaultAutocommit
	svc.characterSetClient = defaultCharacterSetClient
	svc.characterSetConnection = defaultCharacterSetConnection
	svc.characterSetDatabase = defaultCharacterSetDatabase
	svc.characterSetResults = defaultCharacterSetResults
	svc.collationConnection = defaultCollationConnection
	svc.collationDatabase = defaultCollationDatabase
	svc.collationServer = defaultCollationServer
	svc.groupConcatMaxLen = defaultGroupConcatMaxLen
	svc.interactiveTimeoutSecs = defaultInteractiveTimeoutSecs
	svc.maxAllowedPacket = defaultMaxAllowedPacket
	svc.maxConnections = defaultMaxConnections
	svc.maxTimeMS = defaultMaxTimeMS
	svc.socket = defaultSocket
	svc.sqlAutoIsNull = defaultSQLAutoIsNull
	svc.sqlSelectLimit = defaultSQLSelectLimit
	svc.version = defaultVersion
	svc.versionComment = defaultVersionComment
	svc.waitTimeoutSecs = defaultWaitTimeoutSecs
	svc.anonymizeMetrics = defaultAnonymizeMetrics
	svc.enableTableAlterations = defaultEnableTableAlterations
	svc.fullPushdownExecMode = defaultFullPushdownExecMode
	svc.logLevel = defaultLogLevel
	svc.maxNestedTableDepth = defaultMaxNestedTableDepth
	svc.maxNumColumnsPerTable = defaultMaxNumColumnsPerTable
	svc.metricsBackend = defaultMetricsBackend
	svc.mongoDBMaxServerSize = defaultMongoDBMaxServerSize
	svc.mongoDBMaxConnectionSize = defaultMongoDBMaxConnectionSize
	svc.mongoDBMaxStageSize = defaultMongoDBMaxStageSize
	svc.mongoDBMaxVarcharLength = defaultMongoDBMaxVarcharLength
	svc.mongoDBGitVersion = defaultMongoDBGitVersion
	svc.mongoDBTopology = defaultMongoDBTopology
	svc.mongoDBVersion = defaultMongoDBVersion
	svc.mongoDBVersionCompatibility = defaultMongoDBVersionCompatibility
	svc.mongosqldVersion = defaultMongosqldVersion
	svc.optimizeCrossJoins = defaultOptimizeCrossJoins
	svc.optimizeEvaluations = defaultOptimizeEvaluations
	svc.optimizeFiltering = defaultOptimizeFiltering
	svc.optimizeInnerJoins = defaultOptimizeInnerJoins
	svc.optimizeSelfJoins = defaultOptimizeSelfJoins
	svc.optimizeViewSampling = defaultOptimizeViewSampling
	svc.polymorphicTypeConversionMode = defaultPolymorphicTypeConversionMode
	svc.pushdown = defaultPushdown
	svc.rewriteDistinctAsGroup = defaultRewriteDistinctAsGroup
	svc.sampleRefreshIntervalSecs = defaultSampleRefreshIntervalSecs
	svc.sampleSize = defaultSampleSize
	svc.schemaMappingMode = defaultSchemaMappingMode
	svc.typeConversionMode = defaultTypeConversionMode
}

func (svc *systemVariableContainer) setFromConfig(cfg *config.Config) {
	svc.anonymizeMetrics = cfg.SetParameter.AnonymizeMetrics
	svc.enableTableAlterations = cfg.SetParameter.EnableTableAlterations
	svc.logLevel = cfg.SystemLog.Level()
	svc.maxNestedTableDepth = cfg.Schema.Sample.MaxNestedTableDepth
	svc.maxNumColumnsPerTable = cfg.Schema.Sample.MaxNumColumnsPerTable
	svc.metricsBackend = cfg.SetParameter.MetricsBackend
	svc.mongoDBMaxServerSize = cfg.Runtime.Memory.MaxPerServer
	svc.mongoDBMaxConnectionSize = cfg.Runtime.Memory.MaxPerConnection
	svc.mongoDBMaxStageSize = cfg.Runtime.Memory.MaxPerStage
	svc.mongoDBMaxVarcharLength = cfg.Schema.MaxVarcharLength
	svc.mongoDBVersionCompatibility = cfg.MongoDB.VersionCompatibility
	svc.optimizeCrossJoins = cfg.SetParameter.OptimizeCrossJoins
	svc.optimizeEvaluations = cfg.SetParameter.OptimizeEvaluations
	svc.optimizeFiltering = cfg.SetParameter.OptimizeFiltering
	svc.optimizeInnerJoins = cfg.SetParameter.OptimizeInnerJoins
	svc.optimizeSelfJoins = cfg.SetParameter.OptimizeSelfJoins
	svc.optimizeViewSampling = cfg.SetParameter.OptimizeViewSampling
	svc.polymorphicTypeConversionMode = cfg.SetParameter.PolymorphicTypeConversionMode
	svc.pushdown = cfg.SetParameter.Pushdown
	svc.rewriteDistinctAsGroup = cfg.SetParameter.RewriteDistinctAsGroup
	svc.sampleRefreshIntervalSecs = cfg.Schema.Sample.RefreshIntervalSecs
	svc.sampleSize = cfg.Schema.Sample.Size
	svc.schemaMappingMode = cfg.Schema.Sample.SchemaMappingMode
	svc.typeConversionMode = cfg.SetParameter.TypeConversionMode
}

func init() {

	definitions[Autocommit] = &definition{
		Name:             Autocommit,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope | SessionScope,
		SQLType:          schema.SQLBoolean,
		GetValue:         func(c *Container) interface{} { return c.systemVariableContainer.autocommit },
		SetValue:         setAutocommit,
	}

	definitions[CharacterSetClient] = &definition{
		Name:             CharacterSetClient,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope | SessionScope,
		SQLType:          schema.SQLVarchar,
		GetValue:         func(c *Container) interface{} { return c.systemVariableContainer.characterSetClient },
		SetValue:         setCharacterSetClient,
	}

	definitions[CharacterSetConnection] = &definition{
		Name:             CharacterSetConnection,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope | SessionScope,
		SQLType:          schema.SQLVarchar,
		GetValue:         func(c *Container) interface{} { return c.systemVariableContainer.characterSetConnection },
		SetValue:         setCharacterSetConnection,
	}

	definitions[CharacterSetDatabase] = &definition{
		Name:             CharacterSetDatabase,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope | SessionScope,
		SQLType:          schema.SQLVarchar,
		GetValue:         func(c *Container) interface{} { return c.systemVariableContainer.characterSetDatabase },
		SetValue:         setCharacterSetDatabase,
	}

	definitions[CharacterSetResults] = &definition{
		Name:             CharacterSetResults,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope | SessionScope,
		SQLType:          schema.SQLVarchar,
		GetValue:         getCharacterSetResults,
		SetValue:         setCharacterSetResults,
	}

	definitions[CollationConnection] = &definition{
		Name:             CollationConnection,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope | SessionScope,
		SQLType:          schema.SQLVarchar,
		GetValue:         func(c *Container) interface{} { return c.systemVariableContainer.collationConnection },
		SetValue:         setCollationConnection,
	}

	definitions[CollationDatabase] = &definition{
		Name:             CollationDatabase,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope | SessionScope,
		SQLType:          schema.SQLVarchar,
		GetValue:         func(c *Container) interface{} { return c.systemVariableContainer.collationDatabase },
		SetValue:         setCollationDatabase,
	}

	definitions[CollationServer] = &definition{
		Name:             CollationServer,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope | SessionScope,
		SQLType:          schema.SQLVarchar,
		GetValue:         func(c *Container) interface{} { return c.systemVariableContainer.collationServer },
		SetValue:         setCollationServer,
	}

	definitions[GroupConcatMaxLen] = &definition{
		Name:             GroupConcatMaxLen,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope | SessionScope,
		SQLType:          schema.SQLInt,
		GetValue:         func(c *Container) interface{} { return c.systemVariableContainer.groupConcatMaxLen },
		SetValue:         setGroupConcatMaxLen,
	}

	definitions[InteractiveTimeoutSecs] = &definition{
		Name:             InteractiveTimeoutSecs,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope | SessionScope,
		SQLType:          schema.SQLInt,
		GetValue:         func(c *Container) interface{} { return c.systemVariableContainer.interactiveTimeoutSecs },
		SetValue:         setInteractiveTimeoutSecs,
	}

	definitions[MaxAllowedPacket] = &definition{
		Name:             MaxAllowedPacket,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope | SessionScope,
		SQLType:          schema.SQLInt,
		GetValue:         func(c *Container) interface{} { return c.systemVariableContainer.maxAllowedPacket },
		SetValue:         setMaxAllowedPacket,
	}

	definitions[MaxConnections] = &definition{
		Name:             MaxConnections,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope,
		SQLType:          schema.SQLInt,
		GetValue:         func(c *Container) interface{} { return c.systemVariableContainer.maxConnections },
		SetValue:         setMaxConnections,
	}

	definitions[MaxTimeMS] = &definition{
		Name:             MaxTimeMS,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope | SessionScope,
		SQLType:          schema.SQLInt,
		GetValue:         func(c *Container) interface{} { return c.systemVariableContainer.maxTimeMS },
		SetValue:         setMaxTimeMS,
	}

	definitions[Socket] = &definition{
		Name:             Socket,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope,
		SQLType:          schema.SQLVarchar,
		GetValue:         func(c *Container) interface{} { return c.systemVariableContainer.socket },
		SetValue:         setSocket,
	}

	definitions[SQLAutoIsNull] = &definition{
		Name:             SQLAutoIsNull,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope | SessionScope,
		SQLType:          schema.SQLBoolean,
		GetValue:         func(c *Container) interface{} { return c.systemVariableContainer.sqlAutoIsNull },
		SetValue:         setSQLAutoIsNull,
	}

	definitions[SQLSelectLimit] = &definition{
		Name:             SQLSelectLimit,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope | SessionScope,
		SQLType:          schema.SQLUint,
		GetValue:         func(c *Container) interface{} { return c.systemVariableContainer.sqlSelectLimit },
		SetValue:         setSQLSelectLimit,
	}

	definitions[Version] = &definition{
		Name:             Version,
		Kind:             SystemKind,
		AllowedSetScopes: Scope(0),
		SQLType:          schema.SQLVarchar,
		GetValue:         func(c *Container) interface{} { return c.systemVariableContainer.version },
		SetValue:         setVersion,
	}

	definitions[VersionComment] = &definition{
		Name:             VersionComment,
		Kind:             SystemKind,
		AllowedSetScopes: Scope(0),
		SQLType:          schema.SQLVarchar,
		GetValue:         func(c *Container) interface{} { return c.systemVariableContainer.versionComment },
		SetValue:         setVersionComment,
	}

	definitions[WaitTimeoutSecs] = &definition{
		Name:             WaitTimeoutSecs,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope | SessionScope,
		SQLType:          schema.SQLInt,
		GetValue:         func(c *Container) interface{} { return c.systemVariableContainer.waitTimeoutSecs },
		SetValue:         setWaitTimeoutSecs,
	}

	definitions[AnonymizeMetrics] = &definition{
		Name:             AnonymizeMetrics,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope,
		SQLType:          schema.SQLBoolean,
		GetValue:         func(c *Container) interface{} { return c.systemVariableContainer.anonymizeMetrics },
		SetValue:         setAnonymizeMetrics,
	}

	definitions[EnableTableAlterations] = &definition{
		Name:             EnableTableAlterations,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope,
		SQLType:          schema.SQLBoolean,
		GetValue:         func(c *Container) interface{} { return c.systemVariableContainer.enableTableAlterations },
		SetValue:         setEnableTableAlterations,
	}

	definitions[FullPushdownExecMode] = &definition{
		Name:             FullPushdownExecMode,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope | SessionScope,
		SQLType:          schema.SQLBoolean,
		GetValue:         func(c *Container) interface{} { return c.systemVariableContainer.fullPushdownExecMode },
		SetValue:         setFullPushdownExecMode,
	}

	definitions[LogLevel] = &definition{
		Name:             LogLevel,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope,
		SQLType:          schema.SQLInt,
		GetValue:         func(c *Container) interface{} { return c.systemVariableContainer.logLevel },
		SetValue:         setLogLevel,
	}

	definitions[MaxNestedTableDepth] = &definition{
		Name:             MaxNestedTableDepth,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope,
		SQLType:          schema.SQLInt,
		GetValue:         func(c *Container) interface{} { return c.systemVariableContainer.maxNestedTableDepth },
		SetValue:         setMaxNestedTableDepth,
	}

	definitions[MaxNumColumnsPerTable] = &definition{
		Name:             MaxNumColumnsPerTable,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope,
		SQLType:          schema.SQLInt,
		GetValue:         func(c *Container) interface{} { return c.systemVariableContainer.maxNumColumnsPerTable },
		SetValue:         setMaxNumColumnsPerTable,
	}

	definitions[MetricsBackend] = &definition{
		Name:             MetricsBackend,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope,
		SQLType:          schema.SQLVarchar,
		GetValue:         func(c *Container) interface{} { return c.systemVariableContainer.metricsBackend },
		SetValue:         setMetricsBackend,
	}

	definitions[MongoDBMaxServerSize] = &definition{
		Name:             MongoDBMaxServerSize,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope | SessionScope,
		SQLType:          schema.SQLUint,
		GetValue:         func(c *Container) interface{} { return c.systemVariableContainer.mongoDBMaxServerSize },
		SetValue:         setMongoDBMaxServerSize,
	}

	definitions[MongoDBMaxConnectionSize] = &definition{
		Name:             MongoDBMaxConnectionSize,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope | SessionScope,
		SQLType:          schema.SQLUint,
		GetValue:         func(c *Container) interface{} { return c.systemVariableContainer.mongoDBMaxConnectionSize },
		SetValue:         setMongoDBMaxConnectionSize,
	}

	definitions[MongoDBMaxStageSize] = &definition{
		Name:             MongoDBMaxStageSize,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope | SessionScope,
		SQLType:          schema.SQLUint,
		GetValue:         func(c *Container) interface{} { return c.systemVariableContainer.mongoDBMaxStageSize },
		SetValue:         setMongoDBMaxStageSize,
	}

	definitions[MongoDBMaxVarcharLength] = &definition{
		Name:             MongoDBMaxVarcharLength,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope | SessionScope,
		SQLType:          schema.SQLUint,
		GetValue:         func(c *Container) interface{} { return c.systemVariableContainer.mongoDBMaxVarcharLength },
		SetValue:         setMongoDBMaxVarcharLength,
	}

	definitions[MongoDBGitVersion] = &definition{
		Name:             MongoDBGitVersion,
		Kind:             SystemKind,
		AllowedSetScopes: Scope(0),
		SQLType:          schema.SQLVarchar,
		GetValue:         func(c *Container) interface{} { return c.systemVariableContainer.mongoDBGitVersion },
		SetValue:         setMongoDBGitVersion,
	}

	definitions[MongoDBTopology] = &definition{
		Name:             MongoDBTopology,
		Kind:             SystemKind,
		AllowedSetScopes: Scope(0),
		SQLType:          schema.SQLVarchar,
		GetValue:         func(c *Container) interface{} { return c.systemVariableContainer.mongoDBTopology },
		SetValue:         setMongoDBTopology,
	}

	definitions[MongoDBVersion] = &definition{
		Name:             MongoDBVersion,
		Kind:             SystemKind,
		AllowedSetScopes: Scope(0),
		SQLType:          schema.SQLVarchar,
		GetValue:         func(c *Container) interface{} { return c.systemVariableContainer.mongoDBVersion },
		SetValue:         setMongoDBVersion,
	}

	definitions[MongoDBVersionCompatibility] = &definition{
		Name:             MongoDBVersionCompatibility,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope | SessionScope,
		SQLType:          schema.SQLVarchar,
		GetValue:         func(c *Container) interface{} { return c.systemVariableContainer.mongoDBVersionCompatibility },
		SetValue:         setMongoDBVersionCompatibility,
	}

	definitions[MongosqldVersion] = &definition{
		Name:             MongosqldVersion,
		Kind:             SystemKind,
		AllowedSetScopes: Scope(0),
		SQLType:          schema.SQLVarchar,
		GetValue:         func(c *Container) interface{} { return c.systemVariableContainer.mongosqldVersion },
		SetValue:         setMongosqldVersion,
	}

	definitions[OptimizeCrossJoins] = &definition{
		Name:             OptimizeCrossJoins,
		Kind:             SystemKind,
		AllowedSetScopes: SessionScope,
		SQLType:          schema.SQLBoolean,
		GetValue:         func(c *Container) interface{} { return c.systemVariableContainer.optimizeCrossJoins },
		SetValue:         setOptimizeCrossJoins,
	}

	definitions[OptimizeEvaluations] = &definition{
		Name:             OptimizeEvaluations,
		Kind:             SystemKind,
		AllowedSetScopes: SessionScope,
		SQLType:          schema.SQLBoolean,
		GetValue:         func(c *Container) interface{} { return c.systemVariableContainer.optimizeEvaluations },
		SetValue:         setOptimizeEvaluations,
	}

	definitions[OptimizeFiltering] = &definition{
		Name:             OptimizeFiltering,
		Kind:             SystemKind,
		AllowedSetScopes: SessionScope,
		SQLType:          schema.SQLBoolean,
		GetValue:         func(c *Container) interface{} { return c.systemVariableContainer.optimizeFiltering },
		SetValue:         setOptimizeFiltering,
	}

	definitions[OptimizeInnerJoins] = &definition{
		Name:             OptimizeInnerJoins,
		Kind:             SystemKind,
		AllowedSetScopes: SessionScope,
		SQLType:          schema.SQLBoolean,
		GetValue:         func(c *Container) interface{} { return c.systemVariableContainer.optimizeInnerJoins },
		SetValue:         setOptimizeInnerJoins,
	}

	definitions[OptimizeSelfJoins] = &definition{
		Name:             OptimizeSelfJoins,
		Kind:             SystemKind,
		AllowedSetScopes: SessionScope,
		SQLType:          schema.SQLBoolean,
		GetValue:         func(c *Container) interface{} { return c.systemVariableContainer.optimizeSelfJoins },
		SetValue:         setOptimizeSelfJoins,
	}

	definitions[OptimizeViewSampling] = &definition{
		Name:             OptimizeViewSampling,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope,
		SQLType:          schema.SQLBoolean,
		GetValue:         func(c *Container) interface{} { return c.systemVariableContainer.optimizeViewSampling },
		SetValue:         setOptimizeViewSampling,
	}

	definitions[PolymorphicTypeConversionMode] = &definition{
		Name:             PolymorphicTypeConversionMode,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope | SessionScope,
		SQLType:          schema.SQLVarchar,
		GetValue:         func(c *Container) interface{} { return c.systemVariableContainer.polymorphicTypeConversionMode },
		SetValue:         setPolymorphicTypeConversionMode,
	}

	definitions[Pushdown] = &definition{
		Name:             Pushdown,
		Kind:             SystemKind,
		AllowedSetScopes: SessionScope,
		SQLType:          schema.SQLBoolean,
		GetValue:         func(c *Container) interface{} { return c.systemVariableContainer.pushdown },
		SetValue:         setPushdown,
	}

	definitions[RewriteDistinctAsGroup] = &definition{
		Name:             RewriteDistinctAsGroup,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope | SessionScope,
		SQLType:          schema.SQLBoolean,
		GetValue:         func(c *Container) interface{} { return c.systemVariableContainer.rewriteDistinctAsGroup },
		SetValue:         setRewriteDistinctAsGroup,
	}

	definitions[SampleRefreshIntervalSecs] = &definition{
		Name:             SampleRefreshIntervalSecs,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope,
		SQLType:          schema.SQLInt,
		GetValue:         func(c *Container) interface{} { return c.systemVariableContainer.sampleRefreshIntervalSecs },
		SetValue:         setSampleRefreshIntervalSecs,
	}

	definitions[SampleSize] = &definition{
		Name:             SampleSize,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope,
		SQLType:          schema.SQLInt,
		GetValue:         func(c *Container) interface{} { return c.systemVariableContainer.sampleSize },
		SetValue:         setSampleSize,
	}

	definitions[SchemaMappingMode] = &definition{
		Name:             SchemaMappingMode,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope,
		SQLType:          schema.SQLVarchar,
		GetValue:         func(c *Container) interface{} { return c.systemVariableContainer.schemaMappingMode },
		SetValue:         setSchemaMappingMode,
	}

	definitions[TypeConversionMode] = &definition{
		Name:             TypeConversionMode,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope | SessionScope,
		SQLType:          schema.SQLVarchar,
		GetValue:         func(c *Container) interface{} { return c.systemVariableContainer.typeConversionMode },
		SetValue:         setTypeConversionMode,
	}
}

func setAutocommit(c *Container, v interface{}) error {
	val, ok := convertBool(v)
	if !ok {
		return wrongTypeError(Autocommit, v)
	}

	c.systemVariableContainer.autocommit = val
	return nil
}

func setInteractiveTimeoutSecs(c *Container, v interface{}) error {
	val, ok := convertInt64(v)
	if !ok {
		return wrongTypeError(InteractiveTimeoutSecs, v)
	}

	if val < 1 {
		return mysqlerrors.Defaultf(mysqlerrors.ErWrongValueForVar, InteractiveTimeoutSecs, val)
	}

	c.systemVariableContainer.interactiveTimeoutSecs = val
	return nil
}

func setMaxAllowedPacket(c *Container, v interface{}) error {
	val, ok := convertInt64(v)
	if !ok {
		return wrongTypeError(MaxAllowedPacket, v)
	}

	if val < 1024 {
		return mysqlerrors.Defaultf(mysqlerrors.ErWrongValueForVar, MaxAllowedPacket, val)
	}

	if val > 1073741824 {
		return mysqlerrors.Defaultf(mysqlerrors.ErWrongValueForVar, MaxAllowedPacket, val)
	}

	c.systemVariableContainer.maxAllowedPacket = val
	return nil
}

func setMaxConnections(c *Container, v interface{}) error {
	val, ok := convertInt64(v)
	if !ok {
		return wrongTypeError(MaxConnections, v)
	}

	if val < 0 {
		return mysqlerrors.Defaultf(mysqlerrors.ErWrongValueForVar, MaxConnections, val)
	}

	c.systemVariableContainer.maxConnections = val
	return nil
}

func setMaxTimeMS(c *Container, v interface{}) error {
	val, ok := convertInt64(v)
	if !ok {
		return wrongTypeError(MaxTimeMS, v)
	}

	if val < 0 {
		return mysqlerrors.Defaultf(mysqlerrors.ErWrongValueForVar, MaxTimeMS, val)
	}

	c.systemVariableContainer.maxTimeMS = val
	return nil
}

func setSocket(c *Container, v interface{}) error {
	val, ok := convertString(v)
	if !ok {
		return wrongTypeError(Socket, v)
	}

	c.systemVariableContainer.socket = val
	return nil
}

func setSQLAutoIsNull(c *Container, v interface{}) error {
	val, ok := convertBool(v)
	if !ok {
		return wrongTypeError(SQLAutoIsNull, v)
	}

	c.systemVariableContainer.sqlAutoIsNull = val
	return nil
}

func setSQLSelectLimit(c *Container, v interface{}) error {
	val, ok := convertUint64(v)
	if !ok {
		return wrongTypeError(SQLSelectLimit, v)
	}

	c.systemVariableContainer.sqlSelectLimit = val
	return nil
}

func setVersion(c *Container, v interface{}) error {
	val, ok := convertString(v)
	if !ok {
		return wrongTypeError(Version, v)
	}

	c.systemVariableContainer.version = val
	return nil
}

func setVersionComment(c *Container, v interface{}) error {
	val, ok := convertString(v)
	if !ok {
		return wrongTypeError(VersionComment, v)
	}

	c.systemVariableContainer.versionComment = val
	return nil
}

func setAnonymizeMetrics(c *Container, v interface{}) error {
	val, ok := convertBool(v)
	if !ok {
		return wrongTypeError(AnonymizeMetrics, v)
	}

	c.systemVariableContainer.anonymizeMetrics = val
	return nil
}

func setEnableTableAlterations(c *Container, v interface{}) error {
	val, ok := convertBool(v)
	if !ok {
		return wrongTypeError(EnableTableAlterations, v)
	}

	c.systemVariableContainer.enableTableAlterations = val
	return nil
}

func setFullPushdownExecMode(c *Container, v interface{}) error {
	val, ok := convertBool(v)
	if !ok {
		return wrongTypeError(FullPushdownExecMode, v)
	}

	c.systemVariableContainer.fullPushdownExecMode = val
	return nil
}

func setMaxNestedTableDepth(c *Container, v interface{}) error {
	val, ok := convertInt64(v)
	if !ok {
		return wrongTypeError(MaxNestedTableDepth, v)
	}

	if val < 0 {
		return mysqlerrors.Defaultf(mysqlerrors.ErWrongValueForVar, MaxNestedTableDepth, val)
	}

	c.systemVariableContainer.maxNestedTableDepth = val
	return nil
}

func setMaxNumColumnsPerTable(c *Container, v interface{}) error {
	val, ok := convertInt64(v)
	if !ok {
		return wrongTypeError(MaxNumColumnsPerTable, v)
	}

	if val < 1 {
		return mysqlerrors.Defaultf(mysqlerrors.ErWrongValueForVar, MaxNumColumnsPerTable, val)
	}

	c.systemVariableContainer.maxNumColumnsPerTable = val
	return nil
}

func setMetricsBackend(c *Container, v interface{}) error {
	val, ok := convertString(v)
	if !ok {
		return wrongTypeError(MetricsBackend, v)
	}

	switch val {
	case NoMetricsBackend:
		// valid
	case LogMetricsBackend:
		// valid
	case StitchMetricsBackend:
		// valid
	default:
		return mysqlerrors.Defaultf(mysqlerrors.ErWrongValueForVar, MetricsBackend, val)
	}

	c.systemVariableContainer.metricsBackend = val
	return nil
}

func setMongoDBMaxServerSize(c *Container, v interface{}) error {
	val, ok := convertUint64(v)
	if !ok {
		return wrongTypeError(MongoDBMaxServerSize, v)
	}

	c.systemVariableContainer.mongoDBMaxServerSize = val
	return nil
}

func setMongoDBMaxConnectionSize(c *Container, v interface{}) error {
	val, ok := convertUint64(v)
	if !ok {
		return wrongTypeError(MongoDBMaxConnectionSize, v)
	}

	c.systemVariableContainer.mongoDBMaxConnectionSize = val
	return nil
}

func setMongoDBMaxStageSize(c *Container, v interface{}) error {
	val, ok := convertUint64(v)
	if !ok {
		return wrongTypeError(MongoDBMaxStageSize, v)
	}

	c.systemVariableContainer.mongoDBMaxStageSize = val
	return nil
}

func setMongoDBMaxVarcharLength(c *Container, v interface{}) error {
	val, ok := convertUint16(v)
	if !ok {
		return wrongTypeError(MongoDBMaxVarcharLength, v)
	}

	if val < 0 {
		return mysqlerrors.Defaultf(mysqlerrors.ErWrongValueForVar, MongoDBMaxVarcharLength, val)
	}

	if val > math.MaxUint16 {
		return mysqlerrors.Defaultf(mysqlerrors.ErWrongValueForVar, MongoDBMaxVarcharLength, val)
	}

	c.systemVariableContainer.mongoDBMaxVarcharLength = val
	return nil
}

func setMongoDBGitVersion(c *Container, v interface{}) error {
	val, ok := convertString(v)
	if !ok {
		return wrongTypeError(MongoDBGitVersion, v)
	}

	c.systemVariableContainer.mongoDBGitVersion = val
	return nil
}

func setMongoDBTopology(c *Container, v interface{}) error {
	val, ok := convertString(v)
	if !ok {
		return wrongTypeError(MongoDBTopology, v)
	}

	c.systemVariableContainer.mongoDBTopology = val
	return nil
}

func setMongoDBVersion(c *Container, v interface{}) error {
	val, ok := convertString(v)
	if !ok {
		return wrongTypeError(MongoDBVersion, v)
	}

	c.systemVariableContainer.mongoDBVersion = val
	return nil
}

func setMongoDBVersionCompatibility(c *Container, v interface{}) error {
	val, ok := convertString(v)
	if !ok {
		return wrongTypeError(MongoDBVersionCompatibility, v)
	}

	c.systemVariableContainer.mongoDBVersionCompatibility = val
	return nil
}

func setMongosqldVersion(c *Container, v interface{}) error {
	val, ok := convertString(v)
	if !ok {
		return wrongTypeError(MongosqldVersion, v)
	}

	c.systemVariableContainer.mongosqldVersion = val
	return nil
}

func setOptimizeCrossJoins(c *Container, v interface{}) error {
	val, ok := convertBool(v)
	if !ok {
		return wrongTypeError(OptimizeCrossJoins, v)
	}

	c.systemVariableContainer.optimizeCrossJoins = val
	return nil
}

func setOptimizeEvaluations(c *Container, v interface{}) error {
	val, ok := convertBool(v)
	if !ok {
		return wrongTypeError(OptimizeEvaluations, v)
	}

	c.systemVariableContainer.optimizeEvaluations = val
	return nil
}

func setOptimizeFiltering(c *Container, v interface{}) error {
	val, ok := convertBool(v)
	if !ok {
		return wrongTypeError(OptimizeFiltering, v)
	}

	c.systemVariableContainer.optimizeFiltering = val
	return nil
}

func setOptimizeInnerJoins(c *Container, v interface{}) error {
	val, ok := convertBool(v)
	if !ok {
		return wrongTypeError(OptimizeInnerJoins, v)
	}

	c.systemVariableContainer.optimizeInnerJoins = val
	return nil
}

func setOptimizeSelfJoins(c *Container, v interface{}) error {
	val, ok := convertBool(v)
	if !ok {
		return wrongTypeError(OptimizeSelfJoins, v)
	}

	c.systemVariableContainer.optimizeSelfJoins = val
	return nil
}

func setOptimizeViewSampling(c *Container, v interface{}) error {
	val, ok := convertBool(v)
	if !ok {
		return wrongTypeError(OptimizeViewSampling, v)
	}

	c.systemVariableContainer.optimizeViewSampling = val
	return nil
}

func setPolymorphicTypeConversionMode(c *Container, v interface{}) error {
	val, ok := convertString(v)
	if !ok {
		return wrongTypeError(PolymorphicTypeConversionMode, v)
	}

	switch val {
	case SafePolymorphicTypeConversionMode:
		// valid
	case FastPolymorphicTypeConversionMode:
		// valid
	case OffPolymorphicTypeConversionMode:
		// valid
	default:
		return mysqlerrors.Defaultf(mysqlerrors.ErWrongValueForVar, PolymorphicTypeConversionMode, val)
	}

	c.systemVariableContainer.polymorphicTypeConversionMode = val
	return nil
}

func setPushdown(c *Container, v interface{}) error {
	val, ok := convertBool(v)
	if !ok {
		return wrongTypeError(Pushdown, v)
	}

	c.systemVariableContainer.pushdown = val
	return nil
}

func setRewriteDistinctAsGroup(c *Container, v interface{}) error {
	val, ok := convertBool(v)
	if !ok {
		return wrongTypeError(RewriteDistinctAsGroup, v)
	}

	c.systemVariableContainer.rewriteDistinctAsGroup = val
	return nil
}

func setSampleRefreshIntervalSecs(c *Container, v interface{}) error {
	val, ok := convertInt64(v)
	if !ok {
		return wrongTypeError(SampleRefreshIntervalSecs, v)
	}

	if val < 0 {
		return mysqlerrors.Defaultf(mysqlerrors.ErWrongValueForVar, SampleRefreshIntervalSecs, val)
	}

	c.systemVariableContainer.sampleRefreshIntervalSecs = val
	return nil
}

func setSampleSize(c *Container, v interface{}) error {
	val, ok := convertInt64(v)
	if !ok {
		return wrongTypeError(SampleSize, v)
	}

	if val < 0 {
		return mysqlerrors.Defaultf(mysqlerrors.ErWrongValueForVar, SampleSize, val)
	}

	c.systemVariableContainer.sampleSize = val
	return nil
}

func setSchemaMappingMode(c *Container, v interface{}) error {
	val, ok := convertString(v)
	if !ok {
		return wrongTypeError(SchemaMappingMode, v)
	}

	switch val {
	case MajoritySchemaMappingMode:
		// valid
	case LatticeSchemaMappingMode:
		// valid
	default:
		return mysqlerrors.Defaultf(mysqlerrors.ErWrongValueForVar, SchemaMappingMode, val)
	}

	c.systemVariableContainer.schemaMappingMode = val
	return nil
}

func setTypeConversionMode(c *Container, v interface{}) error {
	val, ok := convertString(v)
	if !ok {
		return wrongTypeError(TypeConversionMode, v)
	}

	switch val {
	case MongoSQLTypeConversionMode:
		// valid
	case MySQLTypeConversionMode:
		// valid
	default:
		return mysqlerrors.Defaultf(mysqlerrors.ErWrongValueForVar, TypeConversionMode, val)
	}

	c.systemVariableContainer.typeConversionMode = val
	return nil
}
