// Code generated by 'go generate'. DO NOT EDIT.

package variable

import (
	"fmt"
	"math"

	"github.com/10gen/sqlproxy/collation"
	"github.com/10gen/sqlproxy/evaluator/types"
	"github.com/10gen/sqlproxy/evaluator/values"
	"github.com/10gen/sqlproxy/internal/config"
	"github.com/10gen/sqlproxy/internal/mysqlerrors"
)

// These variables hold system variable names.
const (
	Autocommit                      Name = "autocommit"
	CharacterSetClient              Name = "character_set_client"
	CharacterSetConnection          Name = "character_set_connection"
	CharacterSetDatabase            Name = "character_set_database"
	CharacterSetResults             Name = "character_set_results"
	CollationConnection             Name = "collation_connection"
	CollationDatabase               Name = "collation_database"
	CollationServer                 Name = "collation_server"
	GroupConcatMaxLen               Name = "group_concat_max_len"
	InteractiveTimeoutSecs          Name = "interactive_timeout"
	MaxAllowedPacket                Name = "max_allowed_packet"
	MaxConnections                  Name = "max_connections"
	MaxTimeMS                       Name = "max_execution_time"
	Socket                          Name = "socket"
	SQLAutoIsNull                   Name = "sql_auto_is_null"
	SQLSelectLimit                  Name = "sql_select_limit"
	Version                         Name = "version"
	VersionComment                  Name = "version_comment"
	WaitTimeoutSecs                 Name = "wait_timeout"
	AnonymizeMetrics                Name = "anonymize_metrics"
	EnableTableAlterations          Name = "enable_table_alterations"
	FullPushdownExecMode            Name = "full_pushdown_exec_mode"
	LogLevel                        Name = "log_level"
	MaxNestedTableDepth             Name = "max_nested_table_depth"
	MaxNumColumnsPerTable           Name = "max_num_columns_per_table"
	MetricsBackend                  Name = "metrics_backend"
	MongoDBMaxServerSize            Name = "mongodb_max_server_size"
	MongoDBMaxConnectionSize        Name = "mongodb_max_connection_size"
	MongoDBMaxStageSize             Name = "mongodb_max_stage_size"
	MongoDBMaxVarcharLength         Name = "mongodb_max_varchar_length"
	MongoDBGitVersion               Name = "mongodb_git_version"
	MongoDBTopology                 Name = "mongodb_topology"
	MongoDBVersion                  Name = "mongodb_version"
	MongoDBVersionCompatibility     Name = "mongodb_version_compatibility"
	MongosqldVersion                Name = "mongosqld_version"
	OptimizeCrossJoins              Name = "optimize_cross_joins"
	OptimizeEvaluations             Name = "optimize_evaluations"
	OptimizeFiltering               Name = "optimize_filtering"
	OptimizeInnerJoins              Name = "optimize_inner_joins"
	OptimizeSelfJoins               Name = "optimize_self_joins"
	OptimizeViewSampling            Name = "optimize_view_sampling"
	PolymorphicTypeConversionMode   Name = "polymorphic_type_conversion_mode"
	Pushdown                        Name = "pushdown"
	RewriteDistinctAsGroup          Name = "rewrite_distinct_as_group"
	SampleRefreshIntervalSecs       Name = "sample_refresh_interval_secs"
	SampleSize                      Name = "sample_size"
	SchemaMappingMode               Name = "schema_mapping_mode"
	TypeConversionMode              Name = "type_conversion_mode"
	ReconcileArithmeticAggFunctions Name = "reconcile_arithmetic_agg_functions"
)

// These are constants representing variants of enum-style variables.
const (
	// MetricsBackend variants
	NoMetricsBackend     = "off"
	LogMetricsBackend    = "log"
	StitchMetricsBackend = "stitch"

	// PolymorphicTypeConversionMode variants
	SafePolymorphicTypeConversionMode = "safe"
	FastPolymorphicTypeConversionMode = "fast"
	OffPolymorphicTypeConversionMode  = "off"

	// SchemaMappingMode variants
	MajoritySchemaMappingMode = "majority"
	LatticeSchemaMappingMode  = "lattice"

	// TypeConversionMode variants
	MongoSQLTypeConversionMode = "mongosql"
	MySQLTypeConversionMode    = "mysql"
)

// These are constants representing variables' default values.
var (
	defaultAutocommit                      values.SQLBool    = values.NewSQLBool(values.VariableSQLValueKind, true)
	defaultCharacterSetClient              values.SQLVarchar = values.NewSQLVarchar(values.VariableSQLValueKind, string(collation.DefaultCharset.Name))
	defaultCharacterSetConnection          values.SQLVarchar = values.NewSQLVarchar(values.VariableSQLValueKind, string(collation.DefaultCharset.Name))
	defaultCharacterSetDatabase            values.SQLVarchar = values.NewSQLVarchar(values.VariableSQLValueKind, string(collation.DefaultCharset.Name))
	defaultCharacterSetResults             values.SQLVarchar = values.NewSQLVarchar(values.VariableSQLValueKind, string(collation.DefaultCharset.Name))
	defaultCollationConnection             values.SQLVarchar = values.NewSQLVarchar(values.VariableSQLValueKind, string(collation.Default.Name))
	defaultCollationDatabase               values.SQLVarchar = values.NewSQLVarchar(values.VariableSQLValueKind, string(collation.Default.Name))
	defaultCollationServer                 values.SQLVarchar = values.NewSQLVarchar(values.VariableSQLValueKind, string(collation.Default.Name))
	defaultGroupConcatMaxLen               values.SQLInt64   = values.NewSQLInt64(values.VariableSQLValueKind, 1024)
	defaultInteractiveTimeoutSecs          values.SQLInt64   = values.NewSQLInt64(values.VariableSQLValueKind, 28800)
	defaultMaxAllowedPacket                values.SQLInt64   = values.NewSQLInt64(values.VariableSQLValueKind, 1073741824)
	defaultMaxConnections                  values.SQLInt64   = values.NewSQLInt64(values.VariableSQLValueKind, 0)
	defaultMaxTimeMS                       values.SQLInt64   = values.NewSQLInt64(values.VariableSQLValueKind, 0)
	defaultSocket                          values.SQLVarchar = values.NewSQLVarchar(values.VariableSQLValueKind, "")
	defaultSQLAutoIsNull                   values.SQLBool    = values.NewSQLBool(values.VariableSQLValueKind, false)
	defaultSQLSelectLimit                  values.SQLUint64  = values.NewSQLUint64(values.VariableSQLValueKind, math.MaxUint64)
	defaultVersion                         values.SQLVarchar = values.NewSQLVarchar(values.VariableSQLValueKind, "5.7.12")
	defaultVersionComment                  values.SQLVarchar = values.NewSQLVarchar(values.VariableSQLValueKind, fmt.Sprintf("mongosqld "+config.VersionStr))
	defaultWaitTimeoutSecs                 values.SQLInt64   = values.NewSQLInt64(values.VariableSQLValueKind, 28800)
	defaultAnonymizeMetrics                values.SQLBool    = values.NewSQLBool(values.VariableSQLValueKind, true)
	defaultEnableTableAlterations          values.SQLBool    = values.NewSQLBool(values.VariableSQLValueKind, false)
	defaultFullPushdownExecMode            values.SQLBool    = values.NewSQLBool(values.VariableSQLValueKind, false)
	defaultLogLevel                        values.SQLInt64   = values.NewSQLInt64(values.VariableSQLValueKind, 0)
	defaultMaxNestedTableDepth             values.SQLInt64   = values.NewSQLInt64(values.VariableSQLValueKind, 50)
	defaultMaxNumColumnsPerTable           values.SQLInt64   = values.NewSQLInt64(values.VariableSQLValueKind, 2000)
	defaultMetricsBackend                  values.SQLVarchar = values.NewSQLVarchar(values.VariableSQLValueKind, NoMetricsBackend)
	defaultMongoDBMaxServerSize            values.SQLUint64  = values.NewSQLUint64(values.VariableSQLValueKind, 0)
	defaultMongoDBMaxConnectionSize        values.SQLUint64  = values.NewSQLUint64(values.VariableSQLValueKind, 0)
	defaultMongoDBMaxStageSize             values.SQLUint64  = values.NewSQLUint64(values.VariableSQLValueKind, 0)
	defaultMongoDBMaxVarcharLength         values.SQLUint64  = values.NewSQLUint64(values.VariableSQLValueKind, math.MaxUint16)
	defaultMongoDBGitVersion               values.SQLVarchar = values.NewSQLVarchar(values.VariableSQLValueKind, "")
	defaultMongoDBTopology                 values.SQLVarchar = values.NewSQLVarchar(values.VariableSQLValueKind, "")
	defaultMongoDBVersion                  values.SQLVarchar = values.NewSQLVarchar(values.VariableSQLValueKind, "")
	defaultMongoDBVersionCompatibility     values.SQLVarchar = values.NewSQLVarchar(values.VariableSQLValueKind, "")
	defaultMongosqldVersion                values.SQLVarchar = values.NewSQLVarchar(values.VariableSQLValueKind, config.VersionStr)
	defaultOptimizeCrossJoins              values.SQLBool    = values.NewSQLBool(values.VariableSQLValueKind, true)
	defaultOptimizeEvaluations             values.SQLBool    = values.NewSQLBool(values.VariableSQLValueKind, true)
	defaultOptimizeFiltering               values.SQLBool    = values.NewSQLBool(values.VariableSQLValueKind, true)
	defaultOptimizeInnerJoins              values.SQLBool    = values.NewSQLBool(values.VariableSQLValueKind, true)
	defaultOptimizeSelfJoins               values.SQLBool    = values.NewSQLBool(values.VariableSQLValueKind, true)
	defaultOptimizeViewSampling            values.SQLBool    = values.NewSQLBool(values.VariableSQLValueKind, true)
	defaultPolymorphicTypeConversionMode   values.SQLVarchar = values.NewSQLVarchar(values.VariableSQLValueKind, OffPolymorphicTypeConversionMode)
	defaultPushdown                        values.SQLBool    = values.NewSQLBool(values.VariableSQLValueKind, true)
	defaultRewriteDistinctAsGroup          values.SQLBool    = values.NewSQLBool(values.VariableSQLValueKind, false)
	defaultSampleRefreshIntervalSecs       values.SQLInt64   = values.NewSQLInt64(values.VariableSQLValueKind, 0)
	defaultSampleSize                      values.SQLInt64   = values.NewSQLInt64(values.VariableSQLValueKind, 1000)
	defaultSchemaMappingMode               values.SQLVarchar = values.NewSQLVarchar(values.VariableSQLValueKind, LatticeSchemaMappingMode)
	defaultTypeConversionMode              values.SQLVarchar = values.NewSQLVarchar(values.VariableSQLValueKind, MongoSQLTypeConversionMode)
	defaultReconcileArithmeticAggFunctions values.SQLBool    = values.NewSQLBool(values.VariableSQLValueKind, false)
)

type systemVariableContainer struct {
	autocommit                      values.SQLBool
	characterSetClient              values.SQLVarchar
	characterSetConnection          values.SQLVarchar
	characterSetDatabase            values.SQLVarchar
	characterSetResults             values.SQLVarchar
	collationConnection             values.SQLVarchar
	collationDatabase               values.SQLVarchar
	collationServer                 values.SQLVarchar
	groupConcatMaxLen               values.SQLInt64
	interactiveTimeoutSecs          values.SQLInt64
	maxAllowedPacket                values.SQLInt64
	maxConnections                  values.SQLInt64
	maxTimeMS                       values.SQLInt64
	socket                          values.SQLVarchar
	sqlAutoIsNull                   values.SQLBool
	sqlSelectLimit                  values.SQLUint64
	version                         values.SQLVarchar
	versionComment                  values.SQLVarchar
	waitTimeoutSecs                 values.SQLInt64
	anonymizeMetrics                values.SQLBool
	enableTableAlterations          values.SQLBool
	fullPushdownExecMode            values.SQLBool
	logLevel                        values.SQLInt64
	maxNestedTableDepth             values.SQLInt64
	maxNumColumnsPerTable           values.SQLInt64
	metricsBackend                  values.SQLVarchar
	mongoDBMaxServerSize            values.SQLUint64
	mongoDBMaxConnectionSize        values.SQLUint64
	mongoDBMaxStageSize             values.SQLUint64
	mongoDBMaxVarcharLength         values.SQLUint64
	mongoDBGitVersion               values.SQLVarchar
	mongoDBTopology                 values.SQLVarchar
	mongoDBVersion                  values.SQLVarchar
	mongoDBVersionCompatibility     values.SQLVarchar
	mongosqldVersion                values.SQLVarchar
	optimizeCrossJoins              values.SQLBool
	optimizeEvaluations             values.SQLBool
	optimizeFiltering               values.SQLBool
	optimizeInnerJoins              values.SQLBool
	optimizeSelfJoins               values.SQLBool
	optimizeViewSampling            values.SQLBool
	polymorphicTypeConversionMode   values.SQLVarchar
	pushdown                        values.SQLBool
	rewriteDistinctAsGroup          values.SQLBool
	sampleRefreshIntervalSecs       values.SQLInt64
	sampleSize                      values.SQLInt64
	schemaMappingMode               values.SQLVarchar
	typeConversionMode              values.SQLVarchar
	reconcileArithmeticAggFunctions values.SQLBool
}

func (svc *systemVariableContainer) setDefaults() {
	svc.autocommit = defaultAutocommit
	svc.characterSetClient = defaultCharacterSetClient
	svc.characterSetConnection = defaultCharacterSetConnection
	svc.characterSetDatabase = defaultCharacterSetDatabase
	svc.characterSetResults = defaultCharacterSetResults
	svc.collationConnection = defaultCollationConnection
	svc.collationDatabase = defaultCollationDatabase
	svc.collationServer = defaultCollationServer
	svc.groupConcatMaxLen = defaultGroupConcatMaxLen
	svc.interactiveTimeoutSecs = defaultInteractiveTimeoutSecs
	svc.maxAllowedPacket = defaultMaxAllowedPacket
	svc.maxConnections = defaultMaxConnections
	svc.maxTimeMS = defaultMaxTimeMS
	svc.socket = defaultSocket
	svc.sqlAutoIsNull = defaultSQLAutoIsNull
	svc.sqlSelectLimit = defaultSQLSelectLimit
	svc.version = defaultVersion
	svc.versionComment = defaultVersionComment
	svc.waitTimeoutSecs = defaultWaitTimeoutSecs
	svc.anonymizeMetrics = defaultAnonymizeMetrics
	svc.enableTableAlterations = defaultEnableTableAlterations
	svc.fullPushdownExecMode = defaultFullPushdownExecMode
	svc.logLevel = defaultLogLevel
	svc.maxNestedTableDepth = defaultMaxNestedTableDepth
	svc.maxNumColumnsPerTable = defaultMaxNumColumnsPerTable
	svc.metricsBackend = defaultMetricsBackend
	svc.mongoDBMaxServerSize = defaultMongoDBMaxServerSize
	svc.mongoDBMaxConnectionSize = defaultMongoDBMaxConnectionSize
	svc.mongoDBMaxStageSize = defaultMongoDBMaxStageSize
	svc.mongoDBMaxVarcharLength = defaultMongoDBMaxVarcharLength
	svc.mongoDBGitVersion = defaultMongoDBGitVersion
	svc.mongoDBTopology = defaultMongoDBTopology
	svc.mongoDBVersion = defaultMongoDBVersion
	svc.mongoDBVersionCompatibility = defaultMongoDBVersionCompatibility
	svc.mongosqldVersion = defaultMongosqldVersion
	svc.optimizeCrossJoins = defaultOptimizeCrossJoins
	svc.optimizeEvaluations = defaultOptimizeEvaluations
	svc.optimizeFiltering = defaultOptimizeFiltering
	svc.optimizeInnerJoins = defaultOptimizeInnerJoins
	svc.optimizeSelfJoins = defaultOptimizeSelfJoins
	svc.optimizeViewSampling = defaultOptimizeViewSampling
	svc.polymorphicTypeConversionMode = defaultPolymorphicTypeConversionMode
	svc.pushdown = defaultPushdown
	svc.rewriteDistinctAsGroup = defaultRewriteDistinctAsGroup
	svc.sampleRefreshIntervalSecs = defaultSampleRefreshIntervalSecs
	svc.sampleSize = defaultSampleSize
	svc.schemaMappingMode = defaultSchemaMappingMode
	svc.typeConversionMode = defaultTypeConversionMode
	svc.reconcileArithmeticAggFunctions = defaultReconcileArithmeticAggFunctions
}

func (svc *systemVariableContainer) setFromConfig(cfg *config.Config) {
	svc.anonymizeMetrics = values.NewSQLBool(values.VariableSQLValueKind, cfg.SetParameter.AnonymizeMetrics)
	svc.enableTableAlterations = values.NewSQLBool(values.VariableSQLValueKind, cfg.SetParameter.EnableTableAlterations)
	svc.logLevel = values.NewSQLInt64(values.VariableSQLValueKind, cfg.SystemLog.Level())
	svc.maxNestedTableDepth = values.NewSQLInt64(values.VariableSQLValueKind, cfg.Schema.Sample.MaxNestedTableDepth)
	svc.maxNumColumnsPerTable = values.NewSQLInt64(values.VariableSQLValueKind, cfg.Schema.Sample.MaxNumColumnsPerTable)
	svc.metricsBackend = values.NewSQLVarchar(values.VariableSQLValueKind, cfg.SetParameter.MetricsBackend)
	svc.mongoDBMaxServerSize = values.NewSQLUint64(values.VariableSQLValueKind, cfg.Runtime.Memory.MaxPerServer)
	svc.mongoDBMaxConnectionSize = values.NewSQLUint64(values.VariableSQLValueKind, cfg.Runtime.Memory.MaxPerConnection)
	svc.mongoDBMaxStageSize = values.NewSQLUint64(values.VariableSQLValueKind, cfg.Runtime.Memory.MaxPerStage)
	svc.mongoDBMaxVarcharLength = values.NewSQLUint64(values.VariableSQLValueKind, cfg.Schema.MaxVarcharLength)
	svc.mongoDBVersionCompatibility = values.NewSQLVarchar(values.VariableSQLValueKind, cfg.MongoDB.VersionCompatibility)
	svc.optimizeCrossJoins = values.NewSQLBool(values.VariableSQLValueKind, cfg.SetParameter.OptimizeCrossJoins)
	svc.optimizeEvaluations = values.NewSQLBool(values.VariableSQLValueKind, cfg.SetParameter.OptimizeEvaluations)
	svc.optimizeFiltering = values.NewSQLBool(values.VariableSQLValueKind, cfg.SetParameter.OptimizeFiltering)
	svc.optimizeInnerJoins = values.NewSQLBool(values.VariableSQLValueKind, cfg.SetParameter.OptimizeInnerJoins)
	svc.optimizeSelfJoins = values.NewSQLBool(values.VariableSQLValueKind, cfg.SetParameter.OptimizeSelfJoins)
	svc.optimizeViewSampling = values.NewSQLBool(values.VariableSQLValueKind, cfg.SetParameter.OptimizeViewSampling)
	svc.polymorphicTypeConversionMode = values.NewSQLVarchar(values.VariableSQLValueKind, cfg.SetParameter.PolymorphicTypeConversionMode)
	svc.pushdown = values.NewSQLBool(values.VariableSQLValueKind, cfg.SetParameter.Pushdown)
	svc.rewriteDistinctAsGroup = values.NewSQLBool(values.VariableSQLValueKind, cfg.SetParameter.RewriteDistinctAsGroup)
	svc.sampleRefreshIntervalSecs = values.NewSQLInt64(values.VariableSQLValueKind, cfg.Schema.RefreshIntervalSecs)
	svc.sampleSize = values.NewSQLInt64(values.VariableSQLValueKind, cfg.Schema.Sample.Size)
	svc.schemaMappingMode = values.NewSQLVarchar(values.VariableSQLValueKind, cfg.Schema.Sample.SchemaMappingMode)
	svc.typeConversionMode = values.NewSQLVarchar(values.VariableSQLValueKind, cfg.SetParameter.TypeConversionMode)
	svc.reconcileArithmeticAggFunctions = values.NewSQLBool(values.VariableSQLValueKind, cfg.SetParameter.ReconcileArithmeticAggFunctions)
}

func init() {

	definitions[Autocommit] = &definition{
		Name:             Autocommit,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope | SessionScope,
		EvalType:         types.EvalBoolean,
		GetValue:         func(c *Container) values.SQLValue { return c.systemVariableContainer.autocommit },
		SetValue:         setAutocommit,
	}

	definitions[CharacterSetClient] = &definition{
		Name:             CharacterSetClient,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope | SessionScope,
		EvalType:         types.EvalString,
		GetValue:         func(c *Container) values.SQLValue { return c.systemVariableContainer.characterSetClient },
		SetValue:         setCharacterSetClient,
	}

	definitions[CharacterSetConnection] = &definition{
		Name:             CharacterSetConnection,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope | SessionScope,
		EvalType:         types.EvalString,
		GetValue:         func(c *Container) values.SQLValue { return c.systemVariableContainer.characterSetConnection },
		SetValue:         setCharacterSetConnection,
	}

	definitions[CharacterSetDatabase] = &definition{
		Name:             CharacterSetDatabase,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope | SessionScope,
		EvalType:         types.EvalString,
		GetValue:         func(c *Container) values.SQLValue { return c.systemVariableContainer.characterSetDatabase },
		SetValue:         setCharacterSetDatabase,
	}

	definitions[CharacterSetResults] = &definition{
		Name:             CharacterSetResults,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope | SessionScope,
		EvalType:         types.EvalString,
		GetValue:         getCharacterSetResults,
		SetValue:         setCharacterSetResults,
	}

	definitions[CollationConnection] = &definition{
		Name:             CollationConnection,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope | SessionScope,
		EvalType:         types.EvalString,
		GetValue:         func(c *Container) values.SQLValue { return c.systemVariableContainer.collationConnection },
		SetValue:         setCollationConnection,
	}

	definitions[CollationDatabase] = &definition{
		Name:             CollationDatabase,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope | SessionScope,
		EvalType:         types.EvalString,
		GetValue:         func(c *Container) values.SQLValue { return c.systemVariableContainer.collationDatabase },
		SetValue:         setCollationDatabase,
	}

	definitions[CollationServer] = &definition{
		Name:             CollationServer,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope | SessionScope,
		EvalType:         types.EvalString,
		GetValue:         func(c *Container) values.SQLValue { return c.systemVariableContainer.collationServer },
		SetValue:         setCollationServer,
	}

	definitions[GroupConcatMaxLen] = &definition{
		Name:             GroupConcatMaxLen,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope | SessionScope,
		EvalType:         types.EvalInt64,
		GetValue:         func(c *Container) values.SQLValue { return c.systemVariableContainer.groupConcatMaxLen },
		SetValue:         setGroupConcatMaxLen,
	}

	definitions[InteractiveTimeoutSecs] = &definition{
		Name:             InteractiveTimeoutSecs,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope | SessionScope,
		EvalType:         types.EvalInt64,
		GetValue:         func(c *Container) values.SQLValue { return c.systemVariableContainer.interactiveTimeoutSecs },
		SetValue:         setInteractiveTimeoutSecs,
	}

	definitions[MaxAllowedPacket] = &definition{
		Name:             MaxAllowedPacket,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope | SessionScope,
		EvalType:         types.EvalInt64,
		GetValue:         func(c *Container) values.SQLValue { return c.systemVariableContainer.maxAllowedPacket },
		SetValue:         setMaxAllowedPacket,
	}

	definitions[MaxConnections] = &definition{
		Name:             MaxConnections,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope,
		EvalType:         types.EvalInt64,
		GetValue:         func(c *Container) values.SQLValue { return c.systemVariableContainer.maxConnections },
		SetValue:         setMaxConnections,
	}

	definitions[MaxTimeMS] = &definition{
		Name:             MaxTimeMS,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope | SessionScope,
		EvalType:         types.EvalInt64,
		GetValue:         func(c *Container) values.SQLValue { return c.systemVariableContainer.maxTimeMS },
		SetValue:         setMaxTimeMS,
	}

	definitions[Socket] = &definition{
		Name:             Socket,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope,
		EvalType:         types.EvalString,
		GetValue:         func(c *Container) values.SQLValue { return c.systemVariableContainer.socket },
		SetValue:         setSocket,
	}

	definitions[SQLAutoIsNull] = &definition{
		Name:             SQLAutoIsNull,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope | SessionScope,
		EvalType:         types.EvalBoolean,
		GetValue:         func(c *Container) values.SQLValue { return c.systemVariableContainer.sqlAutoIsNull },
		SetValue:         setSQLAutoIsNull,
	}

	definitions[SQLSelectLimit] = &definition{
		Name:             SQLSelectLimit,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope | SessionScope,
		EvalType:         types.EvalUint64,
		GetValue:         func(c *Container) values.SQLValue { return c.systemVariableContainer.sqlSelectLimit },
		SetValue:         setSQLSelectLimit,
	}

	definitions[Version] = &definition{
		Name:             Version,
		Kind:             SystemKind,
		AllowedSetScopes: Scope(0),
		EvalType:         types.EvalString,
		GetValue:         func(c *Container) values.SQLValue { return c.systemVariableContainer.version },
		SetValue:         setVersion,
	}

	definitions[VersionComment] = &definition{
		Name:             VersionComment,
		Kind:             SystemKind,
		AllowedSetScopes: Scope(0),
		EvalType:         types.EvalString,
		GetValue:         func(c *Container) values.SQLValue { return c.systemVariableContainer.versionComment },
		SetValue:         setVersionComment,
	}

	definitions[WaitTimeoutSecs] = &definition{
		Name:             WaitTimeoutSecs,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope | SessionScope,
		EvalType:         types.EvalInt64,
		GetValue:         func(c *Container) values.SQLValue { return c.systemVariableContainer.waitTimeoutSecs },
		SetValue:         setWaitTimeoutSecs,
	}

	definitions[AnonymizeMetrics] = &definition{
		Name:             AnonymizeMetrics,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope,
		EvalType:         types.EvalBoolean,
		GetValue:         func(c *Container) values.SQLValue { return c.systemVariableContainer.anonymizeMetrics },
		SetValue:         setAnonymizeMetrics,
	}

	definitions[EnableTableAlterations] = &definition{
		Name:             EnableTableAlterations,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope,
		EvalType:         types.EvalBoolean,
		GetValue:         func(c *Container) values.SQLValue { return c.systemVariableContainer.enableTableAlterations },
		SetValue:         setEnableTableAlterations,
	}

	definitions[FullPushdownExecMode] = &definition{
		Name:             FullPushdownExecMode,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope | SessionScope,
		EvalType:         types.EvalBoolean,
		GetValue:         func(c *Container) values.SQLValue { return c.systemVariableContainer.fullPushdownExecMode },
		SetValue:         setFullPushdownExecMode,
	}

	definitions[LogLevel] = &definition{
		Name:             LogLevel,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope,
		EvalType:         types.EvalInt64,
		GetValue:         func(c *Container) values.SQLValue { return c.systemVariableContainer.logLevel },
		SetValue:         setLogLevel,
	}

	definitions[MaxNestedTableDepth] = &definition{
		Name:             MaxNestedTableDepth,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope,
		EvalType:         types.EvalInt64,
		GetValue:         func(c *Container) values.SQLValue { return c.systemVariableContainer.maxNestedTableDepth },
		SetValue:         setMaxNestedTableDepth,
	}

	definitions[MaxNumColumnsPerTable] = &definition{
		Name:             MaxNumColumnsPerTable,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope,
		EvalType:         types.EvalInt64,
		GetValue:         func(c *Container) values.SQLValue { return c.systemVariableContainer.maxNumColumnsPerTable },
		SetValue:         setMaxNumColumnsPerTable,
	}

	definitions[MetricsBackend] = &definition{
		Name:             MetricsBackend,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope,
		EvalType:         types.EvalString,
		GetValue:         func(c *Container) values.SQLValue { return c.systemVariableContainer.metricsBackend },
		SetValue:         setMetricsBackend,
	}

	definitions[MongoDBMaxServerSize] = &definition{
		Name:             MongoDBMaxServerSize,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope | SessionScope,
		EvalType:         types.EvalUint64,
		GetValue:         func(c *Container) values.SQLValue { return c.systemVariableContainer.mongoDBMaxServerSize },
		SetValue:         setMongoDBMaxServerSize,
	}

	definitions[MongoDBMaxConnectionSize] = &definition{
		Name:             MongoDBMaxConnectionSize,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope | SessionScope,
		EvalType:         types.EvalUint64,
		GetValue:         func(c *Container) values.SQLValue { return c.systemVariableContainer.mongoDBMaxConnectionSize },
		SetValue:         setMongoDBMaxConnectionSize,
	}

	definitions[MongoDBMaxStageSize] = &definition{
		Name:             MongoDBMaxStageSize,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope | SessionScope,
		EvalType:         types.EvalUint64,
		GetValue:         func(c *Container) values.SQLValue { return c.systemVariableContainer.mongoDBMaxStageSize },
		SetValue:         setMongoDBMaxStageSize,
	}

	definitions[MongoDBMaxVarcharLength] = &definition{
		Name:             MongoDBMaxVarcharLength,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope | SessionScope,
		EvalType:         types.EvalUint64,
		GetValue:         func(c *Container) values.SQLValue { return c.systemVariableContainer.mongoDBMaxVarcharLength },
		SetValue:         setMongoDBMaxVarcharLength,
	}

	definitions[MongoDBGitVersion] = &definition{
		Name:             MongoDBGitVersion,
		Kind:             SystemKind,
		AllowedSetScopes: Scope(0),
		EvalType:         types.EvalString,
		GetValue:         func(c *Container) values.SQLValue { return c.systemVariableContainer.mongoDBGitVersion },
		SetValue:         setMongoDBGitVersion,
	}

	definitions[MongoDBTopology] = &definition{
		Name:             MongoDBTopology,
		Kind:             SystemKind,
		AllowedSetScopes: Scope(0),
		EvalType:         types.EvalString,
		GetValue:         func(c *Container) values.SQLValue { return c.systemVariableContainer.mongoDBTopology },
		SetValue:         setMongoDBTopology,
	}

	definitions[MongoDBVersion] = &definition{
		Name:             MongoDBVersion,
		Kind:             SystemKind,
		AllowedSetScopes: Scope(0),
		EvalType:         types.EvalString,
		GetValue:         func(c *Container) values.SQLValue { return c.systemVariableContainer.mongoDBVersion },
		SetValue:         setMongoDBVersion,
	}

	definitions[MongoDBVersionCompatibility] = &definition{
		Name:             MongoDBVersionCompatibility,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope | SessionScope,
		EvalType:         types.EvalString,
		GetValue:         func(c *Container) values.SQLValue { return c.systemVariableContainer.mongoDBVersionCompatibility },
		SetValue:         setMongoDBVersionCompatibility,
	}

	definitions[MongosqldVersion] = &definition{
		Name:             MongosqldVersion,
		Kind:             SystemKind,
		AllowedSetScopes: Scope(0),
		EvalType:         types.EvalString,
		GetValue:         func(c *Container) values.SQLValue { return c.systemVariableContainer.mongosqldVersion },
		SetValue:         setMongosqldVersion,
	}

	definitions[OptimizeCrossJoins] = &definition{
		Name:             OptimizeCrossJoins,
		Kind:             SystemKind,
		AllowedSetScopes: SessionScope,
		EvalType:         types.EvalBoolean,
		GetValue:         func(c *Container) values.SQLValue { return c.systemVariableContainer.optimizeCrossJoins },
		SetValue:         setOptimizeCrossJoins,
	}

	definitions[OptimizeEvaluations] = &definition{
		Name:             OptimizeEvaluations,
		Kind:             SystemKind,
		AllowedSetScopes: SessionScope,
		EvalType:         types.EvalBoolean,
		GetValue:         func(c *Container) values.SQLValue { return c.systemVariableContainer.optimizeEvaluations },
		SetValue:         setOptimizeEvaluations,
	}

	definitions[OptimizeFiltering] = &definition{
		Name:             OptimizeFiltering,
		Kind:             SystemKind,
		AllowedSetScopes: SessionScope,
		EvalType:         types.EvalBoolean,
		GetValue:         func(c *Container) values.SQLValue { return c.systemVariableContainer.optimizeFiltering },
		SetValue:         setOptimizeFiltering,
	}

	definitions[OptimizeInnerJoins] = &definition{
		Name:             OptimizeInnerJoins,
		Kind:             SystemKind,
		AllowedSetScopes: SessionScope,
		EvalType:         types.EvalBoolean,
		GetValue:         func(c *Container) values.SQLValue { return c.systemVariableContainer.optimizeInnerJoins },
		SetValue:         setOptimizeInnerJoins,
	}

	definitions[OptimizeSelfJoins] = &definition{
		Name:             OptimizeSelfJoins,
		Kind:             SystemKind,
		AllowedSetScopes: SessionScope,
		EvalType:         types.EvalBoolean,
		GetValue:         func(c *Container) values.SQLValue { return c.systemVariableContainer.optimizeSelfJoins },
		SetValue:         setOptimizeSelfJoins,
	}

	definitions[OptimizeViewSampling] = &definition{
		Name:             OptimizeViewSampling,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope,
		EvalType:         types.EvalBoolean,
		GetValue:         func(c *Container) values.SQLValue { return c.systemVariableContainer.optimizeViewSampling },
		SetValue:         setOptimizeViewSampling,
	}

	definitions[PolymorphicTypeConversionMode] = &definition{
		Name:             PolymorphicTypeConversionMode,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope | SessionScope,
		EvalType:         types.EvalString,
		GetValue:         func(c *Container) values.SQLValue { return c.systemVariableContainer.polymorphicTypeConversionMode },
		SetValue:         setPolymorphicTypeConversionMode,
	}

	definitions[Pushdown] = &definition{
		Name:             Pushdown,
		Kind:             SystemKind,
		AllowedSetScopes: SessionScope,
		EvalType:         types.EvalBoolean,
		GetValue:         func(c *Container) values.SQLValue { return c.systemVariableContainer.pushdown },
		SetValue:         setPushdown,
	}

	definitions[RewriteDistinctAsGroup] = &definition{
		Name:             RewriteDistinctAsGroup,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope | SessionScope,
		EvalType:         types.EvalBoolean,
		GetValue:         func(c *Container) values.SQLValue { return c.systemVariableContainer.rewriteDistinctAsGroup },
		SetValue:         setRewriteDistinctAsGroup,
	}

	definitions[SampleRefreshIntervalSecs] = &definition{
		Name:             SampleRefreshIntervalSecs,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope,
		EvalType:         types.EvalInt64,
		GetValue:         func(c *Container) values.SQLValue { return c.systemVariableContainer.sampleRefreshIntervalSecs },
		SetValue:         setSampleRefreshIntervalSecs,
	}

	definitions[SampleSize] = &definition{
		Name:             SampleSize,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope,
		EvalType:         types.EvalInt64,
		GetValue:         func(c *Container) values.SQLValue { return c.systemVariableContainer.sampleSize },
		SetValue:         setSampleSize,
	}

	definitions[SchemaMappingMode] = &definition{
		Name:             SchemaMappingMode,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope,
		EvalType:         types.EvalString,
		GetValue:         func(c *Container) values.SQLValue { return c.systemVariableContainer.schemaMappingMode },
		SetValue:         setSchemaMappingMode,
	}

	definitions[TypeConversionMode] = &definition{
		Name:             TypeConversionMode,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope | SessionScope,
		EvalType:         types.EvalString,
		GetValue:         func(c *Container) values.SQLValue { return c.systemVariableContainer.typeConversionMode },
		SetValue:         setTypeConversionMode,
	}

	definitions[ReconcileArithmeticAggFunctions] = &definition{
		Name:             ReconcileArithmeticAggFunctions,
		Kind:             SystemKind,
		AllowedSetScopes: GlobalScope | SessionScope,
		EvalType:         types.EvalBoolean,
		GetValue:         func(c *Container) values.SQLValue { return c.systemVariableContainer.reconcileArithmeticAggFunctions },
		SetValue:         setReconcileArithmeticAggFunctions,
	}
}

func setAutocommit(c *Container, v values.SQLValue) error {
	val, err := convertSQLBool(Autocommit, v)
	if err != nil {
		return err
	}

	c.systemVariableContainer.autocommit = val
	return nil
}

func setInteractiveTimeoutSecs(c *Container, v values.SQLValue) error {
	val, err := convertSQLInt64(InteractiveTimeoutSecs, v)
	if err != nil {
		return err
	}

	if lessThan(val, 1) {
		return mysqlerrors.Defaultf(mysqlerrors.ErWrongValueForVar, InteractiveTimeoutSecs, val)
	}

	c.systemVariableContainer.interactiveTimeoutSecs = val
	return nil
}

func setMaxAllowedPacket(c *Container, v values.SQLValue) error {
	val, err := convertSQLInt64(MaxAllowedPacket, v)
	if err != nil {
		return err
	}

	if lessThan(val, 1024) {
		return mysqlerrors.Defaultf(mysqlerrors.ErWrongValueForVar, MaxAllowedPacket, val)
	}

	if greaterThan(val, 1073741824) {
		return mysqlerrors.Defaultf(mysqlerrors.ErWrongValueForVar, MaxAllowedPacket, val)
	}

	c.systemVariableContainer.maxAllowedPacket = val
	return nil
}

func setMaxConnections(c *Container, v values.SQLValue) error {
	val, err := convertSQLInt64(MaxConnections, v)
	if err != nil {
		return err
	}

	if lessThan(val, 0) {
		return mysqlerrors.Defaultf(mysqlerrors.ErWrongValueForVar, MaxConnections, val)
	}

	c.systemVariableContainer.maxConnections = val
	return nil
}

func setMaxTimeMS(c *Container, v values.SQLValue) error {
	val, err := convertSQLInt64(MaxTimeMS, v)
	if err != nil {
		return err
	}

	if lessThan(val, 0) {
		return mysqlerrors.Defaultf(mysqlerrors.ErWrongValueForVar, MaxTimeMS, val)
	}

	c.systemVariableContainer.maxTimeMS = val
	return nil
}

func setSocket(c *Container, v values.SQLValue) error {
	val, err := convertSQLVarchar(Socket, v)
	if err != nil {
		return err
	}

	c.systemVariableContainer.socket = val
	return nil
}

func setSQLAutoIsNull(c *Container, v values.SQLValue) error {
	val, err := convertSQLBool(SQLAutoIsNull, v)
	if err != nil {
		return err
	}

	c.systemVariableContainer.sqlAutoIsNull = val
	return nil
}

func setSQLSelectLimit(c *Container, v values.SQLValue) error {
	val, err := convertSQLUint64(SQLSelectLimit, v)
	if err != nil {
		return err
	}

	c.systemVariableContainer.sqlSelectLimit = val
	return nil
}

func setVersion(c *Container, v values.SQLValue) error {
	val, err := convertSQLVarchar(Version, v)
	if err != nil {
		return err
	}

	c.systemVariableContainer.version = val
	return nil
}

func setVersionComment(c *Container, v values.SQLValue) error {
	val, err := convertSQLVarchar(VersionComment, v)
	if err != nil {
		return err
	}

	c.systemVariableContainer.versionComment = val
	return nil
}

func setAnonymizeMetrics(c *Container, v values.SQLValue) error {
	val, err := convertSQLBool(AnonymizeMetrics, v)
	if err != nil {
		return err
	}

	c.systemVariableContainer.anonymizeMetrics = val
	return nil
}

func setEnableTableAlterations(c *Container, v values.SQLValue) error {
	val, err := convertSQLBool(EnableTableAlterations, v)
	if err != nil {
		return err
	}

	c.systemVariableContainer.enableTableAlterations = val
	return nil
}

func setFullPushdownExecMode(c *Container, v values.SQLValue) error {
	val, err := convertSQLBool(FullPushdownExecMode, v)
	if err != nil {
		return err
	}

	c.systemVariableContainer.fullPushdownExecMode = val
	return nil
}

func setMaxNestedTableDepth(c *Container, v values.SQLValue) error {
	val, err := convertSQLInt64(MaxNestedTableDepth, v)
	if err != nil {
		return err
	}

	if lessThan(val, 0) {
		return mysqlerrors.Defaultf(mysqlerrors.ErWrongValueForVar, MaxNestedTableDepth, val)
	}

	c.systemVariableContainer.maxNestedTableDepth = val
	return nil
}

func setMaxNumColumnsPerTable(c *Container, v values.SQLValue) error {
	val, err := convertSQLInt64(MaxNumColumnsPerTable, v)
	if err != nil {
		return err
	}

	if lessThan(val, 1) {
		return mysqlerrors.Defaultf(mysqlerrors.ErWrongValueForVar, MaxNumColumnsPerTable, val)
	}

	c.systemVariableContainer.maxNumColumnsPerTable = val
	return nil
}

func setMetricsBackend(c *Container, v values.SQLValue) error {
	val, err := convertSQLVarchar(MetricsBackend, v)
	if err != nil {
		return err
	}

	switch val.String() {
	case NoMetricsBackend:
		// valid
	case LogMetricsBackend:
		// valid
	case StitchMetricsBackend:
		// valid
	default:
		return mysqlerrors.Defaultf(mysqlerrors.ErWrongValueForVar, MetricsBackend, val)
	}

	c.systemVariableContainer.metricsBackend = val
	return nil
}

func setMongoDBMaxServerSize(c *Container, v values.SQLValue) error {
	val, err := convertSQLUint64(MongoDBMaxServerSize, v)
	if err != nil {
		return err
	}

	c.systemVariableContainer.mongoDBMaxServerSize = val
	return nil
}

func setMongoDBMaxConnectionSize(c *Container, v values.SQLValue) error {
	val, err := convertSQLUint64(MongoDBMaxConnectionSize, v)
	if err != nil {
		return err
	}

	c.systemVariableContainer.mongoDBMaxConnectionSize = val
	return nil
}

func setMongoDBMaxStageSize(c *Container, v values.SQLValue) error {
	val, err := convertSQLUint64(MongoDBMaxStageSize, v)
	if err != nil {
		return err
	}

	c.systemVariableContainer.mongoDBMaxStageSize = val
	return nil
}

func setMongoDBMaxVarcharLength(c *Container, v values.SQLValue) error {
	val, err := convertSQLUint64(MongoDBMaxVarcharLength, v)
	if err != nil {
		return err
	}

	if lessThan(val, 0) {
		return mysqlerrors.Defaultf(mysqlerrors.ErWrongValueForVar, MongoDBMaxVarcharLength, val)
	}

	if greaterThan(val, math.MaxUint16) {
		return mysqlerrors.Defaultf(mysqlerrors.ErWrongValueForVar, MongoDBMaxVarcharLength, val)
	}

	c.systemVariableContainer.mongoDBMaxVarcharLength = val
	return nil
}

func setMongoDBGitVersion(c *Container, v values.SQLValue) error {
	val, err := convertSQLVarchar(MongoDBGitVersion, v)
	if err != nil {
		return err
	}

	c.systemVariableContainer.mongoDBGitVersion = val
	return nil
}

func setMongoDBTopology(c *Container, v values.SQLValue) error {
	val, err := convertSQLVarchar(MongoDBTopology, v)
	if err != nil {
		return err
	}

	c.systemVariableContainer.mongoDBTopology = val
	return nil
}

func setMongoDBVersion(c *Container, v values.SQLValue) error {
	val, err := convertSQLVarchar(MongoDBVersion, v)
	if err != nil {
		return err
	}

	c.systemVariableContainer.mongoDBVersion = val
	return nil
}

func setMongoDBVersionCompatibility(c *Container, v values.SQLValue) error {
	val, err := convertSQLVarchar(MongoDBVersionCompatibility, v)
	if err != nil {
		return err
	}

	c.systemVariableContainer.mongoDBVersionCompatibility = val
	return nil
}

func setMongosqldVersion(c *Container, v values.SQLValue) error {
	val, err := convertSQLVarchar(MongosqldVersion, v)
	if err != nil {
		return err
	}

	c.systemVariableContainer.mongosqldVersion = val
	return nil
}

func setOptimizeCrossJoins(c *Container, v values.SQLValue) error {
	val, err := convertSQLBool(OptimizeCrossJoins, v)
	if err != nil {
		return err
	}

	c.systemVariableContainer.optimizeCrossJoins = val
	return nil
}

func setOptimizeEvaluations(c *Container, v values.SQLValue) error {
	val, err := convertSQLBool(OptimizeEvaluations, v)
	if err != nil {
		return err
	}

	c.systemVariableContainer.optimizeEvaluations = val
	return nil
}

func setOptimizeFiltering(c *Container, v values.SQLValue) error {
	val, err := convertSQLBool(OptimizeFiltering, v)
	if err != nil {
		return err
	}

	c.systemVariableContainer.optimizeFiltering = val
	return nil
}

func setOptimizeInnerJoins(c *Container, v values.SQLValue) error {
	val, err := convertSQLBool(OptimizeInnerJoins, v)
	if err != nil {
		return err
	}

	c.systemVariableContainer.optimizeInnerJoins = val
	return nil
}

func setOptimizeSelfJoins(c *Container, v values.SQLValue) error {
	val, err := convertSQLBool(OptimizeSelfJoins, v)
	if err != nil {
		return err
	}

	c.systemVariableContainer.optimizeSelfJoins = val
	return nil
}

func setOptimizeViewSampling(c *Container, v values.SQLValue) error {
	val, err := convertSQLBool(OptimizeViewSampling, v)
	if err != nil {
		return err
	}

	c.systemVariableContainer.optimizeViewSampling = val
	return nil
}

func setPolymorphicTypeConversionMode(c *Container, v values.SQLValue) error {
	val, err := convertSQLVarchar(PolymorphicTypeConversionMode, v)
	if err != nil {
		return err
	}

	switch val.String() {
	case SafePolymorphicTypeConversionMode:
		// valid
	case FastPolymorphicTypeConversionMode:
		// valid
	case OffPolymorphicTypeConversionMode:
		// valid
	default:
		return mysqlerrors.Defaultf(mysqlerrors.ErWrongValueForVar, PolymorphicTypeConversionMode, val)
	}

	c.systemVariableContainer.polymorphicTypeConversionMode = val
	return nil
}

func setPushdown(c *Container, v values.SQLValue) error {
	val, err := convertSQLBool(Pushdown, v)
	if err != nil {
		return err
	}

	c.systemVariableContainer.pushdown = val
	return nil
}

func setRewriteDistinctAsGroup(c *Container, v values.SQLValue) error {
	val, err := convertSQLBool(RewriteDistinctAsGroup, v)
	if err != nil {
		return err
	}

	c.systemVariableContainer.rewriteDistinctAsGroup = val
	return nil
}

func setSampleRefreshIntervalSecs(c *Container, v values.SQLValue) error {
	val, err := convertSQLInt64(SampleRefreshIntervalSecs, v)
	if err != nil {
		return err
	}

	if lessThan(val, 0) {
		return mysqlerrors.Defaultf(mysqlerrors.ErWrongValueForVar, SampleRefreshIntervalSecs, val)
	}

	c.systemVariableContainer.sampleRefreshIntervalSecs = val
	return nil
}

func setSampleSize(c *Container, v values.SQLValue) error {
	val, err := convertSQLInt64(SampleSize, v)
	if err != nil {
		return err
	}

	if lessThan(val, 0) {
		return mysqlerrors.Defaultf(mysqlerrors.ErWrongValueForVar, SampleSize, val)
	}

	c.systemVariableContainer.sampleSize = val
	return nil
}

func setSchemaMappingMode(c *Container, v values.SQLValue) error {
	val, err := convertSQLVarchar(SchemaMappingMode, v)
	if err != nil {
		return err
	}

	switch val.String() {
	case MajoritySchemaMappingMode:
		// valid
	case LatticeSchemaMappingMode:
		// valid
	default:
		return mysqlerrors.Defaultf(mysqlerrors.ErWrongValueForVar, SchemaMappingMode, val)
	}

	c.systemVariableContainer.schemaMappingMode = val
	return nil
}

func setTypeConversionMode(c *Container, v values.SQLValue) error {
	val, err := convertSQLVarchar(TypeConversionMode, v)
	if err != nil {
		return err
	}

	switch val.String() {
	case MongoSQLTypeConversionMode:
		// valid
	case MySQLTypeConversionMode:
		// valid
	default:
		return mysqlerrors.Defaultf(mysqlerrors.ErWrongValueForVar, TypeConversionMode, val)
	}

	c.systemVariableContainer.typeConversionMode = val
	return nil
}

func setReconcileArithmeticAggFunctions(c *Container, v values.SQLValue) error {
	val, err := convertSQLBool(ReconcileArithmeticAggFunctions, v)
	if err != nil {
		return err
	}

	c.systemVariableContainer.reconcileArithmeticAggFunctions = val
	return nil
}
