// Copyright 2012, Google Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package parser

import (
	"errors"
	"fmt"
	"strings"

	"github.com/10gen/sqlproxy/parser/sqltypes"
	"github.com/10gen/sqlproxy/schema"
)

// Instructions for creating new types: If a type
// needs to satisfy an interface, declare that function
// along with that interface. This will help users
// identify the list of types to which they can assert
// those interfaces.
// If the member of a type has a string with a predefined
// list of values, declare those values as const following
// the type.
// For interfaces that define dummy functions to consolidate
// a set of types, define the function as ITypeName.
// This will help avoid name collisions.

// Parse parses the sql and returns a Statement, which
// is the AST representation of the query.
func Parse(sql string) (Statement, error) {
	tokenizer := NewStringTokenizer(sql)
	if yyParse(tokenizer) != 0 {
		return nil, errors.New(tokenizer.LastError)
	}
	return tokenizer.ParseTree, nil
}

// SQLNode defines the interface for all nodes
// generated by the parser.
type SQLNode interface {
	Format(buf *TrackedBuffer)
}

// String returns a string representation of an SQLNode.
func String(node SQLNode) string {
	buf := NewTrackedBuffer(nil)
	buf.Fprintf("%v", node)
	return buf.String()
}

// Statement represents a statement.
type Statement interface {
	IStatement()
	SQLNode
}

func (*Union) IStatement()     {}
func (*Select) IStatement()    {}
func (*Set) IStatement()       {}
func (*Use) IStatement()       {}
func (*DropTable) IStatement() {}

type Use struct {
	DBName []byte
}

func (u *Use) Format(buf *TrackedBuffer) {
	buf.Fprintf("USE %s", u.DBName)
}

// SelectStatement any SELECT statement.
type SelectStatement interface {
	ISelectStatement()
	IStatement()
	SQLNode
}

func (*Select) ISelectStatement() {}
func (*Union) ISelectStatement()  {}

// Select represents a SELECT statement.
type Select struct {
	Comments    Comments
	Distinct    string
	SelectExprs SelectExprs
	From        TableExprs
	Where       *Where
	GroupBy     GroupBy
	Having      *Where
	OrderBy     OrderBy
	Limit       *Limit
	Lock        string
}

// Select.Distinct
const (
	AST_DISTINCT = "distinct "
)

// Select.Lock
const (
	AST_FOR_UPDATE = " for update"
	AST_SHARE_MODE = " lock in share mode"
)

func (node *Select) Format(buf *TrackedBuffer) {
	buf.Fprintf("select %v%s%v from %v%v%v%v%v%v%s",
		node.Comments, node.Distinct, node.SelectExprs,
		node.From, node.Where,
		node.GroupBy, node.Having, node.OrderBy,
		node.Limit, node.Lock)
}

// Union represents a UNION statement.
type Union struct {
	Type        string
	Left, Right SelectStatement
}

// Union.Type
const (
	AST_UNION     = "union"
	AST_UNION_ALL = "union all"
	AST_SET_MINUS = "minus"
	AST_EXCEPT    = "except"
	AST_INTERSECT = "intersect"
)

func (node *Union) Format(buf *TrackedBuffer) {
	buf.Fprintf("%v %s %v", node.Left, node.Type, node.Right)
}

// Set represents a SET statement.
type Set struct {
	Comments Comments
	Exprs    UpdateExprs
}

func (node *Set) Format(buf *TrackedBuffer) {
	buf.Fprintf("set %v%v", node.Comments, node.Exprs)
}

const (
	AST_DROP_TABLE_RESTRICT = "restrict"
	AST_DROP_TABLE_CASCADE  = "cascade"
)

// DropTable represents a drop table statement.
type DropTable struct {
	Name      *TableName
	Exists    bool
	Temporary bool
	Opt       []byte
}

func (node *DropTable) Format(buf *TrackedBuffer) {
	buf.Fprintf("drop ")
	if node.Temporary {
		buf.Fprintf("temporary ")
	}
	buf.Fprintf("table ")
	if node.Exists {
		buf.Fprintf("if exists ")
	}
	node.Name.Format(buf)
	if node.Opt != nil {
		buf.Fprintf(" %s", string(node.Opt))
	}
}

// Comments represents a list of comments.
type Comments [][]byte

func (node Comments) Format(buf *TrackedBuffer) {
	for i, c := range node {
		buf.Fprintf("%s", c)
		if i != len(node)-1 {
			buf.Fprintf(" ")
		}
	}
}

// SelectExprs represents SELECT expressions.
type SelectExprs []SelectExpr

func (node SelectExprs) Format(buf *TrackedBuffer) {
	var prefix string
	for _, n := range node {
		buf.Fprintf("%s%v", prefix, n)
		prefix = ", "
	}
}

// SelectExpr represents a SELECT expression.
type SelectExpr interface {
	ISelectExpr()
	SQLNode
}

func (*StarExpr) ISelectExpr()    {}
func (*NonStarExpr) ISelectExpr() {}

// StarExpr defines a '*' or 'table.*' expression.
type StarExpr struct {
	TableName []byte
}

func (node *StarExpr) Format(buf *TrackedBuffer) {
	if node.TableName != nil {
		buf.Fprintf("%s.", node.TableName)
	}
	buf.Fprintf("*")
}

// NonStarExpr defines a non-'*' select expr.
type NonStarExpr struct {
	Expr Expr
	As   []byte
}

func (node *NonStarExpr) Format(buf *TrackedBuffer) {
	buf.Fprintf("%v", node.Expr)
	if node.As != nil {
		buf.Fprintf(" as %s", node.As)
	}
}

// Columns represents an insert column list.
// The syntax for Columns is a subset of SelectExprs.
// So, it's castable to a SelectExprs and can be analyzed
// as such.
type Columns []SelectExpr

func (node Columns) Format(buf *TrackedBuffer) {
	if node == nil {
		return
	}
	buf.Fprintf("(%v)", SelectExprs(node))
}

// ColumnExprs represents a list of column names.
type ColumnExprs []*ColName

func (node ColumnExprs) Format(buf *TrackedBuffer) {
	var prefix string
	for _, n := range node {
		buf.Fprintf("%s%v", prefix, n)
		prefix = ", "
	}
}

// TableExprs represents a list of table expressions.
type TableExprs []TableExpr

func (node TableExprs) Format(buf *TrackedBuffer) {
	var prefix string
	for _, n := range node {
		buf.Fprintf("%s%v", prefix, n)
		prefix = ", "
	}
}

// TableExpr represents a table expression.
type TableExpr interface {
	ITableExpr()
	SQLNode
}

func (*AliasedTableExpr) ITableExpr() {}
func (*ParenTableExpr) ITableExpr()   {}
func (*JoinTableExpr) ITableExpr()    {}

// AliasedTableExpr represents a table expression
// coupled with an optional alias or index hint.
type AliasedTableExpr struct {
	Expr  SimpleTableExpr
	As    []byte
	Hints *IndexHints
}

func (node *AliasedTableExpr) Format(buf *TrackedBuffer) {
	buf.Fprintf("%v", node.Expr)
	if node.As != nil {
		buf.Fprintf(" as %s", node.As)
	}
	if node.Hints != nil {
		// Hint node provides the space padding.
		buf.Fprintf("%v", node.Hints)
	}
}

// SimpleTableExpr represents a simple table expression.
type SimpleTableExpr interface {
	ISimpleTableExpr()
	SQLNode
}

func (*TableName) ISimpleTableExpr() {}
func (*Subquery) ISimpleTableExpr()  {}

// TableName represents a table  name.
type TableName struct {
	Name, Qualifier []byte
}

func (node *TableName) Format(buf *TrackedBuffer) {
	if node.Qualifier != nil {
		escape(buf, node.Qualifier)
		buf.Fprintf(".")
	}
	escape(buf, node.Name)
}

// ParenTableExpr represents a parenthesized TableExpr.
type ParenTableExpr struct {
	Expr TableExpr
}

func (node *ParenTableExpr) Format(buf *TrackedBuffer) {
	buf.Fprintf("(%v)", node.Expr)
}

// JoinTableExpr represents a TableExpr that's a JOIN operation.
type JoinTableExpr struct {
	LeftExpr  TableExpr
	Join      string
	RightExpr TableExpr
	On        Expr
	Using     ColumnExprs
}

// JoinTableExpr.Join
const (
	AST_JOIN               = "join"
	AST_STRAIGHT_JOIN      = "straight_join"
	AST_LEFT_JOIN          = "left join"
	AST_RIGHT_JOIN         = "right join"
	AST_CROSS_JOIN         = "cross join"
	AST_NATURAL_JOIN       = "natural join"
	AST_NATURAL_LEFT_JOIN  = "natural left join"
	AST_NATURAL_RIGHT_JOIN = "natural right join"
)

func (node *JoinTableExpr) Format(buf *TrackedBuffer) {
	buf.Fprintf("%v %s %v", node.LeftExpr, node.Join, node.RightExpr)
	if node.On != nil {
		buf.Fprintf(" on %v", node.On)
	}
	if node.Using != nil {
		buf.Fprintf(" using (%v)", node.Using)
	}
}

// IndexHints represents a list of index hints.
type IndexHints struct {
	Type    string
	Indexes [][]byte
}

const (
	AST_USE    = "use"
	AST_IGNORE = "ignore"
	AST_FORCE  = "force"
)

func (node *IndexHints) Format(buf *TrackedBuffer) {
	buf.Fprintf(" %s index ", node.Type)
	prefix := "("
	for _, n := range node.Indexes {
		buf.Fprintf("%s%s", prefix, n)
		prefix = ", "
	}
	buf.Fprintf(")")
}

// Where represents a WHERE or HAVING clause.
type Where struct {
	Type string
	Expr Expr
}

// Where.Type
const (
	AST_WHERE  = "where"
	AST_HAVING = "having"
)

// NewWhere creates a WHERE or HAVING clause out
// of an Expr. If the expression is nil, it returns nil.
func NewWhere(typ string, expr Expr) *Where {
	if expr == nil {
		return nil
	}
	return &Where{Type: typ, Expr: expr}
}

func (node *Where) Format(buf *TrackedBuffer) {
	if node == nil {
		return
	}
	buf.Fprintf(" %s %v", node.Type, node.Expr)
}

// Expr represents an expression.
type Expr interface {
	IExpr()
	SQLNode
}

func (*AndExpr) IExpr()        {}
func (*OrExpr) IExpr()         {}
func (*XorExpr) IExpr()        {}
func (*NotExpr) IExpr()        {}
func (*ComparisonExpr) IExpr() {}
func (*LikeExpr) IExpr()       {}
func (*RegexExpr) IExpr()      {}
func (*RLikeExpr) IExpr()      {}
func (*RangeCond) IExpr()      {}
func (*ExistsExpr) IExpr()     {}
func (DateVal) IExpr()         {}
func (StrVal) IExpr()          {}
func (NumVal) IExpr()          {}
func (ValArg) IExpr()          {}
func (KeywordVal) IExpr()      {}
func (*NullVal) IExpr()        {}
func (*ColName) IExpr()        {}
func (*TrueVal) IExpr()        {}
func (*FalseVal) IExpr()       {}
func (*UnknownVal) IExpr()     {}
func (ValTuple) IExpr()        {}
func (*Subquery) IExpr()       {}
func (*BinaryExpr) IExpr()     {}
func (*UnaryExpr) IExpr()      {}
func (*FuncExpr) IExpr()       {}
func (*CaseExpr) IExpr()       {}

// AndExpr represents an AND expression.
type AndExpr struct {
	Left, Right Expr
}

func (node *AndExpr) Format(buf *TrackedBuffer) {
	buf.Fprintf("%v and %v", node.Left, node.Right)
}

// OrExpr represents an OR expression.
type OrExpr struct {
	Left, Right Expr
}

func (node *OrExpr) Format(buf *TrackedBuffer) {
	buf.Fprintf("%v or %v", node.Left, node.Right)
}

// XorExpr represents an XOR expression.
type XorExpr struct {
	Left, Right Expr
}

func (node *XorExpr) Format(buf *TrackedBuffer) {
	buf.Fprintf("%v xor %v", node.Left, node.Right)
}

// NotExpr represents a NOT expression.
type NotExpr struct {
	Expr Expr
}

func (node *NotExpr) Format(buf *TrackedBuffer) {
	buf.Fprintf("not %v", node.Expr)
}

// ComparisonExpr represents a two-value comparison expression.
type ComparisonExpr struct {
	Operator         string
	Left, Right      Expr
	SubqueryOperator string
}

// ComparisonExpr.Operator
const (
	AST_EQ     = "="
	AST_LT     = "<"
	AST_GT     = ">"
	AST_LE     = "<="
	AST_GE     = ">="
	AST_NE     = "!="
	AST_NSE    = "<=>"
	AST_IN     = "in"
	AST_NOT_IN = "not in"
	AST_IS     = "is"
	AST_IS_NOT = "is not"
)

// ComparisonExpr.SubqueryOperator
const (
	AST_ALL  = "all"
	AST_ANY  = "any"
	AST_SOME = "some"
)

func (node *ComparisonExpr) Format(buf *TrackedBuffer) {
	buf.Fprintf("%v %s %v", node.Left, node.Operator, node.Right)
}

// LikeExpr.Operator
const (
	AST_LIKE     = "like"
	AST_NOT_LIKE = "not like"
)

// LikeExpr represents a two-value comparison expression.
type LikeExpr struct {
	Operator    string
	Left, Right Expr
	Escape      Expr
}

func (node *LikeExpr) Format(buf *TrackedBuffer) {
	switch typedN := node.Escape.(type) {
	case StrVal:
		if string(typedN) == "\\" {
			buf.Fprintf("%v %s %v", node.Left, node.Operator, node.Right)
			return
		}
	}
	buf.Fprintf("%v %s %v escape %v", node.Left, node.Operator, node.Right, node.Escape)
}

// RangeCond represents a BETWEEN or a NOT BETWEEN expression.
type RangeCond struct {
	Operator string
	Left     Expr
	From, To Expr
}

// RangeCond.Operator
const (
	AST_BETWEEN     = "between"
	AST_NOT_BETWEEN = "not between"
)

func (node *RangeCond) Format(buf *TrackedBuffer) {
	buf.Fprintf("%v %s from %v to %v", node.Left, node.Operator, node.From, node.To)
}

// RegexExpr represents a Regex expression that matches a pattern with an expression.
type RegexExpr struct {
	Operand Expr
	Pattern Expr
}

// This node is synonymous with the one above, simply here so that there
// can be a distinction between the input commands when formatted.
type RLikeExpr struct {
	Operand Expr
	Pattern Expr
}

func (node *RegexExpr) Format(buf *TrackedBuffer) {
	buf.Fprintf("%v regexp %v", node.Operand, node.Pattern)
}

func (node *RLikeExpr) Format(buf *TrackedBuffer) {
	buf.Fprintf("%v rlike %v", node.Operand, node.Pattern)
}

// ExistsExpr represents an EXISTS expression.
type ExistsExpr struct {
	Subquery *Subquery
}

func (node *ExistsExpr) Format(buf *TrackedBuffer) {
	buf.Fprintf("exists %v", node.Subquery)
}

// DateVal represents a date literal.
type DateVal struct {
	Name string
	Val  []byte
}

const (
	AST_DATE      = "date"
	AST_TIME      = "time"
	AST_TIMESTAMP = "timestamp"
	AST_DATETIME  = "datetime"
)

func (node DateVal) Format(buf *TrackedBuffer) {
	buf.Fprintf("%s(%s)", node.Name, node.Val)
}

// StrVal represents a string value.
type StrVal []byte

func (node StrVal) Format(buf *TrackedBuffer) {
	s := sqltypes.MakeString([]byte(node))
	s.EncodeSql(buf)
}

// NumVal represents a number.
type NumVal []byte

func (node NumVal) Format(buf *TrackedBuffer) {
	buf.Fprintf("%s", []byte(node))
}

// ValArg represents a named bind var argument.
type ValArg []byte

func (node ValArg) Format(buf *TrackedBuffer) {
	buf.WriteArg(string(node[1:]))
}

// necessary so keywords aren't quoted in output of SQL query
// (i.e. the output column from SELECT TIMESTAMPADD(YEAR, 1, DATE "2006-01-02")
// should be TIMESTAMPADD(YEAR, 1, DATE "2006-01-02") and not TIMESTAMPADD('YEAR', 1, DATE "2006-01-02"))
type KeywordVal []byte

func (node KeywordVal) Format(buf *TrackedBuffer) {
	buf.Fprintf("%s", []byte(node))
}

// NullVal represents a NULL value.
type NullVal struct{}

func (node *NullVal) Format(buf *TrackedBuffer) {
	buf.Fprintf("null")
}

// TrueVal represents a TRUE value.
type TrueVal struct{}

func (node *TrueVal) Format(buf *TrackedBuffer) {
	buf.Fprintf("true")
}

// FalseVal represents a FALSE value.
type FalseVal struct{}

func (node *FalseVal) Format(buf *TrackedBuffer) {
	buf.Fprintf("false")
}

// UnknownVal represents a UNKNOWN value.
type UnknownVal struct{}

func (node *UnknownVal) Format(buf *TrackedBuffer) {
	buf.Fprintf("unknown")
}

// ColName represents a column name.
type ColName struct {
	Name, Qualifier []byte
}

func (node *ColName) Format(buf *TrackedBuffer) {
	if node.Qualifier != nil {
		escape(buf, node.Qualifier)
		buf.Fprintf(".")
	}
	escape(buf, node.Name)
}

func escape(buf *TrackedBuffer, name []byte) {
	if _, ok := keywords[strings.ToLower(string(name))]; ok {
		buf.Fprintf("`%s`", name)
	} else {
		buf.Fprintf("%s", name)
	}
}

// Tuple represents a tuple. It can be ValTuple, Subquery.
type Tuple interface {
	ITuple()
	Expr
}

func (ValTuple) ITuple()  {}
func (*Subquery) ITuple() {}

// ValTuple represents a tuple of actual values.
type ValTuple Exprs

func (node ValTuple) Format(buf *TrackedBuffer) {
	buf.Fprintf("(%v)", Exprs(node))
}

// Exprs represents a list of value expressions.
// It's not a valid expression because it's not parenthesized.
type Exprs []Expr

func (node Exprs) Format(buf *TrackedBuffer) {
	var prefix string
	for _, n := range node {
		buf.Fprintf("%s%v", prefix, n)
		prefix = ", "
	}
}

// Subquery represents a subquery.
type Subquery struct {
	Select    SelectStatement
	IsDerived bool
}

func (node *Subquery) Format(buf *TrackedBuffer) {
	buf.Fprintf("(%v)", node.Select)
}

// BinaryExpr represents a binary value expression.
type BinaryExpr struct {
	Operator    byte
	Left, Right Expr
}

// BinaryExpr.Operator
const (
	AST_BITAND = '&'
	AST_BITOR  = '|'
	AST_BITXOR = '^'
	AST_PLUS   = '+'
	AST_MINUS  = '-'
	AST_MULT   = '*'
	AST_DIV    = '/'
	AST_IDIV   = 'd'
	AST_MOD    = '%'
)

func (node *BinaryExpr) Format(buf *TrackedBuffer) {
	buf.Fprintf("%v%c%v", node.Left, node.Operator, node.Right)
}

// UnaryExpr represents a unary value expression.
type UnaryExpr struct {
	Operator byte
	Expr     Expr
}

// UnaryExpr.Operator
const (
	AST_UPLUS  = '+'
	AST_UMINUS = '-'
	AST_TILDA  = '~'
)

func (node *UnaryExpr) Format(buf *TrackedBuffer) {
	buf.Fprintf("%c%v", node.Operator, node.Expr)
}

// FuncExpr represents a function call.
type FuncExpr struct {
	Name     []byte
	Distinct bool
	Exprs    SelectExprs
}

func (node *FuncExpr) Format(buf *TrackedBuffer) {
	var distinct string
	if node.Distinct {
		distinct = "distinct "
	}
	buf.Fprintf("%s(%s%v)", node.Name, distinct, node.Exprs)
}

// CaseExpr represents a CASE expression.
type CaseExpr struct {
	Expr  Expr
	Whens []*When
	Else  Expr
}

func (node *CaseExpr) Format(buf *TrackedBuffer) {
	buf.Fprintf("case ")
	if node.Expr != nil {
		buf.Fprintf("%v ", node.Expr)
	}
	for _, when := range node.Whens {
		buf.Fprintf("%v ", when)
	}
	if node.Else != nil {
		buf.Fprintf("else %v ", node.Else)
	}
	buf.Fprintf("end")
}

// When represents a WHEN sub-expression.
type When struct {
	Cond Expr
	Val  Expr
}

func (node *When) Format(buf *TrackedBuffer) {
	buf.Fprintf("when %v then %v", node.Cond, node.Val)
}

// Values represents a VALUES clause.
type Values []Tuple

func (node Values) Format(buf *TrackedBuffer) {
	prefix := "values "
	for _, n := range node {
		buf.Fprintf("%s%v", prefix, n)
		prefix = ", "
	}
}

// GroupBy represents a GROUP BY clause.
type GroupBy []Expr

func (node GroupBy) Format(buf *TrackedBuffer) {
	prefix := " group by "
	for _, n := range node {
		buf.Fprintf("%s%v", prefix, n)
		prefix = ", "
	}
}

// OrderBy represents an ORDER By clause.
type OrderBy []*Order

func (node OrderBy) Format(buf *TrackedBuffer) {
	prefix := " order by "
	for _, n := range node {
		buf.Fprintf("%s%v", prefix, n)
		prefix = ", "
	}
}

// Order represents an ordering expression.
type Order struct {
	Expr      Expr
	Direction string
}

// Order.Direction
const (
	AST_ASC  = "asc"
	AST_DESC = "desc"
)

func (node *Order) Format(buf *TrackedBuffer) {
	buf.Fprintf("%v %s", node.Expr, node.Direction)
}

// Limit represents a LIMIT clause.
type Limit struct {
	Offset, Rowcount Expr
}

func (node *Limit) Format(buf *TrackedBuffer) {
	if node == nil {
		return
	}
	buf.Fprintf(" limit ")
	if node.Offset != nil {
		buf.Fprintf("%v, ", node.Offset)
	}
	buf.Fprintf("%v", node.Rowcount)
}

// UpdateExprs represents a list of update expressions.
type UpdateExprs []*UpdateExpr

func (node UpdateExprs) Format(buf *TrackedBuffer) {
	var prefix string
	for _, n := range node {
		buf.Fprintf("%s%v", prefix, n)
		prefix = ", "
	}
}

// UpdateExpr represents an update expression.
type UpdateExpr struct {
	Name *ColName
	Expr Expr
}

func (node *UpdateExpr) Format(buf *TrackedBuffer) {
	buf.Fprintf("%v = %v", node.Name, node.Expr)
}

type SimpleSelect struct {
	Comments    Comments
	Distinct    string
	SelectExprs SelectExprs
	Limit       *Limit
}

func (node *SimpleSelect) Format(buf *TrackedBuffer) {
	buf.Fprintf("select %v%s%v", node.Comments, node.Distinct, node.SelectExprs)
}

func (*SimpleSelect) IStatement()       {}
func (*SimpleSelect) ISelectStatement() {}

const (
	AST_SHOW_NO_MOD   = ""
	AST_SHOW_FULL     = "full"
	AST_SESSION_SCOPE = "session"
	AST_GLOBAL_SCOPE  = "global"
)

type Show struct {
	Section     string
	Key         string
	From        Expr
	LikeOrWhere Expr
	Modifier    string
}

func (*Show) IStatement() {}

func (node *Show) Format(buf *TrackedBuffer) {
	buf.Fprintf("show %s %s %v %v", node.Section, node.Key, node.From, node.LikeOrWhere)
}

const (
	AST_EXPLAIN_EXTENDED           = "extended"
	AST_EXPLAIN_FORMAT_JSON        = "json"
	AST_EXPLAIN_FORMAT_TRADITIONAL = "traditional"
	AST_EXPLAIN_PARTITIONS         = "partitions"
)

type Explain struct {
	Section     string
	Table       *TableName
	Column      *ColName
	ExplainType string
	Connection  []byte
	Statement   Statement
}

func (*Explain) IStatement() {}

func (node *Explain) Format(buf *TrackedBuffer) {
	buf.Fprintf("explain %v %v", node.Table, node.Column)
}

const (
	AST_KILL_CONNECTION = "connection"
	AST_KILL_QUERY      = "query"
)

func (*Kill) IStatement() {}

type Kill struct {
	Scope string
	ID    Expr
}

func (node *Kill) Format(buf *TrackedBuffer) {
	buf.Fprintf("kill %s %v", node.Scope, node.ID)
}

func (*Flush) IStatement() {}

type FlushKind string

const (
	FlushLogs   = "logs"
	FlushSample = "sample"
)

type Flush struct {
	Kind FlushKind
}

func (f *Flush) Format(buf *TrackedBuffer) {
	buf.Fprintf("flush %s", string(f.Kind))
}

type AlterTable struct {
	Table *TableName
	Specs []*AlterSpec
}

func (*AlterTable) IStatement() {}

func (a *AlterTable) Format(buf *TrackedBuffer) {
	buf.Fprintf("alter table ")
	a.Table.Format(buf)
	buf.Fprintf(" %s", a.Specs[0].String())
	for _, spec := range a.Specs[1:] {
		buf.Fprintf(", %s", spec.String())
	}
}

type AlterSpec struct {
	Type      schema.AlterationType
	Column    *ColName
	NewColumn *ColName
	NewTable  *TableName
}

func (a *AlterSpec) String() string {
	switch a.Type {
	case schema.RenameColumn:
		return fmt.Sprintf("change column %s %s", a.Column.Name, a.NewColumn.Name)
	case schema.DropColumn:
		return fmt.Sprintf("drop column %s", a.Column.Name)
	case schema.RenameTable:
		return fmt.Sprintf("rename to %s", a.NewTable.Name)
	}
	return "<unknown alteration type>"
}

type RenameTable struct {
	Renames []*RenameSpec
}

func (*RenameTable) IStatement() {}

func (r *RenameTable) Format(buf *TrackedBuffer) {
	buf.Fprintf("rename table")
	buf.Fprintf(" %s to %s", r.Renames[0].Table.Name, r.Renames[0].NewTable.Name)
	for _, rn := range r.Renames[1:] {
		buf.Fprintf(", %s to %s", rn.Table.Name, rn.NewTable.Name)
	}
}

type RenameSpec struct {
	Table    *TableName
	NewTable *TableName
}
