// Copyright 2012, Google Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// nolint: golint
package parser

import (
	"errors"
	"strings"

	"github.com/10gen/sqlproxy/internal/option"
	"github.com/10gen/sqlproxy/parser/sqltypes"
)

type OptString = option.String

// Instructions for creating new types: If a type
// needs to satisfy an interface, declare that function
// along with that interface. This will help users
// identify the list of types to which they can assert
// those interfaces.
// If the member of a type has a string with a predefined
// list of values, declare those values as const following
// the type.
// For interfaces that define dummy functions to consolidate
// a set of types, define the function as ITypeName.
// This will help avoid name collisions.

// Parse parses the sql and returns a Statement, which
// is the AST representation of the query.
func Parse(sql string) (Statement, error) {
	tokenizer := NewStringTokenizer(sql)
	if yyParse(tokenizer) != 0 {
		return nil, errors.New(tokenizer.LastError)
	}
	return tokenizer.ParseTree, nil
}

// SQLNode defines the interface for all nodes
// generated by the parser.
type SQLNode interface {
	Format(buf *TrackedBuffer)
}

// String returns a string representation of an SQLNode.
func String(node SQLNode) string {
	buf := NewTrackedBuffer(nil)
	buf.Fprintf("%v", node)
	return buf.String()
}

// Statement represents a statement.
type Statement interface {
	IStatement()
	SQLNode
	CST
}

func (*Union) IStatement()     {}
func (*Select) IStatement()    {}
func (*Set) IStatement()       {}
func (*Use) IStatement()       {}
func (*DropTable) IStatement() {}

type Use struct {
	DBName string
}

func (u *Use) Format(buf *TrackedBuffer) {
	buf.Fprintf("USE %s", u.DBName)
}

type CTE struct {
	TableName   *TableName
	ColumnExprs ColumnExprs
	Query       SelectStatement
}

func (c *CTE) Format(buf *TrackedBuffer) {
	buf.Fprintf("%v ", c.TableName)
	if len(c.ColumnExprs) > 0 {
		buf.Fprintf("(%v) ", c.ColumnExprs)
	}
	buf.Fprintf("as (%v)", c.Query)
}

type CTEs []*CTE

func (c CTEs) Format(buf *TrackedBuffer) {
	for i, cte := range c {
		buf.Fprintf("%v", cte)
		if i != len(c)-1 {
			buf.Fprintf(", ")
		}
	}
}

type With struct {
	CTEs      CTEs
	Recursive bool
}

func (w *With) Format(buf *TrackedBuffer) {
	buf.Fprintf("with ")
	if w.Recursive {
		buf.Fprintf("recursive ")
	}
	buf.Fprintf("%v", w.CTEs)
}

// SelectStatement any SELECT statement.
type SelectStatement interface {
	ISelectStatement()
	IStatement()
	SQLNode
	CST
}

func (*Select) ISelectStatement() {}
func (*Union) ISelectStatement()  {}

// Select represents a SELECT statement.
type Select struct {
	With         *With
	Comments     Comments
	QueryGlobals *QueryGlobals
	SelectExprs  SelectExprs
	From         TableExprs
	Where        *Where
	GroupBy      GroupBy
	Having       *Where
	OrderBy      OrderBy
	Limit        *Limit
	Lock         string
}

// Select.QueryGlobals
type QueryGlobals struct {
	Distinct     bool
	StraightJoin bool
}

// Select.Distinct
const (
	AST_DISTINCT = "distinct "
)

// Select.Lock
const (
	AST_FOR_UPDATE = " for update"
	AST_SHARE_MODE = " lock in share mode"
)

func (node *Select) Format(buf *TrackedBuffer) {
	if node.With != nil {
		buf.Fprintf("%v ", node.With)
	}
	var distinct, straightJoin, from string
	if node.QueryGlobals != nil {
		if node.QueryGlobals.Distinct {
			distinct = "distinct "
		}
		if node.QueryGlobals.StraightJoin {
			straightJoin = "straight join "
		}
	}
	if node.From != nil {
		from = " from "
	}

	buf.Fprintf("select %v%s%s%v%s%v%v%v%v%v%v%s",
		node.Comments, distinct, straightJoin,
		node.SelectExprs, from, node.From, node.Where,
		node.GroupBy, node.Having, node.OrderBy,
		node.Limit, node.Lock)
}

// Union represents a UNION statement.
type Union struct {
	With        *With
	Type        string
	Left, Right SelectStatement
}

// Union.Type
const (
	AST_UNION     = "union"
	AST_UNION_ALL = "union all"
	AST_SET_MINUS = "minus"
	AST_EXCEPT    = "except"
	AST_INTERSECT = "intersect"
)

func (node *Union) Format(buf *TrackedBuffer) {
	buf.Fprintf("%v %s %v", node.Left, node.Type, node.Right)
}

// Set represents a SET statement.
type Set struct {
	Scope    string
	Comments Comments
	Exprs    UpdateExprs
}

func (node *Set) Format(buf *TrackedBuffer) {
	if node.Scope != "" {
		buf.Fprintf("set %s %v%v", node.Scope, node.Comments, node.Exprs)
	} else {
		buf.Fprintf("set %v%v", node.Comments, node.Exprs)
	}
}

const (
	AST_DROP_TABLE_RESTRICT = "restrict"
	AST_DROP_TABLE_CASCADE  = "cascade"
)

// DropTable represents a drop table statement.
type DropTable struct {
	Name      *TableName
	Exists    bool
	Temporary bool
	Opt       option.String
}

func (node *DropTable) Format(buf *TrackedBuffer) {
	buf.Fprintf("drop ")
	if node.Temporary {
		buf.Fprintf("temporary ")
	}
	buf.Fprintf("table ")
	if node.Exists {
		buf.Fprintf("if exists ")
	}
	node.Name.Format(buf)
	buf.Fprintf(node.Opt.Map(prependSpace).Else(""))
}

// Comments represents a list of comments.
type Comments []string

func (node Comments) Format(buf *TrackedBuffer) {
	for i, c := range node {
		buf.Fprintf("%s", c)
		if i != len(node)-1 {
			buf.Fprintf(" ")
		}
	}
}

// SelectExprs represents SELECT expressions.
type SelectExprs []SelectExpr

func (node SelectExprs) Format(buf *TrackedBuffer) {
	var prefix string
	for _, n := range node {
		buf.Fprintf("%s%v", prefix, n)
		prefix = ", "
	}
}

// SelectExpr represents a SELECT expression.
type SelectExpr interface {
	ISelectExpr()
	SQLNode
	CST
}

func (*StarExpr) ISelectExpr()    {}
func (*NonStarExpr) ISelectExpr() {}

// StarExpr defines a '*' or 'table.*' expression.
type StarExpr struct {
	DatabaseName option.String
	TableName    option.String
}

func (node *StarExpr) Format(buf *TrackedBuffer) {
	buf.Fprintf(node.DatabaseName.Map(appendDot).Else(""))
	buf.Fprintf(node.TableName.Map(appendDot).Else(""))
	buf.Fprintf("*")
}

// NonStarExpr defines a non-'*' select expr.
type NonStarExpr struct {
	Expr Expr
	As   option.String
}

var prependAs option.StringMapFunc = func(s string) string {
	return " as " + s
}

var prependSpace option.StringMapFunc = func(s string) string {
	return " " + s
}

var appendDot option.StringMapFunc = func(s string) string {
	return s + "."
}

var escape option.StringMapFunc = func(s string) string {
	if _, ok := keywords[strings.ToLower(s)]; ok {
		return "`" + s + "`"
	}
	return s
}

func (node *NonStarExpr) Format(buf *TrackedBuffer) {
	buf.Fprintf("%v", node.Expr)
	buf.Fprintf(node.As.Map(prependAs).Else(""))
}

// Columns represents an insert column list.
// The syntax for Columns is a subset of SelectExprs.
// So, it's castable to a SelectExprs and can be analyzed
// as such.
type Columns []SelectExpr

func (node Columns) Format(buf *TrackedBuffer) {
	if node == nil {
		return
	}
	buf.Fprintf("(%v)", SelectExprs(node))
}

// ColumnExprs represents a list of column names.
type ColumnExprs []*ColName

func (node ColumnExprs) Format(buf *TrackedBuffer) {
	var prefix string
	for _, n := range node {
		buf.Fprintf("%s%v", prefix, n)
		prefix = ", "
	}
}

// TableExprs represents a list of table expressions.
type TableExprs []TableExpr

func (node TableExprs) Format(buf *TrackedBuffer) {
	var prefix string
	for _, n := range node {
		buf.Fprintf("%s%v", prefix, n)
		prefix = ", "
	}
}

// TableExpr represents a table expression.
type TableExpr interface {
	ITableExpr()
	SQLNode
	CST
}

func (*AliasedTableExpr) ITableExpr() {}
func (*DualTableExpr) ITableExpr()    {}
func (*ParenTableExpr) ITableExpr()   {}
func (*JoinTableExpr) ITableExpr()    {}

// AliasedTableExpr represents a table expression
// coupled with an optional alias or index hint.
type AliasedTableExpr struct {
	Expr  SimpleTableExpr
	As    option.String
	Hints *IndexHints
}

func (node *AliasedTableExpr) Format(buf *TrackedBuffer) {
	buf.Fprintf("%v", node.Expr)
	buf.Fprintf(node.As.Map(prependAs).Else(""))
	if node.Hints != nil {
		// Hint node provides the space padding.
		buf.Fprintf("%v", node.Hints)
	}
}

// SimpleTableExpr represents a simple table expression.
type SimpleTableExpr interface {
	ISimpleTableExpr()
	SQLNode
	CST
}

func (*TableName) ISimpleTableExpr()     {}
func (*Subquery) ISimpleTableExpr()      {}
func (*DualTableExpr) ISimpleTableExpr() {}

// TableName represents a table  name.
type TableName struct {
	Qualifier option.String
	Name      string
}

func (node *TableName) Format(buf *TrackedBuffer) {
	buf.Fprintf(node.Qualifier.Map(escape).Map(appendDot).Else(""))
	buf.Fprintf(escape(node.Name))
}

// ParenTableExpr represents a parenthesized TableExpr.
type ParenTableExpr struct {
	Expr TableExpr
}

func (node *ParenTableExpr) Format(buf *TrackedBuffer) {
	buf.Fprintf("(%v)", node.Expr)
}

// JoinTableExpr represents a TableExpr that's a JOIN operation.
type JoinTableExpr struct {
	LeftExpr  TableExpr
	Join      string
	RightExpr TableExpr
	On        Expr
	Using     ColumnExprs
}

// JoinTableExpr.Join
const (
	AST_JOIN               = "join"
	AST_STRAIGHT_JOIN      = "straight_join"
	AST_LEFT_JOIN          = "left join"
	AST_RIGHT_JOIN         = "right join"
	AST_CROSS_JOIN         = "cross join"
	AST_NATURAL_JOIN       = "natural join"
	AST_NATURAL_LEFT_JOIN  = "natural left join"
	AST_NATURAL_RIGHT_JOIN = "natural right join"
)

func (node *JoinTableExpr) Format(buf *TrackedBuffer) {
	buf.Fprintf("%v %s %v", node.LeftExpr, node.Join, node.RightExpr)
	if node.On != nil {
		buf.Fprintf(" on %v", node.On)
	}
	if node.Using != nil {
		buf.Fprintf(" using (%v)", node.Using)
	}
}

// IndexHints represents a list of index hints.
type IndexHints struct {
	Type    string
	Indexes []string
}

const (
	AST_USE    = "use"
	AST_IGNORE = "ignore"
	AST_FORCE  = "force"
)

func (node *IndexHints) Format(buf *TrackedBuffer) {
	buf.Fprintf(" %s index ", node.Type)
	prefix := "("
	for _, n := range node.Indexes {
		buf.Fprintf("%s%s", prefix, n)
		prefix = ", "
	}
	buf.Fprintf(")")
}

// Where represents a WHERE or HAVING clause.
type Where struct {
	Type string
	Expr Expr
}

// Where.Type
const (
	AST_WHERE  = "where"
	AST_HAVING = "having"
)

// NewWhere creates a WHERE or HAVING clause out
// of an Expr. If the expression is nil, it returns nil.
func NewWhere(typ string, expr Expr) *Where {
	if expr == nil {
		return nil
	}
	return &Where{Type: typ, Expr: expr}
}

func (node *Where) Format(buf *TrackedBuffer) {
	if node == nil {
		return
	}
	buf.Fprintf(" %s %v", node.Type, node.Expr)
}

// Expr represents an expression.
type Expr interface {
	IExpr()
	SQLNode
	CST
}

func (*AndExpr) IExpr()        {}
func (*OrExpr) IExpr()         {}
func (*XorExpr) IExpr()        {}
func (*NotExpr) IExpr()        {}
func (*ComparisonExpr) IExpr() {}
func (*LikeExpr) IExpr()       {}
func (*RegexExpr) IExpr()      {}
func (*RLikeExpr) IExpr()      {}
func (*RangeCond) IExpr()      {}
func (*ExistsExpr) IExpr()     {}
func (*DateVal) IExpr()        {}
func (StrVal) IExpr()          {}
func (NumVal) IExpr()          {}
func (ValArg) IExpr()          {}
func (KeywordVal) IExpr()      {}
func (*NullVal) IExpr()        {}
func (*ColName) IExpr()        {}
func (*TrueVal) IExpr()        {}
func (*FalseVal) IExpr()       {}
func (*UnknownVal) IExpr()     {}
func (ValTuple) IExpr()        {}
func (*Subquery) IExpr()       {}
func (*BinaryExpr) IExpr()     {}
func (*UnaryExpr) IExpr()      {}
func (*FuncExpr) IExpr()       {}
func (*CaseExpr) IExpr()       {}

// AndExpr represents an AND expression.
type AndExpr struct {
	Left, Right Expr
}

func (node *AndExpr) Format(buf *TrackedBuffer) {
	buf.Fprintf("%v and %v", node.Left, node.Right)
}

// OrExpr represents an OR expression.
type OrExpr struct {
	Left, Right Expr
}

func (node *OrExpr) Format(buf *TrackedBuffer) {
	buf.Fprintf("%v or %v", node.Left, node.Right)
}

// XorExpr represents an XOR expression.
type XorExpr struct {
	Left, Right Expr
}

func (node *XorExpr) Format(buf *TrackedBuffer) {
	buf.Fprintf("%v xor %v", node.Left, node.Right)
}

// NotExpr represents a NOT expression.
type NotExpr struct {
	Expr Expr
}

func (node *NotExpr) Format(buf *TrackedBuffer) {
	buf.Fprintf("not %v", node.Expr)
}

// ComparisonExpr represents a two-value comparison expression.
type ComparisonExpr struct {
	Operator         string
	Left, Right      Expr
	SubqueryOperator string
}

// ComparisonExpr.Operator
const (
	AST_EQ     = "="
	AST_LT     = "<"
	AST_GT     = ">"
	AST_LE     = "<="
	AST_GE     = ">="
	AST_NE     = "!="
	AST_NSE    = "<=>"
	AST_IN     = "in"
	AST_NOT_IN = "not in"
	AST_IS     = "is"
	AST_IS_NOT = "is not"
)

// ComparisonExpr.SubqueryOperator
const (
	AST_ALL  = "all"
	AST_ANY  = "any"
	AST_SOME = "some"
)

func (node *ComparisonExpr) Format(buf *TrackedBuffer) {
	buf.Fprintf("%v %s", node.Left, node.Operator)
	if node.SubqueryOperator != "" && node.SubqueryOperator != node.Operator {
		buf.Fprintf(" %s", node.SubqueryOperator)
	}
	buf.Fprintf(" %v", node.Right)
}

// LikeExpr.Operator
const (
	AST_LIKE            = "like"
	AST_LIKE_BINARY     = "like binary"
	AST_NOT_LIKE        = "not like"
	AST_NOT_LIKE_BINARY = "not like binary"
)

// LikeExpr represents a two-value comparison expression.
type LikeExpr struct {
	Operator    string
	Left, Right Expr
	Escape      Expr
}

func (node *LikeExpr) Format(buf *TrackedBuffer) {
	switch typedN := node.Escape.(type) {
	case StrVal:
		if string(typedN) == "\\" {
			buf.Fprintf("%v %s %v", node.Left, node.Operator, node.Right)
			return
		}
	}
	buf.Fprintf("%v %s %v escape %v", node.Left, node.Operator, node.Right, node.Escape)
}

// RangeCond represents a BETWEEN or a NOT BETWEEN expression.
type RangeCond struct {
	Operator string
	Left     Expr
	From, To Expr
}

// RangeCond.Operator
const (
	AST_BETWEEN     = "between"
	AST_NOT_BETWEEN = "not between"
)

func (node *RangeCond) Format(buf *TrackedBuffer) {
	buf.Fprintf("%v %s from %v to %v", node.Left, node.Operator, node.From, node.To)
}

// RegexExpr represents a Regex expression that matches a pattern with an expression.
type RegexExpr struct {
	Operand Expr
	Pattern Expr
}

// RLikeExpr is equivalent to RegexExpr. It is implemented separately so that
// there can be a distinction between the input commands when formatted.
type RLikeExpr struct {
	Operand Expr
	Pattern Expr
}

func (node *RegexExpr) Format(buf *TrackedBuffer) {
	buf.Fprintf("%v regexp %v", node.Operand, node.Pattern)
}

func (node *RLikeExpr) Format(buf *TrackedBuffer) {
	buf.Fprintf("%v rlike %v", node.Operand, node.Pattern)
}

// ExistsExpr represents an EXISTS expression.
type ExistsExpr struct {
	Subquery *Subquery
}

func (node *ExistsExpr) Format(buf *TrackedBuffer) {
	buf.Fprintf("exists %v", node.Subquery)
}

// DateVal represents a date literal.
type DateVal struct {
	Name string
	Val  string
}

const (
	AST_DATE      = "date"
	AST_TIME      = "time"
	AST_TIMESTAMP = "timestamp"
	AST_DATETIME  = "datetime"
)

func (node *DateVal) Format(buf *TrackedBuffer) {
	buf.Fprintf("%s '%s'", node.Name, node.Val)
}

// StrVal represents a string value.
type StrVal string

func (node StrVal) Format(buf *TrackedBuffer) {
	s := sqltypes.MakeString([]byte(node))
	s.EncodeSql(buf)
}

// NumVal represents a number.
type NumVal string

func (node NumVal) Format(buf *TrackedBuffer) {
	buf.Fprintf("%s", []byte(node))
}

// ValArg represents a named bind var argument.
type ValArg string

func (node ValArg) Format(buf *TrackedBuffer) {
	buf.WriteArg(string(node[1:]))
}

// necessary so keywords aren't quoted in output of SQL query
// (i.e. the output column from SELECT TIMESTAMPADD(YEAR, 1, DATE "2006-01-02")
// should be TIMESTAMPADD(YEAR, 1, DATE "2006-01-02") and not TIMESTAMPADD('YEAR', 1, DATE "2006-01-02"))
type KeywordVal string

func (node KeywordVal) Format(buf *TrackedBuffer) {
	buf.Fprintf("%s", []byte(node))
}

// NullVal represents a NULL value.
type NullVal struct{}

func (node *NullVal) Format(buf *TrackedBuffer) {
	buf.Fprintf("null")
}

// TrueVal represents a TRUE value.
type TrueVal struct{}

func (node *TrueVal) Format(buf *TrackedBuffer) {
	buf.Fprintf("true")
}

// FalseVal represents a FALSE value.
type FalseVal struct{}

func (node *FalseVal) Format(buf *TrackedBuffer) {
	buf.Fprintf("false")
}

// UnknownVal represents a UNKNOWN value.
type UnknownVal struct{}

func (node *UnknownVal) Format(buf *TrackedBuffer) {
	buf.Fprintf("unknown")
}

// ColName represents a column name.
type ColName struct {
	Database, Qualifier option.String
	Name                string
}

func (node *ColName) Format(buf *TrackedBuffer) {
	buf.Fprintf(node.Database.Map(escape).Map(appendDot).Else(""))
	buf.Fprintf(node.Qualifier.Map(escape).Map(appendDot).Else(""))
	buf.Fprintf(escape(node.Name))
}

// Tuple represents a tuple. It can be ValTuple, Subquery.
type Tuple interface {
	ITuple()
	Expr
}

func (ValTuple) ITuple()  {}
func (*Subquery) ITuple() {}

// ValTuple represents a tuple of actual values.
type ValTuple Exprs

func (node ValTuple) Format(buf *TrackedBuffer) {
	buf.Fprintf("(%v)", Exprs(node))
}

// Exprs represents a list of value expressions.
// It's not a valid expression because it's not parenthesized.
type Exprs []Expr

func (node Exprs) Format(buf *TrackedBuffer) {
	var prefix string
	for _, n := range node {
		buf.Fprintf("%s%v", prefix, n)
		prefix = ", "
	}
}

// Subquery represents a subquery.
type Subquery struct {
	Select    SelectStatement
	IsDerived bool
}

func (node *Subquery) Format(buf *TrackedBuffer) {
	buf.Fprintf("(%v)", node.Select)
}

// DualTableExpr represents a DUAL table, which has different semantics from
// typical table expressions and is not a true table in MySQL.
type DualTableExpr struct{}

func (node *DualTableExpr) Format(buf *TrackedBuffer) {
	buf.Fprintf("DUAL")
}

// BinaryExpr represents a binary value expression.
type BinaryExpr struct {
	Operator    string
	Left, Right Expr
}

// BinaryExpr.Operator
const (
	AST_BITAND = "&"
	AST_BITOR  = "|"
	AST_BITXOR = "^"
	AST_PLUS   = "+"
	AST_MINUS  = "-"
	AST_MULT   = "*"
	AST_DIV    = "/"
	AST_IDIV   = "div"
	AST_MOD    = "%"
)

func (node *BinaryExpr) Format(buf *TrackedBuffer) {
	if node.Operator == AST_IDIV {
		buf.Fprintf("%v div %v", node.Left, node.Right)
	} else {
		buf.Fprintf("%v%s%v", node.Left, node.Operator, node.Right)
	}
}

// UnaryExpr represents a unary value expression.
type UnaryExpr struct {
	Operator byte
	Expr     Expr
}

// UnaryExpr.Operator
const (
	AST_UPLUS  = '+'
	AST_UMINUS = '-'
	AST_TILDA  = '~'
)

func (node *UnaryExpr) Format(buf *TrackedBuffer) {
	buf.Fprintf("%c%v", node.Operator, node.Expr)
}

// FuncExpr represents a function call.
type FuncExpr struct {
	Name      string
	Distinct  bool
	Exprs     SelectExprs
	OrderBy   OrderBy
	Separator option.String
}

func (node *FuncExpr) Format(buf *TrackedBuffer) {
	var distinct, separator string
	if node.Distinct {
		distinct = "distinct "
	}

	if node.Separator.IsSome() {
		separator = ` separator "` + node.Separator.Unwrap() + `"`
	}
	buf.Fprintf(
		"%s(%s%v%v%s)", node.Name,
		distinct, node.Exprs, node.OrderBy, separator,
	)
}

// CaseExpr represents a CASE expression.
type CaseExpr struct {
	Expr  Expr
	Whens Whens
	Else  Expr
}

func (node *CaseExpr) Format(buf *TrackedBuffer) {
	buf.Fprintf("case ")
	if node.Expr != nil {
		buf.Fprintf("%v ", node.Expr)
	}
	buf.Fprintf("%v ", node.Whens)
	if node.Else != nil {
		buf.Fprintf("else %v ", node.Else)
	}
	buf.Fprintf("end")
}

type Whens []*When

func (w Whens) Format(buf *TrackedBuffer) {
	for _, when := range w {
		buf.Fprintf("%v ", when)
	}
}

// When represents a WHEN sub-expression.
type When struct {
	Cond Expr
	Val  Expr
}

func (node *When) Format(buf *TrackedBuffer) {
	buf.Fprintf("when %v then %v", node.Cond, node.Val)
}

// GroupBy represents a GROUP BY clause.
type GroupBy []Expr

func (node GroupBy) Format(buf *TrackedBuffer) {
	prefix := " group by "
	for _, n := range node {
		buf.Fprintf("%s%v", prefix, n)
		prefix = ", "
	}
}

// OrderBy represents an ORDER By clause.
type OrderBy []*Order

func (node OrderBy) Format(buf *TrackedBuffer) {
	prefix := " order by "
	for _, n := range node {
		buf.Fprintf("%s%v", prefix, n)
		prefix = ", "
	}
}

// Order represents an ordering expression.
type Order struct {
	Expr      Expr
	Direction string
}

// Order.Direction
const (
	AST_ASC  = "asc"
	AST_DESC = "desc"
)

func (node *Order) Format(buf *TrackedBuffer) {
	buf.Fprintf("%v %s", node.Expr, node.Direction)
}

// Limit represents a LIMIT clause.
type Limit struct {
	Offset, Rowcount Expr
}

func (node *Limit) Format(buf *TrackedBuffer) {
	if node == nil {
		return
	}
	buf.Fprintf(" limit ")
	if node.Offset != nil {
		buf.Fprintf("%v, ", node.Offset)
	}
	buf.Fprintf("%v", node.Rowcount)
}

// UpdateExprs represents a list of update expressions.
type UpdateExprs []*UpdateExpr

func (node UpdateExprs) Format(buf *TrackedBuffer) {
	var prefix string
	for _, n := range node {
		buf.Fprintf("%s%v", prefix, n)
		prefix = ", "
	}
}

// UpdateExpr represents an update expression.
type UpdateExpr struct {
	Name *ColName
	Expr Expr
}

func (node *UpdateExpr) Format(buf *TrackedBuffer) {
	buf.Fprintf("%v = %v", node.Name, node.Expr)
}

const (
	AST_SHOW_NO_MOD   = ""
	AST_SHOW_FULL     = "full"
	AST_SESSION_SCOPE = "session"
	AST_GLOBAL_SCOPE  = "global"
)

type Show struct {
	Section     string
	Key         string
	From        Expr
	LikeOrWhere Expr
	Modifier    string
}

func (*Show) IStatement() {}

func (node *Show) Format(buf *TrackedBuffer) {
	buf.Fprintf("show %s %s", node.Section, node.Key)
	if node.From != nil {
		buf.Fprintf(" %v", node.From)
	}
	if node.LikeOrWhere != nil {
		buf.Fprintf(" %v", node.LikeOrWhere)
	}
}

const (
	AST_EXPLAIN_EXTENDED           = "extended"
	AST_EXPLAIN_FORMAT_JSON        = "json"
	AST_EXPLAIN_FORMAT_TRADITIONAL = "traditional"
	AST_EXPLAIN_PARTITIONS         = "partitions"
)

type Explain struct {
	Section     string
	Table       *TableName
	Column      *ColName
	ExplainType string
	Connection  option.String
	Statement   Statement
}

func (*Explain) IStatement() {}

func (node *Explain) Format(buf *TrackedBuffer) {
	buf.Fprintf("explain %v %v", node.Table, node.Column)
}

const (
	AST_KILL_CONNECTION = "connection"
	AST_KILL_QUERY      = "query"
)

func (*Kill) IStatement() {}

type Kill struct {
	Scope string
	ID    Expr
}

func (node *Kill) Format(buf *TrackedBuffer) {
	buf.Fprintf("kill %s %v", node.Scope, node.ID)
}

func (*Flush) IStatement() {}

type FlushKind string

const (
	FlushLogs   = "logs"
	FlushSample = "sample"
)

type Flush struct {
	Kind FlushKind
}

func (f *Flush) Format(buf *TrackedBuffer) {
	buf.Fprintf("flush %s", string(f.Kind))
}

type AlterTable struct {
	Table *TableName
	Specs AlterSpecs
}

func (*AlterTable) IStatement() {}

func (node *AlterTable) Format(buf *TrackedBuffer) {
	buf.Fprintf("alter table %s %v", node.Table.Name, node.Specs)
}

const (
	AltRenameColumn = "rename_column"
	AltDropColumn   = "drop_column"
	AltModifyColumn = "modify_column"
	AltRenameTable  = "rename_table"
)

type AlterSpec struct {
	Type          string
	Column        *ColName
	NewColumn     *ColName
	NewTable      *TableName
	NewColumnType string
}

func (node *AlterSpec) Format(buf *TrackedBuffer) {
	switch node.Type {
	case AltRenameColumn:
		buf.Fprintf("change column %s %s", node.Column.Name, node.NewColumn.Name)
	case AltDropColumn:
		buf.Fprintf("drop column %s", node.Column.Name)
	case AltModifyColumn:
		buf.Fprintf("change column %s %s", node.Column.Name, node.NewColumnType)
	case AltRenameTable:
		buf.Fprintf("rename to %s", node.NewTable.Name)
	default:
		buf.Fprintf("unknown %q", node.NewTable.Name)
	}
}

type AlterSpecs []*AlterSpec

func (node AlterSpecs) Format(buf *TrackedBuffer) {
	buf.Fprintf("%v", node[0])
	for _, spec := range node[1:] {
		buf.Fprintf(", %v", spec)
	}
}

type RenameTable struct {
	Renames RenameSpecs
}

func (*RenameTable) IStatement() {}

func (node *RenameTable) Format(buf *TrackedBuffer) {
	buf.Fprintf("rename table %s", node.Renames)
}

type RenameSpec struct {
	Table    *TableName
	NewTable *TableName
}

func (node *RenameSpec) Format(buf *TrackedBuffer) {
	buf.Fprintf("%s to %s", node.Table.Name, node.NewTable.Name)
}

type RenameSpecs []*RenameSpec

func (node RenameSpecs) Format(buf *TrackedBuffer) {
	buf.Fprintf("%s", node[0])
	for _, rn := range node[1:] {
		buf.Fprintf(", %s", rn)
	}
}
