package parser

import (
	"github.com/10gen/sqlproxy/internal/mysqlerrors"
)

// DesugarQuery is a compiler phase that occurs after parsing and before
// algebrization. This phase converts a CST from its input form to an equivalent
// simpler from. Constructs that exist in the input can be wholly removed in the
// output. Operations in this phase should be simple. CSTs leave the deeper
// structure of the query obfuscated and no attempt to uncover it should be made.
func DesugarQuery(statement Statement) (Statement, error) {
	result, err := walk(&unwrapSingleTuples{}, statement)
	if err != nil {
		return nil, err
	}

	result, err = walk(&inListConverter{}, result)
	if err != nil {
		return nil, err
	}

	result, err = walk(&detupler{}, result)
	if err != nil {
		return nil, err
	}

	return result.(Statement), nil
}

// unwrapSingleTuples is a desugarer that removes single-element tuples
// generated by the parser. Desugarers orchestrates a desugaring phase on the
// CST by implementing the walker interface.
type unwrapSingleTuples struct{}

// PreVisit is called for every node before its children are walked.
func (*unwrapSingleTuples) PreVisit(current CST) (CST, error) {
	return current, nil
}

// PostVisit is called for every node after its children are walked.
func (*unwrapSingleTuples) PostVisit(current CST) (CST, error) {
	return detupleWrappedExpr(current), nil
}

var _ walker = (*unwrapSingleTuples)(nil)

// detupleWrappedExpr removes tuples that were placed around expressions in the
// parser where parentheses existed.
//
// Note: This should not be necessary. However, our parser interprets every set
// of parentheses (even those in arithmetic exprs, for example) as a tuple, so
// we need to get rid of them.
func detupleWrappedExpr(node CST) CST {
	if tuple, isTuple := node.(ValTuple); isTuple && len(tuple) == 1 {
		return tuple[0]
	}
	return node
}

// inListConverter is a desugarer that breakes IN lists into boolean
// comparisons.
// Desugarers orchestrates a desugaring phase on the CST by implementing
// the walker interface.
type inListConverter struct{}

// PreVisit is called for every node before its children are walked. PreVisit
// desugars NOT IN nodes to IN nodes, which will themselves be desugared further
// in the PostVisit function.
func (*inListConverter) PreVisit(current CST) (CST, error) {
	if node, isComp := current.(*ComparisonExpr); isComp {
		if node.Operator == AST_NOT_IN {
			// ignore NOT IN subquery, that is a different expression
			if _, isSub := node.Right.(*Subquery); !isSub {
				current = breakUpNotIn(node)
			}
		}
	}
	return current, nil
}

// PostVisit is called for every node after its children are walked.
func (*inListConverter) PostVisit(current CST) (CST, error) {
	if node, isComp := current.(*ComparisonExpr); isComp {
		if node.Operator == AST_IN {
			// ignore IN subquery, that is a different expression
			if _, isSub := node.Right.(*Subquery); !isSub {
				if tuple, isTuple := node.Right.(ValTuple); isTuple {
					current = inListToDisjunction(node.Left, tuple)
				} else {
					current = inListToDisjunction(node.Left, []Expr{node.Right})
				}
			}
		}
	}
	return current, nil
}

var _ walker = (*inListConverter)(nil)

// breakUpNotIn rewrites a NOT IN list expression as a boolean NOT of an IN list
// expression. NOT IN list is of the form a NOT IN (b, c...) and is expressable
// as NOT (a IN (b, c...))
func breakUpNotIn(node *ComparisonExpr) Expr {
	node.Operator = AST_IN
	return &NotExpr{node}
}

// detupleEquality rewrites an IN list expression as a disjunction by enumerating every
// equality comparison.
// IN list is of the form a in (b, c...) and is expressable as
// a = b OR a = c OR ...
func inListToDisjunction(leftExpr Expr, rightExprs ValTuple) Expr {
	var makeDisjunction func(leftExpr Expr, rightExprs ValTuple) Expr
	makeDisjunction = func(leftExpr Expr, rightExprs ValTuple) Expr {
		if len(rightExprs) == 1 {
			return &ComparisonExpr{
				AST_EQ,
				leftExpr,
				rightExprs[0],
				"",
			}
		}
		return &OrExpr{
			&ComparisonExpr{
				AST_EQ,
				leftExpr,
				rightExprs[0],
				"",
			},
			makeDisjunction(leftExpr.Copy().(Expr), rightExprs[1:]),
		}
	}
	return makeDisjunction(leftExpr, rightExprs)
}

// detupler is a desugarer that rewrites multi-element tuples into other
// expressions. The detupler also unifies the equivalent SOME and ANY subquery
// comparison modifiers. For example, the detupler will rewrite `select (a, b) <
// (c, d) from foo` as `select a < c or a = c and b < d from foo`.
type detupler struct{}

// PreVisit is called for every node before its children are walked.
func (*detupler) PreVisit(current CST) (CST, error) {
	return current, nil
}

// PostVisit is called for every node after its children are walked.
func (*detupler) PostVisit(current CST) (CST, error) {
	if node, isComp := current.(*ComparisonExpr); isComp {
		if err := SomeToAny(node); err != nil {
			return nil, err
		}

		left, leftIsTuple := node.Left.(ValTuple)
		right, rightIsTuple := node.Right.(ValTuple)

		if leftIsTuple || rightIsTuple {
			_, leftIsSubquery := node.Left.(*Subquery)
			_, rightIsSubquery := node.Right.(*Subquery)

			if leftIsSubquery {
				node.Right = detupleToSubquery(right)
			} else if rightIsSubquery {
				node.Left = detupleToSubquery(left)
			} else {
				var err error
				current, err = detupleToBooleanCompare(node)
				if err != nil {
					return nil, err
				}
			}
		}
	}
	return current, nil
}

var _ walker = (*detupler)(nil)

// SomeToAny changes SOMEs to ANYs.
// SOME and ANY are aliases of each other.
// We choose to represent them all as ANY for uniformity.
func SomeToAny(node *ComparisonExpr) error {
	if node.SubqueryOperator == AST_SOME {
		node.SubqueryOperator = AST_ANY
	}
	return nil
}

// Tuples are only legal in comparisons.
// Tuple comparisons are either equivalent to conjunctions or disjunctions
// of comparisons or subquery comparisons.
// This function handles the first case.
func detupleToBooleanCompare(node *ComparisonExpr) (Expr, error) {
	// Check outermost left side to ensure it is a tuple.
	left, leftIsTuple := node.Left.(ValTuple)
	if !leftIsTuple {
		return nil, mysqlerrors.Defaultf(mysqlerrors.ErOperandColumns, 1)
	}

	// Ensure both sides are uniform. And extract values from nests.
	var checkLengthAndExtract func(left ValTuple, rightUnchecked Expr) (Exprs, Exprs, error)
	checkLengthAndExtract = func(left ValTuple, rightUnchecked Expr) (Exprs, Exprs, error) {
		var leftExprs Exprs
		var rightExprs Exprs

		// Make sure the right hand side is a tuple first.
		right, rightIsTuple := rightUnchecked.(ValTuple)
		if !rightIsTuple {
			return nil, nil, mysqlerrors.Defaultf(mysqlerrors.ErOperandColumns, len(left))
		}

		// Make sure the lengths are the same.
		if len(left) != len(right) {
			return nil, nil, mysqlerrors.Defaultf(mysqlerrors.ErOperandColumns, len(left))
		}

		// Collect values in turn from each tuple.
		for i, leftExpr := range left {
			rightExpr := right[i]

			// Recursively descend into left side if a tuple is located.
			leftElem, innerLeftIsTuple := leftExpr.(ValTuple)
			if innerLeftIsTuple {
				leftAdditions, rightAdditions, err := checkLengthAndExtract(leftElem, rightExpr)
				if err != nil {
					return nil, nil, err
				}
				leftExprs = append(leftExprs, leftAdditions...)
				rightExprs = append(rightExprs, rightAdditions...)
			} else {
				// If the right hand side is a tuple here, it doesn't match the expression
				// on the left.
				if _, innerRightIsTuple := rightExpr.(ValTuple); innerRightIsTuple {
					return nil, nil, mysqlerrors.Defaultf(mysqlerrors.ErOperandColumns, 1)
				}
				leftExprs = append(leftExprs, leftExpr)
				rightExprs = append(rightExprs, rightExpr)
			}
		}

		return leftExprs, rightExprs, nil
	}

	leftExprs, rightExprs, err := checkLengthAndExtract(left, node.Right)
	if err != nil {
		return nil, err
	}
	switch node.Operator {
	case string(AST_EQ), string(AST_NSE):
		return detupleEquality(node.Operator, leftExprs, rightExprs), nil
	case string(AST_NE):
		eq := detupleEquality(string(AST_EQ), leftExprs, rightExprs)
		return &NotExpr{eq}, nil
	default:
		return detupleInequality(node.Operator, leftExprs, rightExprs), nil
	}
}

// detupleEquality rewrites a tuple as a conjunction by moving from the former to the later:
// Tuple equality expressions of the form (a1, b1, ...) op (a2, b2, ...) are expressable as
// a1 op a2 AND b1 op b2 AND ...
func detupleEquality(operator string, leftExprs, rightExprs Exprs) Expr {
	var makeConjunction func(operator string, leftExprs, rightExprs Exprs) Expr
	makeConjunction = func(operator string, leftExprs, rightExprs Exprs) Expr {
		if len(leftExprs) == 1 {
			return &ComparisonExpr{
				operator,
				leftExprs[0],
				rightExprs[0],
				"",
			}
		}
		return &AndExpr{
			&ComparisonExpr{
				operator,
				leftExprs[0],
				rightExprs[0],
				"",
			},
			makeConjunction(operator, leftExprs[1:], rightExprs[1:]),
		}
	}
	return makeConjunction(operator, leftExprs, rightExprs)
}

// detupleInequality rewrites a tuple as a disjunction by moving from the former to the later:
// Tuple inequality expressions of the form (a1, b1, ...) op (a2, b2, ...) are expressable as
// a1 op a2 OR (a1 = a2 AND b1 op b2 OR (...))
func detupleInequality(operator string, leftExprs, rightExprs Exprs) Expr {
	var makeDisjunction func(operator string, leftExprs, rightExprs Exprs) Expr
	makeDisjunction = func(operator string, leftExprs, rightExprs Exprs) Expr {
		if len(leftExprs) == 1 {
			return &ComparisonExpr{
				operator,
				leftExprs[0],
				rightExprs[0],
				"",
			}
		}
		return &OrExpr{
			&ComparisonExpr{
				operator,
				leftExprs[0],
				rightExprs[0],
				"",
			},
			&AndExpr{
				&ComparisonExpr{
					AST_EQ,
					leftExprs[0],
					rightExprs[0],
					"",
				},
				makeDisjunction(operator, leftExprs[1:], rightExprs[1:]),
			},
		}
	}

	switch operator {
	case string(AST_LE):
		operator = string(AST_LT)
	case string(AST_GE):
		operator = string(AST_GT)
	}

	return makeDisjunction(operator, leftExprs, rightExprs)
}

// detupleToSubquery rewrites a tuple to a subquery. Tuples are only legal in
// comparisons. Tuple comparisons are either equivalent to conjunctions or
// disjunctions of comparisons or subquery comparisons. This function handles
// the second case.
func detupleToSubquery(node ValTuple) *Subquery {
	var selExprs SelectExprs
	for _, expr := range node {
		selExprs = append(selExprs, &NonStarExpr{Expr: expr})
	}
	return &Subquery{
		&SimpleSelect{SelectExprs: selExprs},
		false,
	}
}
