[package]
name = "schema-builder-library"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "schema_builder_library"
path = "src/lib.rs"

[dependencies]
futures = "0.3.28"
mongodb = "3.1.0"
serde = "1.0.189"
tokio = { version = "1.32.0", features = ["full"] }
mongosql = { path = "../mongosql" }
schema_derivation = { path = "../agg-ast/schema_derivation" }
thiserror = "1.0.50"
lazy_static = "1.4.0"
glob = "0.3.1"
test-utils = { path = "../test-utils" }
tracing = "0.1"

[features]
integration = []

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
