[package]
name = "schema-builder-library"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "schema_builder_library"
path = "src/lib.rs"

[[bin]]
name = "schema-builder-data-loader"
path = "src/data-loader/main.rs"

[dependencies]
crossbeam = { version = "0.8.2", features = ["crossbeam-channel"] }
futures = "0.3.28"
mongodb = "3.0.1"
serde = "1.0.189"
serde_json = "1.0.107"
tokio = { version = "1.32.0", features = ["full"] }
mongosql = { path = "../mongosql" }
anyhow = "1.0.75"
tokio-util = { version = "0.7.8" }
thiserror = "1.0.50"
lazy_static = "1.4.0"
glob = "0.3.1"
tracing = "0.1"
fake = "2"
rand = "0.8.5"

[features]
integration = []
