package data

import (
	toolsoptions "github.com/mongodb/mongo-tools-common/options"
	"go.mongodb.org/mongo-driver/bson"
)

// A DynamicDataset is a function that generates rows of data to be
// restored to MongoDB.
type DynamicDataset func() (string, map[string][]bson.D)

// Restore restores the data generated by this function to the MongoDB
// deployment to the MongoDB deployment specified in the provided options.
func (d DynamicDataset) Restore(opts *toolsoptions.ToolOptions) error {
	db, namespaces := d()

	for col, docs := range namespaces {
		inmem := &InMemoryDataset{
			Db:         db,
			Collection: col,
			Docs:       docs,
		}
		err := inmem.Restore(opts)
		if err != nil {
			return err
		}
	}

	return nil
}
