[package]
name = "bic-trip"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "bic-trip"
path = "src/main.rs"

[lib]
name = "report"
path = "src/report/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

mongodb = { version = "2.8.1", features = ["tokio-runtime"] }
build_html = "2.4.0"
mongosql = { path = "../mongosql" }
clap = "4.4.18"
rpassword = "7.3.1"
chrono = { version = "0.4.33", features = ["serde"] }
dialoguer = "0.11.0"
csv = "1.3.0"
serde = { version = "1.0.196", features = ["derive"] }
sampler = { path = "../sampler" }
tokio = { version = "1.36.0", features = ["full"] }
anyhow = "1.0.80"
sqlformat = "0.2.3"
base64 = "0.21.7"
image = "0.24.7"
