[package]
name = "oidc"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0", features = ["blocking"] }
mongodb = { workspace = true }
tokio = { version = "1", features = ["full"] }
openidconnect = "3"
open = "5"
actix-web = "4"
askama = "0"
once_cell = "1"
