package collation

import (
	"fmt"

	"github.com/10gen/sqlproxy/internal/mysqlerrors"

	"golang.org/x/text/collate"
	"golang.org/x/text/language"
)

const defaultCollationName = Name("utf8_bin")

func init() {
	collationByID = make(map[ID]*Collation)
	collationByName = make(map[Name]*Collation)

	for _, collation := range collations {
		collationByName[collation.Name] = collation
		collationByID[collation.ID] = collation
	}

	Default = Must(Get(defaultCollationName))
	DefaultCharset = MustCharset(GetCharset(Default.CharsetName))
	NullCharset = &Charset{
		Name:                 CharsetName(""),
		DefaultCollationName: defaultCollationName,
		Description:          DefaultCharset.Description,
		MaxLen:               DefaultCharset.MaxLen,
		encoding:             DefaultCharset.encoding,
	}
}

var collationByID map[ID]*Collation
var collationByName map[Name]*Collation

// Default is the default Collation.
var Default *Collation

// Name is the name of a collation.
type Name string

// ID is the identifier of a collation.
type ID uint8

// Collation defines a collation.
type Collation struct {
	binary           bool
	language         language.Tag
	ignoreCase       bool
	ignoreDiacritics bool
	ignoreWidth      bool
	collator         *collate.Collator

	// SortLen is related to the amount of memory
	// required to sort strings expressed in
	// collation's character set.
	SortLen uint8
	// Name is the name of the collation.
	Name Name
	// ID is the id of the collation.
	ID ID
	// Default indicates if this collation is the default for its character set.
	Default bool
	// CharsetName indicates the default character set for this collation.
	CharsetName CharsetName
}

// NewCollation is a constructor for Collation.
func NewCollation(t language.Tag, collator *collate.Collator, ignoreCase bool,
	ignoreDiacritics bool, ignoreWidth bool, charsetName CharsetName, sortLen uint8) *Collation {

	return &Collation{
		language:         t,
		collator:         collator,
		ignoreCase:       ignoreCase,
		ignoreDiacritics: ignoreDiacritics,
		ignoreWidth:      ignoreWidth,
		CharsetName:      charsetName,
		SortLen:          sortLen,
	}
}

func (c *Collation) ensureCollator() {
	if c.collator != nil {
		return
	}

	opts := []collate.Option{collate.OptionsFromTag(c.language)}
	if c.ignoreCase {
		opts = append(opts, collate.IgnoreCase)
	}
	if c.ignoreDiacritics {
		opts = append(opts, collate.IgnoreDiacritics)
	}
	if c.ignoreWidth {
		opts = append(opts, collate.IgnoreWidth)
	}

	c.collator = collate.New(c.language, opts...)
}

// CompareString returns an integer comparing the two strings. The result will
// be 0 if a==b, -1 if a < b, and +1 if a > b.
func (c *Collation) CompareString(a, b string) int {

	if c.binary {
		if a == b {
			return 0
		}
		if a < b {
			return -1
		}
		return +1
	}

	c.ensureCollator()
	return c.collator.CompareString(a, b)
}

// KeyBuffer holds keys generated by KeyFromString.
type KeyBuffer struct {
	buffer collate.Buffer
}

// Reset resets the buffer back to its original state.
func (b *KeyBuffer) Reset() {
	(&b.buffer).Reset()
}

// KeyFromString returns the collation key for s. Passing the buffer b may
// avoid memory allocations. The returned string will point to an allocation
// in KeyBuffer and will remain valid until the next call to b.Reset().
func (c *Collation) KeyFromString(b *KeyBuffer, s string) string {
	if c.binary {
		return s
	}

	c.ensureCollator()
	keyBytes := c.collator.KeyFromString(&b.buffer, s)
	return string(keyBytes)
}

// GetAll gets all available collations.
func GetAll() []*Collation {
	return collations
}

// Get gets a collation by its name.
func Get(name Name) (*Collation, error) {
	collation, ok := collationByName[name]
	if !ok {
		return nil, mysqlerrors.Defaultf(
			mysqlerrors.ErUnknownCollation,
			fmt.Sprintf("name(%v)", name),
		)
	}

	return collation, nil
}

// GetByID gets a collation by its id.
func GetByID(id ID) (*Collation, error) {
	collation, ok := collationByID[id]
	if !ok {
		return nil, mysqlerrors.Defaultf(mysqlerrors.ErUnknownCollation, fmt.Sprintf("id(%v)", id))
	}

	return collation, nil
}

// Must gets a Collation or panics.
func Must(cs *Collation, err error) *Collation {
	if err != nil {
		panic("internal error: " + err.Error())
	}

	return cs
}
