package collation

import (
	"golang.org/x/text/encoding"
	"golang.org/x/text/encoding/charmap"
	"golang.org/x/text/encoding/japanese"
	"golang.org/x/text/encoding/korean"
	"golang.org/x/text/encoding/simplifiedchinese"
	"golang.org/x/text/encoding/traditionalchinese"
	"golang.org/x/text/encoding/unicode"
	"golang.org/x/text/encoding/unicode/utf32"
	"golang.org/x/text/language"
)

// charsets is the list of all character sets.
var charsets = []*Charset{
	{Name: "big5", DefaultCollationName: "big5_chinese_ci", Description: "Big5 Traditional Chinese", MaxLen: 2},
	{Name: "dec8", DefaultCollationName: "dec8_swedish_ci", Description: "DEC West European", MaxLen: 1},
	{Name: "cp850", DefaultCollationName: "cp850_general_ci", Description: "DOS West European", MaxLen: 1},
	{Name: "hp8", DefaultCollationName: "hp8_english_ci", Description: "HP West European", MaxLen: 1},
	{Name: "koi8r", DefaultCollationName: "koi8r_general_ci", Description: "KOI8-R Relcom Russian", MaxLen: 1},
	{Name: "latin1", DefaultCollationName: "latin1_swedish_ci", Description: "cp1252 West European", MaxLen: 1},
	{Name: "latin2", DefaultCollationName: "latin2_general_ci", Description: "ISO 8859-2 Central European", MaxLen: 1},
	{Name: "swe7", DefaultCollationName: "swe7_swedish_ci", Description: "7bit Swedish", MaxLen: 1},
	{Name: "ascii", DefaultCollationName: "ascii_general_ci", Description: "US ASCII", MaxLen: 1},
	{Name: "ujis", DefaultCollationName: "ujis_japanese_ci", Description: "EUC-JP Japanese", MaxLen: 3},
	{Name: "sjis", DefaultCollationName: "sjis_japanese_ci", Description: "Shift-JIS Japanese", MaxLen: 2},
	{Name: "hebrew", DefaultCollationName: "hebrew_general_ci", Description: "ISO 8859-8 Hebrew", MaxLen: 1},
	{Name: "tis620", DefaultCollationName: "tis620_thai_ci", Description: "TIS620 Thai", MaxLen: 1},
	{Name: "euckr", DefaultCollationName: "euckr_korean_ci", Description: "EUC-KR Korean", MaxLen: 2},
	{Name: "koi8u", DefaultCollationName: "koi8u_general_ci", Description: "KOI8-U Ukrainian", MaxLen: 1},
	{Name: "gb2312", DefaultCollationName: "gb2312_chinese_ci", Description: "GB2312 Simplified Chinese", MaxLen: 2},
	{Name: "greek", DefaultCollationName: "greek_general_ci", Description: "ISO 8859-7 Greek", MaxLen: 1},
	{Name: "cp1250", DefaultCollationName: "cp1250_general_ci", Description: "Windows Central European", MaxLen: 1},
	{Name: "gbk", DefaultCollationName: "gbk_chinese_ci", Description: "GBK Simplified Chinese", MaxLen: 2},
	{Name: "latin5", DefaultCollationName: "latin5_turkish_ci", Description: "ISO 8859-9 Turkish", MaxLen: 1},
	{Name: "armscii8", DefaultCollationName: "armscii8_general_ci", Description: "ARMSCII-8 Armenian", MaxLen: 1},
	{Name: "utf8", DefaultCollationName: "utf8_general_ci", Description: "UTF-8 Unicode", MaxLen: 3},
	{Name: "ucs2", DefaultCollationName: "ucs2_general_ci", Description: "UCS-2 Unicode", MaxLen: 2},
	{Name: "cp866", DefaultCollationName: "cp866_general_ci", Description: "DOS Russian", MaxLen: 1},
	{Name: "keybcs2", DefaultCollationName: "keybcs2_general_ci", Description: "DOS Kamenicky Czech-Slovak", MaxLen: 1},
	{Name: "macce", DefaultCollationName: "macce_general_ci", Description: "Mac Central European", MaxLen: 1},
	{Name: "macroman", DefaultCollationName: "macroman_general_ci", Description: "Mac West European", MaxLen: 1},
	{Name: "cp852", DefaultCollationName: "cp852_general_ci", Description: "DOS Central European", MaxLen: 1},
	{Name: "latin7", DefaultCollationName: "latin7_general_ci", Description: "ISO 8859-13 Baltic", MaxLen: 1},
	{Name: "utf8mb4", DefaultCollationName: "utf8mb4_general_ci", Description: "UTF-8 Unicode", MaxLen: 4},
	{Name: "cp1251", DefaultCollationName: "cp1251_general_ci", Description: "Windows Cyrillic", MaxLen: 1},
	{Name: "utf16", DefaultCollationName: "utf16_general_ci", Description: "UTF-16 Unicode", MaxLen: 4},
	{Name: "utf16le", DefaultCollationName: "utf16le_general_ci", Description: "UTF-16LE Unicode", MaxLen: 4},
	{Name: "cp1256", DefaultCollationName: "cp1256_general_ci", Description: "Windows Arabic", MaxLen: 1},
	{Name: "cp1257", DefaultCollationName: "cp1257_general_ci", Description: "Windows Baltic", MaxLen: 1},
	{Name: "utf32", DefaultCollationName: "utf32_general_ci", Description: "UTF-32 Unicode", MaxLen: 4},
	{Name: "binary", DefaultCollationName: "binary", Description: "Binary pseudo charset", MaxLen: 1},
	{Name: "geostd8", DefaultCollationName: "geostd8_general_ci", Description: "GEOSTD8 Georgian", MaxLen: 1},
	{Name: "cp932", DefaultCollationName: "cp932_japanese_ci", Description: "SJIS for Windows Japanese", MaxLen: 2},
	{Name: "eucjpms", DefaultCollationName: "eucjpms_japanese_ci", Description: "UJIS for Windows Japanese", MaxLen: 3},
}

var collations = []*Collation{
	{Name: "big5_chinese_ci", ID: 1, SortLen: 1, Default: true, CharsetName: "big5", language: language.TraditionalChinese, ignoreCase: true, ignoreDiacritics: true},
	{Name: "latin2_czech_cs", ID: 2, SortLen: 4, CharsetName: "latin2", language: language.Czech},
	{Name: "dec8_swedish_ci", ID: 3, SortLen: 1, Default: true, CharsetName: "dec8", language: language.Swedish, ignoreCase: true, ignoreDiacritics: true},
	{Name: "cp850_general_ci", ID: 4, SortLen: 1, Default: true, CharsetName: "cp850", language: language.Und, ignoreCase: true, ignoreDiacritics: true, ignoreWidth: true},
	{Name: "latin1_german1_ci", ID: 5, SortLen: 1, CharsetName: "latin1", language: language.German, ignoreCase: true, ignoreDiacritics: true},
	{Name: "hp8_english_ci", ID: 6, SortLen: 1, Default: true, CharsetName: "hp8", language: language.BritishEnglish, ignoreCase: true, ignoreDiacritics: true},
	{Name: "koi8r_general_ci", ID: 7, SortLen: 1, Default: true, CharsetName: "koi8r", language: language.Ukrainian, ignoreCase: true, ignoreDiacritics: true, ignoreWidth: true},
	{Name: "latin1_swedish_ci", ID: 8, SortLen: 1, Default: true, CharsetName: "latin1", language: language.Swedish, ignoreCase: true, ignoreDiacritics: true},
	{Name: "latin2_general_ci", ID: 9, SortLen: 1, Default: true, CharsetName: "latin2", language: language.Und, ignoreCase: true, ignoreDiacritics: true, ignoreWidth: true},
	{Name: "swe7_swedish_ci", ID: 10, SortLen: 1, Default: true, CharsetName: "swe7", language: language.Swedish, ignoreCase: true, ignoreDiacritics: true},
	{Name: "ascii_general_ci", ID: 11, SortLen: 1, Default: true, CharsetName: "ascii", language: language.Und, ignoreCase: true, ignoreDiacritics: true, ignoreWidth: true},
	{Name: "ujis_japanese_ci", ID: 12, SortLen: 1, Default: true, CharsetName: "ujis", language: language.Japanese, ignoreCase: true, ignoreDiacritics: true},
	{Name: "sjis_japanese_ci", ID: 13, SortLen: 1, Default: true, CharsetName: "sjis", language: language.Japanese, ignoreCase: true, ignoreDiacritics: true},
	{Name: "cp1251_bulgarian_ci", ID: 14, SortLen: 1, CharsetName: "cp1251", language: language.Bulgarian, ignoreCase: true, ignoreDiacritics: true},
	{Name: "latin1_danish_ci", ID: 15, SortLen: 1, CharsetName: "latin1", language: language.Danish, ignoreCase: true, ignoreDiacritics: true},
	{Name: "hebrew_general_ci", ID: 16, SortLen: 1, Default: true, CharsetName: "hebrew", language: language.Und, ignoreCase: true, ignoreDiacritics: true, ignoreWidth: true},
	{Name: "tis620_thai_ci", ID: 18, SortLen: 4, Default: true, CharsetName: "tis620", language: language.Thai, ignoreCase: true, ignoreDiacritics: true},
	{Name: "euckr_korean_ci", ID: 19, SortLen: 1, Default: true, CharsetName: "euckr", language: language.Korean, ignoreCase: true, ignoreDiacritics: true},
	{Name: "latin7_estonian_cs", ID: 20, SortLen: 1, CharsetName: "latin7", language: language.Estonian},
	{Name: "latin2_hungarian_ci", ID: 21, SortLen: 1, CharsetName: "latin2", language: language.Hungarian, ignoreCase: true, ignoreDiacritics: true},
	{Name: "koi8u_general_ci", ID: 22, SortLen: 1, Default: true, CharsetName: "koi8u", language: language.Und, ignoreCase: true, ignoreDiacritics: true, ignoreWidth: true},
	{Name: "cp1251_ukrainian_ci", ID: 23, SortLen: 1, CharsetName: "cp1251", language: language.Ukrainian, ignoreCase: true, ignoreDiacritics: true},
	{Name: "gb2312_chinese_ci", ID: 24, SortLen: 1, Default: true, CharsetName: "gb2312", language: language.SimplifiedChinese, ignoreCase: true, ignoreDiacritics: true},
	{Name: "greek_general_ci", ID: 25, SortLen: 1, Default: true, CharsetName: "greek", language: language.Und, ignoreCase: true, ignoreDiacritics: true, ignoreWidth: true},
	{Name: "cp1250_general_ci", ID: 26, SortLen: 1, Default: true, CharsetName: "cp1250", language: language.Und, ignoreCase: true, ignoreDiacritics: true, ignoreWidth: true},
	{Name: "latin2_croatian_ci", ID: 27, SortLen: 1, CharsetName: "latin2", language: language.Croatian, ignoreCase: true, ignoreDiacritics: true},
	{Name: "gbk_chinese_ci", ID: 28, SortLen: 1, Default: true, CharsetName: "gbk", language: language.SimplifiedChinese, ignoreCase: true, ignoreDiacritics: true},
	{Name: "cp1257_lithuanian_ci", ID: 29, SortLen: 1, CharsetName: "cp1257", language: language.Lithuanian, ignoreCase: true, ignoreDiacritics: true},
	{Name: "latin5_turkish_ci", ID: 30, SortLen: 1, Default: true, CharsetName: "latin5", language: language.Turkish, ignoreCase: true, ignoreDiacritics: true},
	{Name: "latin1_german2_ci", ID: 31, SortLen: 2, CharsetName: "latin1", language: language.MustParse("de_AT"), ignoreCase: true, ignoreDiacritics: true},
	{Name: "armscii8_general_ci", ID: 32, SortLen: 1, Default: true, CharsetName: "armscii8", language: language.Und, ignoreCase: true, ignoreDiacritics: true, ignoreWidth: true},
	{Name: "utf8_general_ci", ID: 33, SortLen: 1, Default: true, CharsetName: "utf8", language: language.Und, ignoreCase: true, ignoreDiacritics: true, ignoreWidth: true},
	{Name: "cp1250_czech_cs", ID: 34, SortLen: 2, CharsetName: "cp1250", language: language.Czech},
	{Name: "ucs2_general_ci", ID: 35, SortLen: 1, Default: true, CharsetName: "ucs2", language: language.Und, ignoreCase: true, ignoreDiacritics: true, ignoreWidth: true},
	{Name: "cp866_general_ci", ID: 36, SortLen: 1, Default: true, CharsetName: "cp866", language: language.Und, ignoreCase: true, ignoreDiacritics: true, ignoreWidth: true},
	{Name: "keybcs2_general_ci", ID: 37, SortLen: 1, Default: true, CharsetName: "keybcs2", language: language.Und, ignoreCase: true, ignoreDiacritics: true, ignoreWidth: true},
	{Name: "macce_general_ci", ID: 38, SortLen: 1, Default: true, CharsetName: "macce", language: language.Und, ignoreCase: true, ignoreDiacritics: true, ignoreWidth: true},
	{Name: "macroman_general_ci", ID: 39, SortLen: 1, Default: true, CharsetName: "macroman", language: language.Und, ignoreCase: true, ignoreDiacritics: true, ignoreWidth: true},
	{Name: "cp852_general_ci", ID: 40, SortLen: 1, Default: true, CharsetName: "cp852", language: language.Und, ignoreCase: true, ignoreDiacritics: true, ignoreWidth: true},
	{Name: "latin7_general_ci", ID: 41, SortLen: 1, Default: true, CharsetName: "latin7", language: language.Und, ignoreCase: true, ignoreDiacritics: true, ignoreWidth: true},
	{Name: "latin7_general_cs", ID: 42, SortLen: 1, CharsetName: "latin7", language: language.Und, ignoreWidth: true},
	{Name: "macce_bin", ID: 43, SortLen: 1, CharsetName: "macce", binary: true},
	{Name: "cp1250_croatian_ci", ID: 44, SortLen: 1, CharsetName: "cp1250", language: language.Croatian, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf8mb4_general_ci", ID: 45, SortLen: 1, Default: true, CharsetName: "utf8mb4", language: language.Und, ignoreCase: true, ignoreDiacritics: true, ignoreWidth: true},
	{Name: "utf8mb4_bin", ID: 46, SortLen: 1, CharsetName: "utf8mb4", binary: true},
	{Name: "latin1_bin", ID: 47, SortLen: 1, CharsetName: "latin1", binary: true},
	{Name: "latin1_general_ci", ID: 48, SortLen: 1, CharsetName: "latin1", language: language.Und, ignoreCase: true, ignoreDiacritics: true, ignoreWidth: true},
	{Name: "latin1_general_cs", ID: 49, SortLen: 1, CharsetName: "latin1", language: language.Und, ignoreWidth: true},
	{Name: "cp1251_bin", ID: 50, SortLen: 1, CharsetName: "cp1251", binary: true},
	{Name: "cp1251_general_ci", ID: 51, SortLen: 1, Default: true, CharsetName: "cp1251", language: language.Und, ignoreCase: true, ignoreDiacritics: true, ignoreWidth: true},
	{Name: "cp1251_general_cs", ID: 52, SortLen: 1, CharsetName: "cp1251", language: language.Und, ignoreWidth: true},
	{Name: "macroman_bin", ID: 53, SortLen: 1, CharsetName: "macroman", binary: true},
	{Name: "utf16_general_ci", ID: 54, SortLen: 1, Default: true, CharsetName: "utf16", language: language.Und, ignoreCase: true, ignoreDiacritics: true, ignoreWidth: true},
	{Name: "utf16_bin", ID: 55, SortLen: 1, CharsetName: "utf16", binary: true},
	{Name: "utf16le_general_ci", ID: 56, SortLen: 1, Default: true, CharsetName: "utf16le", language: language.Und, ignoreCase: true, ignoreDiacritics: true, ignoreWidth: true},
	{Name: "cp1256_general_ci", ID: 57, SortLen: 1, Default: true, CharsetName: "cp1256", language: language.Und, ignoreCase: true, ignoreDiacritics: true, ignoreWidth: true},
	{Name: "cp1257_bin", ID: 58, SortLen: 1, CharsetName: "cp1257", binary: true},
	{Name: "cp1257_general_ci", ID: 59, SortLen: 1, Default: true, CharsetName: "cp1257", language: language.Und, ignoreCase: true, ignoreDiacritics: true, ignoreWidth: true},
	{Name: "utf32_general_ci", ID: 60, SortLen: 1, Default: true, CharsetName: "utf32", language: language.Und, ignoreCase: true, ignoreDiacritics: true, ignoreWidth: true},
	{Name: "utf32_bin", ID: 61, SortLen: 1, CharsetName: "utf32", language: language.Und},
	{Name: "utf16le_bin", ID: 62, SortLen: 1, CharsetName: "utf16le", language: language.Und},
	{Name: "binary", ID: 63, SortLen: 1, Default: true, CharsetName: "binary", binary: true},
	{Name: "armscii8_bin", ID: 64, SortLen: 1, CharsetName: "armscii8", binary: true},
	{Name: "ascii_bin", ID: 65, SortLen: 1, CharsetName: "ascii", binary: true},
	{Name: "cp1250_bin", ID: 66, SortLen: 1, CharsetName: "cp1250", binary: true},
	{Name: "cp1256_bin", ID: 67, SortLen: 1, CharsetName: "cp1256", binary: true},
	{Name: "cp866_bin", ID: 68, SortLen: 1, CharsetName: "cp866", binary: true},
	{Name: "dec8_bin", ID: 69, SortLen: 1, CharsetName: "dec8", binary: true},
	{Name: "greek_bin", ID: 70, SortLen: 1, CharsetName: "greek", binary: true},
	{Name: "hebrew_bin", ID: 71, SortLen: 1, CharsetName: "hebrew", binary: true},
	{Name: "hp8_bin", ID: 72, SortLen: 1, CharsetName: "hp8", binary: true},
	{Name: "keybcs2_bin", ID: 73, SortLen: 1, CharsetName: "keybcs2", binary: true},
	{Name: "koi8r_bin", ID: 74, SortLen: 1, CharsetName: "koi8r", binary: true},
	{Name: "koi8u_bin", ID: 75, SortLen: 1, CharsetName: "koi8u", binary: true},
	{Name: "latin2_bin", ID: 77, SortLen: 1, CharsetName: "latin2", binary: true},
	{Name: "latin5_bin", ID: 78, SortLen: 1, CharsetName: "latin5", binary: true},
	{Name: "latin7_bin", ID: 79, SortLen: 1, CharsetName: "latin7", binary: true},
	{Name: "cp850_bin", ID: 80, SortLen: 1, CharsetName: "cp850", binary: true},
	{Name: "cp852_bin", ID: 81, SortLen: 1, CharsetName: "cp852", binary: true},
	{Name: "swe7_bin", ID: 82, SortLen: 1, CharsetName: "swe7", binary: true},
	{Name: "utf8_bin", ID: 83, SortLen: 1, CharsetName: "utf8", binary: true},
	{Name: "big5_bin", ID: 84, SortLen: 1, CharsetName: "big5", binary: true},
	{Name: "euckr_bin", ID: 85, SortLen: 1, CharsetName: "euckr", binary: true},
	{Name: "gb2312_bin", ID: 86, SortLen: 1, CharsetName: "gb2312", binary: true},
	{Name: "gbk_bin", ID: 87, SortLen: 1, CharsetName: "gbk", binary: true},
	{Name: "sjis_bin", ID: 88, SortLen: 1, CharsetName: "sjis", binary: true},
	{Name: "tis620_bin", ID: 89, SortLen: 1, CharsetName: "tis620", binary: true},
	{Name: "ucs2_bin", ID: 90, SortLen: 1, CharsetName: "ucs2", binary: true},
	{Name: "ujis_bin", ID: 91, SortLen: 1, CharsetName: "ujis", binary: true},
	{Name: "geostd8_general_ci", ID: 92, SortLen: 1, Default: true, CharsetName: "geostd8", language: language.Und, ignoreCase: true, ignoreDiacritics: true, ignoreWidth: true},
	{Name: "geostd8_bin", ID: 93, SortLen: 1, CharsetName: "geostd8", binary: true},
	{Name: "latin1_spanish_ci", ID: 94, SortLen: 1, CharsetName: "latin1", language: language.Spanish, ignoreCase: true, ignoreDiacritics: true},
	{Name: "cp932_japanese_ci", ID: 95, SortLen: 1, Default: true, CharsetName: "cp932", language: language.Japanese, ignoreCase: true, ignoreDiacritics: true},
	{Name: "cp932_bin", ID: 96, SortLen: 1, CharsetName: "cp932", binary: true},
	{Name: "eucjpms_japanese_ci", ID: 97, SortLen: 1, Default: true, CharsetName: "eucjpms", language: language.Japanese, ignoreCase: true, ignoreDiacritics: true},
	{Name: "eucjpms_bin", ID: 98, SortLen: 1, CharsetName: "eucjpms", binary: true},
	{Name: "cp1250_polish_ci", ID: 99, SortLen: 1, CharsetName: "cp1250", language: language.Polish, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf16_unicode_ci", ID: 101, SortLen: 8, CharsetName: "utf16", language: language.Und, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf16_icelandic_ci", ID: 102, SortLen: 8, CharsetName: "utf16", language: language.Icelandic, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf16_latvian_ci", ID: 103, SortLen: 8, CharsetName: "utf16", language: language.Latvian, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf16_romanian_ci", ID: 104, SortLen: 8, CharsetName: "utf16", language: language.Romanian, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf16_slovenian_ci", ID: 105, SortLen: 8, CharsetName: "utf16", language: language.Slovenian, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf16_polish_ci", ID: 106, SortLen: 8, CharsetName: "utf16", language: language.Polish, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf16_estonian_ci", ID: 107, SortLen: 8, CharsetName: "utf16", language: language.Estonian, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf16_spanish_ci", ID: 108, SortLen: 8, CharsetName: "utf16", language: language.Spanish, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf16_swedish_ci", ID: 109, SortLen: 8, CharsetName: "utf16", language: language.Swedish, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf16_turkish_ci", ID: 110, SortLen: 8, CharsetName: "utf16", language: language.Turkish, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf16_czech_ci", ID: 111, SortLen: 8, CharsetName: "utf16", language: language.Czech, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf16_danish_ci", ID: 112, SortLen: 8, CharsetName: "utf16", language: language.Danish, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf16_lithuanian_ci", ID: 113, SortLen: 8, CharsetName: "utf16", language: language.Lithuanian, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf16_slovak_ci", ID: 114, SortLen: 8, CharsetName: "utf16", language: language.Slovak, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf16_spanish2_ci", ID: 115, SortLen: 8, CharsetName: "utf16", language: language.EuropeanSpanish, ignoreCase: true, ignoreDiacritics: true},
	//{Name: "utf16_roman_ci", ID: 116, SortLen: 8, CharsetName: "utf16", language: language.Roman, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf16_persian_ci", ID: 117, SortLen: 8, CharsetName: "utf16", language: language.Persian, ignoreCase: true, ignoreDiacritics: true},
	//{Name: "utf16_esperanto_ci", ID: 118, SortLen: 8, CharsetName: "utf16", language: language.Esperanto, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf16_hungarian_ci", ID: 119, SortLen: 8, CharsetName: "utf16", language: language.Hungarian, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf16_sinhala_ci", ID: 120, SortLen: 8, CharsetName: "utf16", language: language.Sinhala, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf16_german2_ci", ID: 121, SortLen: 8, CharsetName: "utf16", language: language.MustParse("de_AT"), ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf16_croatian_ci", ID: 122, SortLen: 8, CharsetName: "utf16", language: language.Croatian, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf16_unicode_520_ci", ID: 123, SortLen: 8, CharsetName: "utf16", language: language.Und, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf16_vietnamese_ci", ID: 124, SortLen: 8, CharsetName: "utf16", language: language.Vietnamese, ignoreCase: true, ignoreDiacritics: true},
	{Name: "ucs2_unicode_ci", ID: 128, SortLen: 8, CharsetName: "ucs2", language: language.Und, ignoreCase: true, ignoreDiacritics: true},
	{Name: "ucs2_icelandic_ci", ID: 129, SortLen: 8, CharsetName: "ucs2", language: language.Icelandic, ignoreCase: true, ignoreDiacritics: true},
	{Name: "ucs2_latvian_ci", ID: 130, SortLen: 8, CharsetName: "ucs2", language: language.Latvian, ignoreCase: true, ignoreDiacritics: true},
	{Name: "ucs2_romanian_ci", ID: 131, SortLen: 8, CharsetName: "ucs2", language: language.Romanian, ignoreCase: true, ignoreDiacritics: true},
	{Name: "ucs2_slovenian_ci", ID: 132, SortLen: 8, CharsetName: "ucs2", language: language.Slovenian, ignoreCase: true, ignoreDiacritics: true},
	{Name: "ucs2_polish_ci", ID: 133, SortLen: 8, CharsetName: "ucs2", language: language.Polish, ignoreCase: true, ignoreDiacritics: true},
	{Name: "ucs2_estonian_ci", ID: 134, SortLen: 8, CharsetName: "ucs2", language: language.Estonian, ignoreCase: true, ignoreDiacritics: true},
	{Name: "ucs2_spanish_ci", ID: 135, SortLen: 8, CharsetName: "ucs2", language: language.Spanish, ignoreCase: true, ignoreDiacritics: true},
	{Name: "ucs2_swedish_ci", ID: 136, SortLen: 8, CharsetName: "ucs2", language: language.Swedish, ignoreCase: true, ignoreDiacritics: true},
	{Name: "ucs2_turkish_ci", ID: 137, SortLen: 8, CharsetName: "ucs2", language: language.Turkish, ignoreCase: true, ignoreDiacritics: true},
	{Name: "ucs2_czech_ci", ID: 138, SortLen: 8, CharsetName: "ucs2", language: language.Czech, ignoreCase: true, ignoreDiacritics: true},
	{Name: "ucs2_danish_ci", ID: 139, SortLen: 8, CharsetName: "ucs2", language: language.Danish, ignoreCase: true, ignoreDiacritics: true},
	{Name: "ucs2_lithuanian_ci", ID: 140, SortLen: 8, CharsetName: "ucs2", language: language.Lithuanian, ignoreCase: true, ignoreDiacritics: true},
	{Name: "ucs2_slovak_ci", ID: 141, SortLen: 8, CharsetName: "ucs2", language: language.Slovak, ignoreCase: true, ignoreDiacritics: true},
	{Name: "ucs2_spanish2_ci", ID: 142, SortLen: 8, CharsetName: "ucs2", language: language.EuropeanSpanish, ignoreCase: true, ignoreDiacritics: true},
	//{Name: "ucs2_roman_ci", ID: 143, SortLen: 8, CharsetName: "ucs2", language: language.Roman, ignoreCase: true, ignoreDiacritics: true},
	{Name: "ucs2_persian_ci", ID: 144, SortLen: 8, CharsetName: "ucs2", language: language.Persian, ignoreCase: true, ignoreDiacritics: true},
	//{Name: "ucs2_esperanto_ci", ID: 145, SortLen: 8, CharsetName: "ucs2", language: language.Esperanto, ignoreCase: true, ignoreDiacritics: true},
	{Name: "ucs2_hungarian_ci", ID: 146, SortLen: 8, CharsetName: "ucs2", language: language.Hungarian, ignoreCase: true, ignoreDiacritics: true},
	{Name: "ucs2_sinhala_ci", ID: 147, SortLen: 8, CharsetName: "ucs2", language: language.Sinhala, ignoreCase: true, ignoreDiacritics: true},
	{Name: "ucs2_german2_ci", ID: 148, SortLen: 8, CharsetName: "ucs2", language: language.MustParse("de_AT"), ignoreCase: true, ignoreDiacritics: true},
	{Name: "ucs2_croatian_ci", ID: 149, SortLen: 8, CharsetName: "ucs2", language: language.Croatian, ignoreCase: true, ignoreDiacritics: true},
	{Name: "ucs2_unicode_520_ci", ID: 150, SortLen: 8, CharsetName: "ucs2", language: language.Und, ignoreCase: true, ignoreDiacritics: true},
	{Name: "ucs2_vietnamese_ci", ID: 151, SortLen: 8, CharsetName: "ucs2", language: language.Vietnamese, ignoreCase: true, ignoreDiacritics: true},
	{Name: "ucs2_general_mysql500_ci", ID: 159, SortLen: 1, CharsetName: "ucs2", language: language.Und, ignoreCase: true, ignoreDiacritics: true, ignoreWidth: true},
	{Name: "utf32_unicode_ci", ID: 160, SortLen: 8, CharsetName: "utf32", language: language.Und, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf32_icelandic_ci", ID: 161, SortLen: 8, CharsetName: "utf32", language: language.Icelandic, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf32_latvian_ci", ID: 162, SortLen: 8, CharsetName: "utf32", language: language.Latvian, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf32_romanian_ci", ID: 163, SortLen: 8, CharsetName: "utf32", language: language.Romanian, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf32_slovenian_ci", ID: 164, SortLen: 8, CharsetName: "utf32", language: language.Slovenian, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf32_polish_ci", ID: 165, SortLen: 8, CharsetName: "utf32", language: language.Polish, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf32_estonian_ci", ID: 166, SortLen: 8, CharsetName: "utf32", language: language.Estonian, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf32_spanish_ci", ID: 167, SortLen: 8, CharsetName: "utf32", language: language.Spanish, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf32_swedish_ci", ID: 168, SortLen: 8, CharsetName: "utf32", language: language.Swedish, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf32_turkish_ci", ID: 169, SortLen: 8, CharsetName: "utf32", language: language.Turkish, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf32_czech_ci", ID: 170, SortLen: 8, CharsetName: "utf32", language: language.Czech, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf32_danish_ci", ID: 171, SortLen: 8, CharsetName: "utf32", language: language.Danish, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf32_lithuanian_ci", ID: 172, SortLen: 8, CharsetName: "utf32", language: language.Lithuanian, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf32_slovak_ci", ID: 173, SortLen: 8, CharsetName: "utf32", language: language.Slovak, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf32_spanish2_ci", ID: 174, SortLen: 8, CharsetName: "utf32", language: language.EuropeanSpanish, ignoreCase: true, ignoreDiacritics: true},
	//{Name: "utf32_roman_ci", ID: 175, SortLen: 8, CharsetName: "utf32", language: language.Roman, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf32_persian_ci", ID: 176, SortLen: 8, CharsetName: "utf32", language: language.Persian, ignoreCase: true, ignoreDiacritics: true},
	//{Name: "utf32_esperanto_ci", ID: 177, SortLen: 8, CharsetName: "utf32", language: language.Esperanto, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf32_hungarian_ci", ID: 178, SortLen: 8, CharsetName: "utf32", language: language.Hungarian, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf32_sinhala_ci", ID: 179, SortLen: 8, CharsetName: "utf32", language: language.Sinhala, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf32_german2_ci", ID: 180, SortLen: 8, CharsetName: "utf32", language: language.MustParse("de_AT"), ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf32_croatian_ci", ID: 181, SortLen: 8, CharsetName: "utf32", language: language.Croatian, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf32_unicode_520_ci", ID: 182, SortLen: 8, CharsetName: "utf32", language: language.Und, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf32_vietnamese_ci", ID: 183, SortLen: 8, CharsetName: "utf32", language: language.Vietnamese, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf8_unicode_ci", ID: 192, SortLen: 8, CharsetName: "utf8", language: language.Und, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf8_icelandic_ci", ID: 193, SortLen: 8, CharsetName: "utf8", language: language.Icelandic, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf8_latvian_ci", ID: 194, SortLen: 8, CharsetName: "utf8", language: language.Latvian, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf8_romanian_ci", ID: 195, SortLen: 8, CharsetName: "utf8", language: language.Romanian, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf8_slovenian_ci", ID: 196, SortLen: 8, CharsetName: "utf8", language: language.Slovenian, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf8_polish_ci", ID: 197, SortLen: 8, CharsetName: "utf8", language: language.Polish, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf8_estonian_ci", ID: 198, SortLen: 8, CharsetName: "utf8", language: language.Estonian, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf8_spanish_ci", ID: 199, SortLen: 8, CharsetName: "utf8", language: language.Spanish, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf8_swedish_ci", ID: 200, SortLen: 8, CharsetName: "utf8", language: language.Swedish, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf8_turkish_ci", ID: 201, SortLen: 8, CharsetName: "utf8", language: language.Turkish, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf8_czech_ci", ID: 202, SortLen: 8, CharsetName: "utf8", language: language.Czech, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf8_danish_ci", ID: 203, SortLen: 8, CharsetName: "utf8", language: language.Danish, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf8_lithuanian_ci", ID: 204, SortLen: 8, CharsetName: "utf8", language: language.Lithuanian, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf8_slovak_ci", ID: 205, SortLen: 8, CharsetName: "utf8", language: language.Slovak, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf8_spanish2_ci", ID: 206, SortLen: 8, CharsetName: "utf8", language: language.EuropeanSpanish, ignoreCase: true, ignoreDiacritics: true},
	//{Name: "utf8_roman_ci", ID: 207, SortLen: 8, CharsetName: "utf8", language: language.Roman, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf8_persian_ci", ID: 208, SortLen: 8, CharsetName: "utf8", language: language.Persian, ignoreCase: true, ignoreDiacritics: true},
	//{Name: "utf8_esperanto_ci", ID: 209, SortLen: 8, CharsetName: "utf8", language: language.Esperanto, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf8_hungarian_ci", ID: 210, SortLen: 8, CharsetName: "utf8", language: language.Hungarian, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf8_sinhala_ci", ID: 211, SortLen: 8, CharsetName: "utf8", language: language.Sinhala, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf8_german2_ci", ID: 212, SortLen: 8, CharsetName: "utf8", language: language.MustParse("de_AT"), ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf8_croatian_ci", ID: 213, SortLen: 8, CharsetName: "utf8", language: language.Croatian, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf8_unicode_520_ci", ID: 214, SortLen: 8, CharsetName: "utf8", language: language.Und, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf8_vietnamese_ci", ID: 215, SortLen: 8, CharsetName: "utf8", language: language.Vietnamese, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf8_general_mysql500_ci", ID: 223, SortLen: 1, CharsetName: "utf8", language: language.Und, ignoreCase: true, ignoreDiacritics: true, ignoreWidth: true},
	{Name: "utf8mb4_unicode_ci", ID: 224, SortLen: 8, CharsetName: "utf8mb4", language: language.Und, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf8mb4_icelandic_ci", ID: 225, SortLen: 8, CharsetName: "utf8mb4", language: language.Icelandic, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf8mb4_latvian_ci", ID: 226, SortLen: 8, CharsetName: "utf8mb4", language: language.Latvian, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf8mb4_romanian_ci", ID: 227, SortLen: 8, CharsetName: "utf8mb4", language: language.Romanian, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf8mb4_slovenian_ci", ID: 228, SortLen: 8, CharsetName: "utf8mb4", language: language.Slovenian, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf8mb4_polish_ci", ID: 229, SortLen: 8, CharsetName: "utf8mb4", language: language.Polish, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf8mb4_estonian_ci", ID: 230, SortLen: 8, CharsetName: "utf8mb4", language: language.Estonian, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf8mb4_spanish_ci", ID: 231, SortLen: 8, CharsetName: "utf8mb4", language: language.Spanish, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf8mb4_swedish_ci", ID: 232, SortLen: 8, CharsetName: "utf8mb4", language: language.Swedish, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf8mb4_turkish_ci", ID: 233, SortLen: 8, CharsetName: "utf8mb4", language: language.Turkish, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf8mb4_czech_ci", ID: 234, SortLen: 8, CharsetName: "utf8mb4", language: language.Czech, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf8mb4_danish_ci", ID: 235, SortLen: 8, CharsetName: "utf8mb4", language: language.Danish, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf8mb4_lithuanian_ci", ID: 236, SortLen: 8, CharsetName: "utf8mb4", language: language.Lithuanian, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf8mb4_slovak_ci", ID: 237, SortLen: 8, CharsetName: "utf8mb4", language: language.Slovak, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf8mb4_spanish2_ci", ID: 238, SortLen: 8, CharsetName: "utf8mb4", language: language.EuropeanSpanish, ignoreCase: true, ignoreDiacritics: true},
	//{Name: "utf8mb4_roman_ci", ID: 239, SortLen: 8, CharsetName: "utf8mb4", language: language.Roman, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf8mb4_persian_ci", ID: 240, SortLen: 8, CharsetName: "utf8mb4", language: language.Persian, ignoreCase: true, ignoreDiacritics: true},
	//{Name: "utf8mb4_esperanto_ci", ID: 241, SortLen: 8, CharsetName: "utf8mb4", language: language.Esperanto, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf8mb4_hungarian_ci", ID: 242, SortLen: 8, CharsetName: "utf8mb4", language: language.Hungarian, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf8mb4_sinhala_ci", ID: 243, SortLen: 8, CharsetName: "utf8mb4", language: language.Sinhala, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf8mb4_german2_ci", ID: 244, SortLen: 8, CharsetName: "utf8mb4", language: language.MustParse("de_AT"), ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf8mb4_croatian_ci", ID: 245, SortLen: 8, CharsetName: "utf8mb4", language: language.Croatian, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf8mb4_unicode_520_ci", ID: 246, SortLen: 8, CharsetName: "utf8mb4", language: language.Und, ignoreCase: true, ignoreDiacritics: true},
	{Name: "utf8mb4_vietnamese_ci", ID: 247, SortLen: 8, CharsetName: "utf8mb4", language: language.Vietnamese, ignoreCase: true, ignoreDiacritics: true},
}

var charsetEncodings = map[CharsetName]encoding.Encoding{
	"big5":  traditionalchinese.Big5,
	"cp850": charmap.CodePage850,
	//"hp8": // HP West European,
	"koi8r":  charmap.KOI8R,
	"latin1": charmap.Windows1252,
	"latin2": charmap.ISO8859_2,
	//"swe7": // 7bit Swedish,
	"ascii":  charmap.Windows1252,
	"ujis":   japanese.EUCJP,
	"sjis":   japanese.ShiftJIS,
	"hebrew": charmap.ISO8859_8,
	"tis620": charmap.Windows874,
	"euckr":  korean.EUCKR,
	"koi8u":  charmap.KOI8U,
	"gb2312": simplifiedchinese.HZGB2312,
	"greek":  charmap.ISO8859_7,
	"cp1250": charmap.Windows1250,
	"gbk":    simplifiedchinese.GBK,
	"latin5": charmap.Windows1254,
	//"armscii8": // ARMSCII-8 Armenian,
	"utf8": unicode.UTF8,
	//"ucs2": // UCS-2 Unicode,
	"cp866": charmap.CodePage866,
	//"keybcs2": // DOS Kamenicky Czech-Slovak,
	"macce":    charmap.MacintoshCyrillic,
	"macroman": charmap.Macintosh,
	"cp852":    charmap.CodePage852,
	"latin7":   charmap.ISO8859_13,
	"utf8mb4":  unicode.UTF8,
	"cp1251":   charmap.Windows1251,
	"utf16":    unicode.UTF16(unicode.BigEndian, unicode.IgnoreBOM),
	"utf16le":  unicode.UTF16(unicode.LittleEndian, unicode.IgnoreBOM),
	"cp1256":   charmap.Windows1256,
	"cp1257":   charmap.Windows1257,
	"utf32":    utf32.UTF32(utf32.BigEndian, utf32.IgnoreBOM),
	"binary":   encoding.Nop,
	//"geostd8": // GEOSTD8 Georgian,
	//"cp932": // SJIS for Windows Japanese,
	//"eucjpms": // UJIS for Windows Japanese,
}
