uri: mongodb://test:test@localhost:27017/
ns-include:
  # Include all collections in only the database config_db.
  - config_db.*
ns-exclude:
  # But do not include the foo collection. Note, namespaces do not need to be specified
  # in ns-include prior to specifying them in ns-exclude.
  - config_db.foo
quiet: false
dry-run: false
