package generate

import (
	"fmt"
	"io"
	"os"
	"text/template"

	yaml "github.com/10gen/candiedyaml"
)

// ScalarFuncSpec specifies how a scalar function's code should be generated.
// For more details on the meaning of each field, see the comment at the top of
// scalar_functions.yml.
type ScalarFuncSpec struct {
	ID                           string                 `yaml:"id"`
	Description                  string                 `yaml:"description"`
	MySQLDocURL                  string                 `yaml:"mysql_doc_url"`
	Names                        []string               `yaml:"names"`
	SeparateInvocationEvaluation bool                   `yaml:"separate_invocation_evaluation"`
	ValidateArgTypes             bool                   `yaml:"validate_arg_types"`
	Reconcile                    string                 `yaml:"reconcile"`
	SkipConstantFolding          bool                   `yaml:"skip_constant_folding"`
	NoPushdown                   bool                   `yaml:"no_pushdown"`
	CustomNormalize              bool                   `yaml:"custom_normalize"`
	Invocations                  []ScalarFuncInvocation `yaml:"invocations"`
}

func (sf *ScalarFuncSpec) SkipReconcile() bool {
	switch sf.Reconcile {
	case "skip":
		return true
	case "", "custom":
		return false
	default:
		panic(fmt.Errorf("unexpected value for 'reconcile' key in '%s' function: %s", sf.ID, sf.Reconcile))
	}
}

func (sf *ScalarFuncSpec) CustomReconcile() bool {
	switch sf.Reconcile {
	case "custom":
		return true
	case "", "skip":
		return false
	default:
		panic(fmt.Errorf("unexpected value for 'reconcile' key in '%s' function: %s", sf.ID, sf.Reconcile))
	}
}

// ScalarFuncInvocation represents the specification for a particular invocation
// of a scalar function. For more details on the meaning of each field, see the
// comment at the top of scalar_functions.yml.
type ScalarFuncInvocation struct {
	ID             string               `yaml:"id"`
	Arguments      []ScalarFuncArgument `yaml:"arguments"`
	ReturnEvalType string               `yaml:"return_type"`
}

// ScalarFuncArgument represents the specification for a particular argument
// to a scalar function. For more details on the meaning of each field, see the
// comment at the top of scalar_functions.yml.
type ScalarFuncArgument struct {
	Name     string `yaml:"name"`
	Variadic bool   `yaml:"variadic"`
	EvalType string `yaml:"eval_type"`
}

// ArgEvalTypes returns a list of this function invocation's argument EvalTypes
// as strings.
func (i ScalarFuncInvocation) ArgEvalTypes() []string {
	types := []string{}
	for _, arg := range i.Arguments {
		types = append(types, arg.EvalType)
	}
	return types
}

// IsVariadic returns whether this scalar function invocation is variadic.
func (i ScalarFuncInvocation) IsVariadic() bool {
	if len(i.Arguments) == 0 {
		return false
	}
	return i.Arguments[len(i.Arguments)-1].Variadic
}

// ScalarFunctionsSpec is the struct into which evaluator/scalar_functions.yml
// should be deserialized.
type ScalarFunctionsSpec struct {
	Functions []*ScalarFuncSpec `yaml:"functions"`
}

// Parse loads ScalarFunctionSpecs from the file at the provided path.
func (sf *ScalarFunctionsSpec) Parse(filename string) error {
	f, err := os.Open(filename)
	if err != nil {
		return err
	}
	decoder := yaml.NewDecoder(f)
	return decoder.Decode(sf)
}

// Generate writes the code generated for this Spec's scalar functions to the
// provided io.Writer.
func (sf *ScalarFunctionsSpec) Generate(w io.Writer) error {
	tmplString := `// Code generated by 'go generate'. DO NOT EDIT.

package evaluator

import (
    "context"
    "fmt"
)

const (
    noMatchingInvocationMessage = "provided arguments do not match any invocations for '%s' scalar function"
)

{{range .Functions -}}
{{$func := .}}
{{- range .Invocations}}

type {{$func.ID}}{{.ID}}Func struct {
    baseScalarFunctionExpr
}

// {{$func.ID}}{{.ID}}Func must satisfy the SQLScalarFunctionExpr interface.
var _ SQLScalarFunctionExpr = (*{{$func.ID}}{{.ID}}Func)(nil)

// The following constants represent some properties of the {{$func.ID}}{{.ID}}Func scalar function.
var (
    {{$func.ID}}{{.ID}}ExpectedTypes []EvalType = []EvalType{ {{- range $i, $typ := .ArgEvalTypes}}{{if $i}}, {{end}}{{$typ}}{{end -}} }
    {{$func.ID}}{{.ID}}IsVariadic bool = {{.IsVariadic}}
    {{$func.ID}}{{.ID}}ReturnTypeFunc func([]SQLExpr) EvalType = {{$func.ID}}{{.ID}}EvalType
)

func (f *{{$func.ID}}{{.ID}}Func) Evaluate(ctx context.Context, cfg *ExecutionConfig, st *ExecutionState) (SQLValue, error) {
    {{- if $func.ValidateArgTypes}}
    // Validate this function's argument count and types.
	err := f.validateArgs()
	if err != nil {
		return nil, err
	}
    {{- else}}
    // Validate this function's argument count.
	err := f.validateArgCount()
	if err != nil {
		return nil, err
	}
    {{- end}}

	// evaluate arguments
	args := []SQLValue{}
	for i, arg := range f.args {
		val, err := arg.Evaluate(ctx, cfg, st)
		if err != nil {
			return nil, fmt.Errorf("error evaluating argument at index %d in scalar function '%s': %v", i, f.invokedAs, err)
		}
		args = append(args, val)
	}

    {{if $func.SeparateInvocationEvaluation}}
    // Call the function that contains the appropriate evaluation logic.
	return f.{{$func.ID}}{{.ID}}Evaluate(ctx, cfg, st, args)
    {{else}}
    // Call the function that contains the appropriate evaluation logic.
    // For now, one evaluate function contains the logic for all invocations of this function,
    // but we will probably want to separate them out at some point in the future.
	return f.{{$func.ID}}Evaluate(ctx, cfg, st, args)
    {{- end}}
}

func (f *{{$func.ID}}{{.ID}}Func) ToAggregationLanguage(t *PushdownTranslator) (interface{}, PushdownFailure) {
    {{- if $func.NoPushdown}}
    return nil, newPushdownFailure(f.ExprName(), "no pushdown implementation")
    {{- else}}
    return f.{{$func.ID}}ToAggregationLanguage(t, f.args)
    {{- end}}
}

func (f *{{$func.ID}}{{.ID}}Func) ToAggregationPredicate(t *PushdownTranslator) (interface{}, PushdownFailure) {
    return f.ToAggregationLanguage(t)
}

{{- if $func.SkipConstantFolding}}
func (f *{{$func.ID}}{{.ID}}Func) SkipConstantFolding() bool {
    return true
}
{{- end}}

func (f *{{$func.ID}}{{.ID}}Func) Normalize(kind SQLValueKind) Node {
    {{- if $func.CustomNormalize}}
    if newExpr, ok := f.{{$func.ID}}Normalize(kind); ok {
        return newExpr
    }
    return f
    {{- else}}
    if hasNullExpr(f.args...) {
        return NewSQLNull(kind, f.EvalType())
    }
    return f
    {{- end}}
}

{{if $func.SkipReconcile}}// nolint: unparam{{end}}
func (f *{{$func.ID}}{{.ID}}Func) reconcile() (SQLExpr, error) {
    {{- if $func.SkipReconcile}}
    return f, nil
    {{- else}}
    convertedArgs := {{if $func.CustomReconcile}}{{$func.ID}}{{.ID}}ReconcileArgs(f.args){{else}}convertExprs(f.args, f.argTypes()){{end}}
    return NewSQLScalarFunctionExpr(f.invokedAs, convertedArgs)
    {{- end}}
}

{{if .ReturnEvalType -}}
func {{$func.ID}}{{.ID}}EvalType(_ []SQLExpr) EvalType {
    return {{.ReturnEvalType}}
}
{{- end}}

{{- end}}
{{- end}}

func NewSQLScalarFunctionExpr(name string, exprs []SQLExpr) (SQLScalarFunctionExpr, error) {
	switch name {
	{{range .Functions}}
    {{- $func := .}}
	case {{range $i, $name := .Names}}{{if $i}},{{end}}"{{$name}}"{{end}}:
        var base baseScalarFunctionExpr
        var err error
		{{- range .Invocations}}

        // check whether provided arguments are valid for {{$func.ID}}{{.ID}}Func
		base = baseScalarFunctionExpr{
            invokedAs: name,
			args: exprs,

			expectedTypes: {{$func.ID}}{{.ID}}ExpectedTypes,
			variadic: {{$func.ID}}{{.ID}}IsVariadic,
			returnTypeFunc: {{$func.ID}}{{.ID}}ReturnTypeFunc,
		}
		err = base.validateArgCount()
		if err == nil {
			return &{{$func.ID}}{{.ID}}Func{base}, nil
		}
		{{- end}}

        return nil, fmt.Errorf(noMatchingInvocationMessage, name)
	{{end}}
    default:
		return nil, fmt.Errorf("scalar function '%s' is not supported", name)
	}
}
`

	tmpl, err := template.New("funcs").Parse(tmplString)
	if err != nil {
		return fmt.Errorf("error parsing template: %v", err)
	}

	return tmpl.Execute(w, sf)
}
