package generate

import (
	"fmt"
	"io"
	"os"
	"text/template"

	yaml "github.com/10gen/candiedyaml"
)

// ScalarFuncSpec specifies how a scalar function's code should be generated.
// For more details on the meaning of each field, see the comment at the top of
// scalar_functions.yml.
type ScalarFuncSpec struct {
	ID                           string                 `yaml:"id"`
	Description                  string                 `yaml:"description"`
	MySQLDocURL                  string                 `yaml:"mysql_doc_url"`
	Names                        []string               `yaml:"names"`
	SeparateInvocationEvaluation bool                   `yaml:"separate_invocation_evaluation"`
	UseFullEvaluationState       bool                   `yaml:"use_full_evaluation_state"`
	ValidateArgTypes             bool                   `yaml:"validate_arg_types"`
	Reconcile                    string                 `yaml:"reconcile"`
	NoPushdown                   bool                   `yaml:"no_pushdown"`
	CustomFoldConstants          bool                   `yaml:"custom_fold_constants"`
	Invocations                  []ScalarFuncInvocation `yaml:"invocations"`
}

func (sf *ScalarFuncSpec) SkipReconcile() bool {
	switch sf.Reconcile {
	case "skip":
		return true
	case "", "custom":
		return false
	default:
		panic(fmt.Errorf("unexpected value for 'reconcile' key in '%s' function: %s", sf.ID, sf.Reconcile))
	}
}

func (sf *ScalarFuncSpec) CustomReconcile() bool {
	switch sf.Reconcile {
	case "custom":
		return true
	case "", "skip":
		return false
	default:
		panic(fmt.Errorf("unexpected value for 'reconcile' key in '%s' function: %s", sf.ID, sf.Reconcile))
	}
}

// ScalarFuncInvocation represents the specification for a particular invocation
// of a scalar function. For more details on the meaning of each field, see the
// comment at the top of scalar_functions.yml.
type ScalarFuncInvocation struct {
	ID             string               `yaml:"id"`
	Children       []ScalarFuncArgument `yaml:"arguments"`
	ReturnEvalType string               `yaml:"return_type"`
}

// ScalarFuncArgument represents the specification for a particular argument
// to a scalar function. For more details on the meaning of each field, see the
// comment at the top of scalar_functions.yml.
type ScalarFuncArgument struct {
	Name     string `yaml:"name"`
	Variadic bool   `yaml:"variadic"`
	EvalType string `yaml:"eval_type"`
}

// ArgEvalTypes returns a list of this function invocation's argument EvalTypes
// as strings.
func (i ScalarFuncInvocation) ArgEvalTypes() []string {
	types := []string{}
	for _, arg := range i.Children {
		types = append(types, arg.EvalType)
	}
	return types
}

// IsVariadic returns whether this scalar function invocation is variadic.
func (i ScalarFuncInvocation) IsVariadic() bool {
	if len(i.Children) == 0 {
		return false
	}
	return i.Children[len(i.Children)-1].Variadic
}

// ScalarFunctionsSpec is the struct into which evaluator/scalar_functions.yml
// should be deserialized.
type ScalarFunctionsSpec struct {
	Functions []*ScalarFuncSpec `yaml:"functions"`
}

// Parse loads ScalarFunctionSpecs from the file at the provided path.
func (sf *ScalarFunctionsSpec) Parse(filename string) error {
	f, err := os.Open(filename)
	if err != nil {
		return err
	}
	decoder := yaml.NewDecoder(f)
	err = decoder.Decode(sf)
	if err != nil {
		return fmt.Errorf("Error parsing yaml file: %v", err)
	}
	return nil
}

// Generate writes the code generated for this Spec's scalar functions to the
// provided io.Writer.
func (sf *ScalarFunctionsSpec) Generate(w io.Writer) error {
	tmplString := `// Code generated by 'go generate'. DO NOT EDIT.

package evaluator

import (
	"context"
	"fmt"
)

const (
	noMatchingInvocationMessage = "provided arguments do not match any invocations for '%s' scalar function"
)

{{range .Functions -}}
{{$func := .}}
{{- range .Invocations}}

type {{$func.ID}}{{.ID}}Func struct {
	baseScalarFunctionExpr
}

// {{$func.ID}}{{.ID}}Func must satisfy the SQLScalarFunctionExpr interface.
var _ SQLScalarFunctionExpr = (*{{$func.ID}}{{.ID}}Func)(nil)

// The following constants represent some properties of the {{$func.ID}}{{.ID}}Func scalar function.
var (
	{{$func.ID}}{{.ID}}ExpectedTypes []EvalType = []EvalType{ {{- range $i, $typ := .ArgEvalTypes}}{{if $i}}, {{end}}{{$typ}}{{end -}} }
	{{$func.ID}}{{.ID}}IsVariadic bool = {{.IsVariadic}}
	{{$func.ID}}{{.ID}}ReturnTypeFunc func([]SQLExpr) EvalType = {{$func.ID}}{{.ID}}EvalType
)

func (f *{{$func.ID}}{{.ID}}Func) Evaluate(ctx context.Context, cfg *ExecutionConfig, st *ExecutionState) (SQLValue, error) {
	{{- if $func.ValidateArgTypes}}
	// Validate this function's argument count and types.
	err := f.validateArgs()
	if err != nil {
		return nil, err
	}
	{{- else}}
	// Validate this function's argument count.
	err := f.validateArgCount()
	if err != nil {
		return nil, err
	}
	{{- end}}

	// evaluate arguments
	args := []SQLValue{}
	for i, arg := range f.args {
		val, err := arg.Evaluate(ctx, cfg, st)
		if err != nil {
			return nil, fmt.Errorf("error evaluating argument at index %d in scalar function '%s': %v", i, f.invokedAs, err)
		}
		args = append(args, val)
	}

	{{- if $func.UseFullEvaluationState}}
		// Call the full state evlauation function that contains the appropriate evaluation logic.
		return f.{{$func.ID}}EvaluateWithFullEvaluationState(ctx, cfg, st, args)
		{{- if $func.SeparateInvocationEvaluation}}
			// Call the full state separate SQLValue accepting function that contains the appropriate evaluation logic.
			return f.{{$func.ID}}{{.ID}}EvaluateWithFullEvaluationState(ctx, cfg, st, args)
 		{{- end}}
	{{- else}}
		{{- if $func.SeparateInvocationEvaluation}}
  			// Call the separate SQLValue accepting evaluation function that contains the appropriate evaluation logic.
			return f.{{$func.ID}}{{.ID}}Evaluate(cfg.sqlValueKind, st.collation, args)
			{{- else}}
				// Call the value based evaluation function that contains the appropriate evaluation logic.
				return f.{{$func.ID}}Evaluate(cfg.sqlValueKind, st.collation, args)
		{{- end}}
	{{- end}}
}

func (f *{{$func.ID}}{{.ID}}Func) ToAggregationLanguage(t *PushdownTranslator) (interface{}, PushdownFailure) {
	{{- if $func.NoPushdown}}
	return nil, newPushdownFailure(f.ExprName(), "no pushdown implementation")
	{{- else}}
	return f.{{$func.ID}}ToAggregationLanguage(t, f.args)
	{{- end}}
}

func (f *{{$func.ID}}{{.ID}}Func) ToAggregationPredicate(t *PushdownTranslator) (interface{}, PushdownFailure) {
	return f.ToAggregationLanguage(t)
}

func (f *{{$func.ID}}{{.ID}}Func) FoldConstants(cfg *OptimizerConfig) SQLExpr {
	{{- if $func.CustomFoldConstants}}
		if newExpr, ok := f.{{$func.ID}}FoldConstants(cfg); ok {
			return newExpr
		}
		return f
	{{- else}}
		{{- if $func.UseFullEvaluationState}}
		{{- else}}
		allVals := true
		{{- end}}
		valArgs := make([]SQLValue, len(f.args))
		for i, arg := range f.args {
			if val, ok := arg.(SQLValue); ok {
				valArgs[i] = val
			} else {
			{{- if $func.UseFullEvaluationState}}
			{{- else}}
				allVals = false
			{{- end}}
			}
		}
 		if hasNullExpr(f.args...) {
   			 return NewSQLNull(cfg.sqlValueKind, f.EvalType())
		}
		{{- if $func.UseFullEvaluationState}}
			return f
		{{- else}}
			if !allVals {
				return f
			}
			// Call the function that contains the appropriate evaluation logic.
			{{- if $func.SeparateInvocationEvaluation}}
				val, err :=  f.{{$func.ID}}{{.ID}}Evaluate(cfg.sqlValueKind, cfg.collation, valArgs)
			{{- else}}
				val, err := f.{{$func.ID}}Evaluate(cfg.sqlValueKind, cfg.collation, valArgs)
			{{- end}}
			if err != nil {
				return f
			}
			return val
		{{- end}}
	{{- end}}
}

{{if $func.SkipReconcile}}// nolint: unparam{{end}}
func (f *{{$func.ID}}{{.ID}}Func) reconcile() (SQLExpr, error) {
    {{- if $func.SkipReconcile}}
    return f, nil
    {{- else}}
    convertedArgs := {{if $func.CustomReconcile}}{{$func.ID}}{{.ID}}ReconcileArgs(f.args){{else}}convertExprs(f.args, f.argTypes()){{end}}
    return NewSQLScalarFunctionExpr(f.invokedAs, convertedArgs)
    {{- end}}
}

{{if .ReturnEvalType -}}
func {{$func.ID}}{{.ID}}EvalType(_ []SQLExpr) EvalType {
	return {{.ReturnEvalType}}
}
{{- end}}

{{- end}}
{{- end}}

func NewSQLScalarFunctionExpr(name string, exprs []SQLExpr) (SQLScalarFunctionExpr, error) {
	switch name {
	{{range .Functions}}
	{{- $func := .}}
	case {{range $i, $name := .Names}}{{if $i}},{{end}}"{{$name}}"{{end}}:
		var base baseScalarFunctionExpr
		var err error
		{{- range .Invocations}}

		// check whether provided arguments are valid for {{$func.ID}}{{.ID}}Func
		base = baseScalarFunctionExpr{
			invokedAs: name,
			args: exprs,

			expectedTypes: {{$func.ID}}{{.ID}}ExpectedTypes,
			variadic: {{$func.ID}}{{.ID}}IsVariadic,
			returnTypeFunc: {{$func.ID}}{{.ID}}ReturnTypeFunc,
		}
		err = base.validateArgCount()
		if err == nil {
			return &{{$func.ID}}{{.ID}}Func{base}, nil
		}
		{{- end}}

		return nil, fmt.Errorf(noMatchingInvocationMessage, name)
	{{end}}
	default:
		return nil, fmt.Errorf("scalar function '%s' is not supported", name)
	}
}
`

	tmpl, err := template.New("funcs").Parse(tmplString)
	if err != nil {
		return fmt.Errorf("error parsing template: %v", err)
	}

	return tmpl.Execute(w, sf)
}
