package generate

import (
	"fmt"
	"io"
	"os"
	"strings"
	"text/template"

	yaml "github.com/10gen/candiedyaml"
)

type SystemVariableSpec struct {
	ID           string         `yaml:"_id"`
	Name         string         `yaml:"name"`
	SetScopes    []string       `yaml:"set_scopes"`
	VariableType string         `yaml:"type"`
	GolangType   string         `yaml:"go_type"`
	Default      string         `yaml:"default"`
	ConfigField  string         `yaml:"config_field"`
	CustomGetter bool           `yaml:"custom_getter"`
	CustomSetter bool           `yaml:"custom_setter"`
	Validation   ValidationSpec `yaml:"validation"`
}

type ValidationSpec struct {
	Enum []EnumVariantSpec `yaml:"enum"`
	Min  string            `yaml:"min"`
	Max  string            `yaml:"max"`
}

type EnumVariantSpec struct {
	Variant string `yaml:"variant"`
	Value   string `yaml:"value"`
}

func (sv SystemVariableSpec) NameVar() string {
	if sv.ID[0:3] == "sql" {
		return "SQL" + sv.ID[3:]
	}
	return strings.Title(sv.ID)
}

func (sv SystemVariableSpec) DefaultVar() string {
	return "default" + sv.NameVar()
}

func (sv SystemVariableSpec) GetterFunc() string {
	return "get" + sv.NameVar()
}

func (sv SystemVariableSpec) SetterFunc() string {
	return "set" + sv.NameVar()
}

var evalTypeByVariableType = map[string]string{
	"SQLInt64":   "EvalInt64",
	"SQLBool":    "EvalBoolean",
	"SQLVarchar": "EvalString",
	"SQLUint64":  "EvalUint64",
}

func (sv SystemVariableSpec) Initializer(value string) string {
	return fmt.Sprintf("values.New%s(values.VariableSQLValueKind, %s)", sv.VariableType, value)
}

func (sv SystemVariableSpec) SetFromConfig(value string) string {
	value = "cfg." + value
	return sv.Initializer(value)
}

func (sv SystemVariableSpec) ConvertFunc() string {
	return "convert" + sv.VariableType
}

func (sv SystemVariableSpec) ContainerField() string {
	return sv.ID
}

func (sv SystemVariableSpec) SetScopeExpr() string {
	if len(sv.SetScopes) == 0 {
		return "Scope(0)"
	}

	scopeStrs := []string{}
	for _, scope := range sv.SetScopes {
		scopeStrs = append(scopeStrs, strings.Title(scope)+"Scope")
	}

	return strings.Join(scopeStrs, " | ")
}

func (sv SystemVariableSpec) VariableTypeExpr() string {
	return "values." + sv.VariableType
}

func (sv SystemVariableSpec) EvalTypeExpr() string {
	return "types." + evalTypeByVariableType[sv.VariableType]
}

type VariablesSpec struct {
	SystemVariables []SystemVariableSpec `yaml:"system_variables"`
}

func (v *VariablesSpec) Parse(filename string) error {
	f, err := os.Open(filename)
	if err != nil {
		return err
	}
	decoder := yaml.NewDecoder(f)
	err = decoder.Decode(v)
	if err != nil {
		return fmt.Errorf("Error parsing yaml file: %v", err)
	}
	return nil
}

func (v *VariablesSpec) Generate(w io.Writer) error {
	tmplString := `// Code generated by 'go generate'. DO NOT EDIT.

package variable

import (
    "fmt"
    "math"

    "github.com/10gen/sqlproxy/collation"
    "github.com/10gen/sqlproxy/evaluator/types"
    "github.com/10gen/sqlproxy/evaluator/values"
    "github.com/10gen/sqlproxy/internal/config"
    "github.com/10gen/sqlproxy/internal/mysqlerrors"
)

// These variables hold system variable names.
const (
{{- range .SystemVariables}}
    {{.NameVar}} Name = "{{.Name}}"
{{- end}}
)

// These are constants representing variants of enum-style variables.
const (
{{- range .SystemVariables}}
{{-  $var := . }}
{{- if .Validation.Enum}}
// {{.NameVar}} variants
{{range .Validation.Enum -}}
    {{.Variant}}{{$var.NameVar}} = "{{.Value}}"
{{end}}
{{- end}}
{{- end}}
)

// These are constants representing variables' default values.
var (
{{- range .SystemVariables}}
    {{.DefaultVar}} {{.VariableTypeExpr}} = {{.Initializer .Default}}
{{- end}}
)

type systemVariableContainer struct {
{{- range .SystemVariables}}
    {{.ContainerField}} {{.VariableTypeExpr}}
{{- end}}
}

func (svc *systemVariableContainer) setDefaults() {
{{- range .SystemVariables}}
    svc.{{.ContainerField}} = {{.DefaultVar}}
{{- end}}
}

func (svc *systemVariableContainer) setFromConfig(cfg *config.Config) {
{{- range .SystemVariables}}
{{- if .ConfigField}}
    svc.{{.ContainerField}} = {{.SetFromConfig .ConfigField}}
{{- end}}
{{- end}}
}

func init() {
{{- range .SystemVariables}}

    definitions[{{.NameVar}}] = &definition{
        Name: {{.NameVar}},
        Kind: SystemKind,
        AllowedSetScopes: {{.SetScopeExpr}},
        EvalType: {{.EvalTypeExpr}},
        GetValue: {{if .CustomGetter}}{{.GetterFunc}}{{else}}func(c *Container) values.SQLValue { return c.systemVariableContainer.{{.ContainerField}} }{{end}},
        SetValue: {{.SetterFunc}},
    }
{{- end}}
}

{{- range .SystemVariables}}
{{- $var := .}}
{{if .CustomSetter}}{{else}}
func {{.SetterFunc}}(c *Container, v values.SQLValue) error {
    val, err := {{.ConvertFunc}}({{$var.NameVar}}, v)
	if err != nil {
		return err
	}

    {{if .Validation.Min}}
    if lessThan(val, {{.Validation.Min}}) {
        return mysqlerrors.Defaultf(mysqlerrors.ErWrongValueForVar, {{.NameVar}}, val)
    }
    {{end}}
    {{if .Validation.Max}}
    if greaterThan(val, {{.Validation.Max}}) {
        return mysqlerrors.Defaultf(mysqlerrors.ErWrongValueForVar, {{.NameVar}}, val)
    }
    {{end}}
    {{if .Validation.Enum}}
    switch val.String() {
    {{- range .Validation.Enum}}
    case {{.Variant}}{{$var.NameVar}}:
        // valid
    {{- end}}
    default:
        return mysqlerrors.Defaultf(mysqlerrors.ErWrongValueForVar, {{$var.NameVar}}, val)
    }
    {{end}}

    c.systemVariableContainer.{{.ContainerField}} = val
    return nil
}
{{- end}}{{end}}
`

	tmpl, err := template.New("vars").Parse(tmplString)
	if err != nil {
		return fmt.Errorf("error parsing template: %v", err)
	}

	return tmpl.Execute(w, v)
}
