package generate

import (
	"fmt"
	"io"
	"os"
	"strings"
	"text/template"

	yaml "github.com/10gen/candiedyaml"
)

type SystemVariableSpec struct {
	ID           string         `yaml:"_id"`
	Name         string         `yaml:"name"`
	SetScopes    []string       `yaml:"set_scopes"`
	SQLType      string         `yaml:"sql_type"`
	GolangType   string         `yaml:"go_type"`
	Default      string         `yaml:"default"`
	ConfigField  string         `yaml:"config_field"`
	CustomGetter bool           `yaml:"custom_getter"`
	CustomSetter bool           `yaml:"custom_setter"`
	Validation   ValidationSpec `yaml:"validation"`
}

type ValidationSpec struct {
	Enum []EnumVariantSpec `yaml:"enum"`
	Min  string            `yaml:"min"`
	Max  string            `yaml:"max"`
}

type EnumVariantSpec struct {
	Variant string `yaml:"variant"`
	Value   string `yaml:"value"`
}

func (sv SystemVariableSpec) NameVar() string {
	if sv.ID[0:3] == "sql" {
		return "SQL" + sv.ID[3:]
	}
	return strings.Title(sv.ID)
}

func (sv SystemVariableSpec) DefaultVar() string {
	return "default" + sv.NameVar()
}

func (sv SystemVariableSpec) GetterFunc() string {
	return "get" + sv.NameVar()
}

func (sv SystemVariableSpec) SetterFunc() string {
	return "set" + sv.NameVar()
}

var goTypeBySQLType = map[string]string{
	"SQLInt":     "int64",
	"SQLBoolean": "bool",
	"SQLVarchar": "string",
	"SQLUint":    "uint64",
}

func (sv SystemVariableSpec) GoType() string {
	if sv.GolangType != "" {
		return sv.GolangType
	}
	goType, ok := goTypeBySQLType[sv.SQLType]
	if !ok {
		panic(fmt.Sprintf("could not find go type for sql type %q", sv.SQLType))
	}
	return goType
}

func (sv SystemVariableSpec) ConvertFunc() string {
	return "convert" + strings.Title(sv.GoType())
}

func (sv SystemVariableSpec) ContainerField() string {
	return sv.ID
}

func (sv SystemVariableSpec) SetScopeExpr() string {
	if len(sv.SetScopes) == 0 {
		return "Scope(0)"
	}

	scopeStrs := []string{}
	for _, scope := range sv.SetScopes {
		scopeStrs = append(scopeStrs, strings.Title(scope)+"Scope")
	}

	return strings.Join(scopeStrs, " | ")
}

func (sv SystemVariableSpec) SQLTypeExpr() string {
	return "schema." + sv.SQLType
}

type VariablesSpec struct {
	SystemVariables []SystemVariableSpec `yaml:"system_variables"`
}

func (v *VariablesSpec) Parse(filename string) error {
	f, err := os.Open(filename)
	if err != nil {
		return err
	}
	decoder := yaml.NewDecoder(f)
	err = decoder.Decode(v)
	if err != nil {
		return fmt.Errorf("Error parsing yaml file: %v", err)
	}
	return nil
}

func (v *VariablesSpec) Generate(w io.Writer) error {
	tmplString := `// Code generated by 'go generate'. DO NOT EDIT.

package variable

import (
    "fmt"
    "math"

    "github.com/10gen/sqlproxy/collation"
    "github.com/10gen/sqlproxy/internal/config"
    "github.com/10gen/sqlproxy/internal/mysqlerrors"
    "github.com/10gen/sqlproxy/schema"
)

// These variables hold system variable names.
const (
{{- range .SystemVariables}}
    {{.NameVar}} Name = "{{.Name}}"
{{- end}}
)

// These are constants representing variants of enum-style variables.
const (
{{- range .SystemVariables}}
{{-  $var := . }}
{{- if .Validation.Enum}}
// {{.NameVar}} variants
{{range .Validation.Enum -}}
    {{.Variant}}{{$var.NameVar}} = "{{.Value}}"
{{end}}
{{- end}}
{{- end}}
)

// These are constants representing variables' default values.
var (
{{- range .SystemVariables}}
    {{.DefaultVar}} {{.GoType}} = {{.Default}}
{{- end}}
)

type systemVariableContainer struct {
{{- range .SystemVariables}}
    {{.ContainerField}} {{.GoType}}
{{- end}}
}

func (svc *systemVariableContainer) setDefaults() {
{{- range .SystemVariables}}
    svc.{{.ContainerField}} = {{.DefaultVar}}
{{- end}}
}

func (svc *systemVariableContainer) setFromConfig(cfg *config.Config) {
{{- range .SystemVariables}}
{{- if .ConfigField}}
    svc.{{.ContainerField}} = cfg.{{.ConfigField}}
{{- end}}
{{- end}}
}

func init() {
{{- range .SystemVariables}}

    definitions[{{.NameVar}}] = &definition{
        Name: {{.NameVar}},
        Kind: SystemKind,
        AllowedSetScopes: {{.SetScopeExpr}},
        SQLType: {{.SQLTypeExpr}},
        GetValue: {{if .CustomGetter}}{{.GetterFunc}}{{else}}func(c *Container) interface{} { return c.systemVariableContainer.{{.ContainerField}} }{{end}},
        SetValue: {{.SetterFunc}},
    }
{{- end}}
}

{{- range .SystemVariables}}
{{- $var := .}}
{{if .CustomSetter}}{{else}}
func {{.SetterFunc}}(c *Container, v interface{}) error {
    val, ok := {{.ConvertFunc}}(v)
    if !ok {
        return wrongTypeError({{.NameVar}}, v)
    }

    {{if .Validation.Min}}
    if val < {{.Validation.Min}} {
        return mysqlerrors.Defaultf(mysqlerrors.ErWrongValueForVar, {{.NameVar}}, val)
    }
    {{end}}
    {{if .Validation.Max}}
    if val > {{.Validation.Max}} {
        return mysqlerrors.Defaultf(mysqlerrors.ErWrongValueForVar, {{.NameVar}}, val)
    }
    {{end}}
    {{if .Validation.Enum}}
    switch val {
    {{- range .Validation.Enum}}
    case {{.Variant}}{{$var.NameVar}}:
        // valid
    {{- end}}
    default:
        return mysqlerrors.Defaultf(mysqlerrors.ErWrongValueForVar, {{$var.NameVar}}, val)
    }
    {{end}}

    c.systemVariableContainer.{{.ContainerField}} = val
    return nil
}
{{- end}}{{end}}
`

	tmpl, err := template.New("vars").Parse(tmplString)
	if err != nil {
		return fmt.Errorf("error parsing template: %v", err)
	}

	return tmpl.Execute(w, v)
}
