[package]
name = "visitgen-test"
version = "0.1.0"
authors = ["Patrick Meredith <pmeredit@protonmail.com>"]
edition = "2021"

[dependencies]
linked-hash-map = "0.5.4"
mongosql-datastructures = { path = "../mongosql-datastructures" }
visitgen = { path = "../visitgen" }
