[package]
name = "visitgen-test"
version = "0.1.0"
authors = ["Patrick Meredith <pmeredit@protonmail.com>"]
edition.workspace = true

[dependencies]
linked-hash-map = { workspace = true }
mongosql-datastructures = { path = "../mongosql-datastructures" }
visitgen = { path = "../visitgen" }
lazy_static = { workspace = true }
